# Chronology of Key Dates

1878

First Zionist agricultural colony in Palestine (Petah Tikva)



1882

25,000 Jewish immigrants begin to settle in Palestine, mainly from eastern Europe



1891

Baron Maurice de Hirsch, a German, founds the Jewish Colonization Association in London to aid Zionist settlers in Palestine



1896

Der Judenstaat, a book advocating the establishment of a Jewish state, is published by Austro-Hungarian Jewish writer Theodor Herzl

Jewish Colonization Association (JCA) begins operations in Palestine



1897

Zionist Congress calls for a home for Jewish people in Palestine Pamphlet by founder of socialist Zionism, Nahman Syrkin, says Palestine “must be evacuated for the Jews”.

First Zionist Congress in Switzerland sets up the World Zionist Association (WZO) and petitions for “a home for the Jewish people in Palestine”.



1901

Jewish National Fund (JNF) set up to acquire land in Palestine for the WZO; the land is to be used and worked solely by Jews.



1904

Tensions between Zionists and Palestinian farmers in Tiberias area



1904–1914

40,000 Zionist immigrants arrive in Palestine; Jews now total 6% of the population.



1905

Israel Zangwill states Jews must drive out the Arabs or “grapple with the problem of a large alien population ...”



1907

First kibbutz established



1909

Tel Aviv founded north of Jaffa



1911

Memo to Zionist Executive speaks of “limited population transfer”.



1914

World War I starts



1917

Balfour Declaration; British Secretary of State pledges support for “a Jewish national home in Palestine”. Ottoman forces in Jerusalem surrender to British General Allenby



1918

Palestine occupied by Allies under Allenby

World War 1 over, Ottoman rule in Palestine ends



1919

First Palestinian National Congress in Jerusalem rejects Balfour declaration, demands independence

Chaim Weizmann, of the Zionist Commission at the Paris Peace Conference calls for a Palestine “as Jewish as England is English” Other Commission members say “as many Arabs as possible should be persuaded to emigrate”.

Winston Churchill wrote “there are Jews, whom we are pledged to introduce into Palestine, and who take it for granted that the local population will be cleared out to suit their convenience”.



1919–1933

35,000 Zionists immigrate to Palestine. Jews now total 12% of the population and hold 3% of the land



1920

Founding of Hagana, Zionist underground military organisation

Britain is assigned the Palestinian Mandate by the Supreme Council of San Remo Peace Conference



1921

Protests in Jaffa against large-scale Zionist immigration



1922

League of Nations Council approves Britain’s Mandate for Palestine

British census of Palestine: 78% Muslim, 11% Jewish, 9.6% Christian, total population 757,182



1923

British Mandate for Palestine officially comes into force



1924–28

67,000 Zionist immigrants come to Palestine, half of whom are from Poland, raising Jewish population to 16%. Jews now own 4% of land



1925

In Paris the Revisionist Party is founded, which insists on the founding of a Jewish state in Palestine and Transjordan



1929

Riots in Palestine over claims to the Wailing Wall, with 133 Jews and 116 Arabs killed, mainly by British



1930

International Commission founded by the League of Nations to establish the legal status of Jews and Arabs at the Wailing Wall.



1931

Irgun (IZL) founded to support more militancy against Arabs

Census shows total population of 1.03 million, 16.9% Jewish British director of development for Palestine publishes report on “landless Arabs” caused by Zionist colonization



1932

First regularly constituted Palestinian political party, the Istliqlal (Independence) Party, founded



1935

Arms smuggling by Zionist groups discovered at Jaffa port



1936

A conference of Palestinian National Committees demands “no taxation without representation”.



1937

Peel Commission recommends partition of Palestine, with 33% of the country to become a Jewish state. Part of the Palestinian population is to be transferred from this state.

British dissolve all Palestinian political organisations, deport five leaders, establish military courts against rebellion by Palestinians



1938

Irgun bombings kill 119 Palestinians. Palestinian bombs and mines kill 8 Jews

British bring reinforcements to help suppress rebellion



1939

Zionist leader Jabotinsky writes: “... the Arabs must make room for the Jews in Eretz Israel. If it was possible to transfer the Baltic peoples, it is also possible to move the Palestinian Arabs.”

British House of Commons votes in approval of a White Paper which plans conditional independence of Palestine after 10 years and the immigration of 15,000 Jews into Palestine each year for the next 5 years

World War II begins



1940

Land Transfer Regulations come into force, protecting Palestinian land against Zionist acquisition



1943

Five-year limit planned in White Paper of 1939 extended



1945

World War II ends



1947

Britain tells newly formed UN that it will withdraw from Palestine

UN appoints committee (UNSCOP) on Palestine

UNSCOP recommends partition

November 29: UN adopts Resolution 181 on partition of Palestine

Mass expulsion by the Jews of the indigenous Palestinian Arabs begins



1948

January





‘Abd al-Qadir al-Husayni returns to Palestine after ten-year exile to form a group to resist partition



20

Britain plans to hand over areas of land to whichever group is predominant in the region



February





War breaks out between Jews and Arabs



18

Hagana announces military service and calls up 25–35 year old men and women



24

US delegate to UN announces that the role of the Security Council is peacekeeping rather than enforcing partition



March





6

Hagana announces mobilization



10

Plan Dalet, the Zionist blueprint for the cleansing of Palestine, finalised



18

President Truman pledges support to the Zionist cause



19–20

Arab leaders decide to accept a truce and limited trusteeship rather than partition, as suggested by UN Security Council. Jews reject the truce



30 March–15 May





Coastal “clearing” operation undertaken by Hagana, expelling Palestinians from the coastal area between Haifa and Jaffa



April





1

First delivery of Czech arms arrives for Hagana; includes 4,500 rifles, 200 light machine guns, 5 million rounds of ammunition



4

Plan Dalet launched by Hagana. Villages along the Tel-Aviv-Jerusalem road captured and residents expelled



9

The massacre of Deir Yassin



17

Security Council resolution demands a truce



20

Palestine trusteeship plan submitted to UN by US



22

Haifa cleansed of its Palestinian population



26–30

Hagana attacks an area of East Jerusalem, and are forced to hand it over to the British. Hagana captures an area of West Jerusalem. All Palestinians in West Jerusalem expelled by the Jewish forces



May





3

Report claims that between 175,000 and 250,000





Palestinians have been forced from their homes



12–14

Czech arms arrive for Hagana



13

Arab Legion attacks Jewish communities in retaliation for Jewish military action



13

Jaffa surrenders to Hagana



14

Israel declares independence as British Mandate ends.





President Truman recognizes State of Israel



20

Count Bernadotte appointed as UN mediator in Palestine



22

UN Security resolution demands ceasefire



11 June–8 July

First Truce established



July





8–18

Fighting breaks out anew as IDF capture Lydd and Ramla



17

IDF launch an offensive but fail to capture Old City of Jerusalem



18 July–15 Oct

Second Truce established, broken by the capture of several villages by IDF



September





17

UN mediator Count Bernadotte assassinated by Jewish terrorists in Jerusalem. New UN mediator is Ralph Bunche



October





29–31

Thousands of Palestinians are expelled during Operation Hiram



November





4

UN Security Council calls for immediate truce and withdrawal of forces.

UN adopts Resolution 194 on Palestinian refugee right of return

Israel blocks return



November – 1949

IDF begins to expel villagers from settlements inside the Lebanese border



1949





24 February

Israeli–Egyptian Armistice



end February

Between 2000 and 3000 villagers expelled from the Faluja pocket by IDF



23 March

Israeli–Lebanese Armistice



3 April

Israeli–Jordanian Armistice



20 July

Syrian–Israeli Armistice


