# Maps and Tables

## Maps

This map, showing the area of Palestine claimed by the World Zionist Organisation, was officially presented to the Paris Peace Conference, 1919





The Peel Commission Partition Plan, 1937. This became the Palestine Partition Commission Plan A the following year





Palestine Partition Commission Plan B, 1938





Palestine Partition Commission Plan C, 1938





United Nations Partition Plan, adopted as General Assembly Resolution 181 (29 November 1947)





1949 Armistice Agreement





Palestinian villages depopulated, 1947–1949

## Tables



TABLE 1: PALESTINE: PALESTINIAN AND JEWISH LAND OWNERSHIP IN PERCENTAGES BY DISTRICT, 19451





TABLE 2: PALESTINE: DISTRIBUTION OF POPULATION BY DISTRICT SHOWING PERCENTAGES OF PALESTINIANS AND JEWS, 19463





1 The source for this table is Village Statistics (Jerusalem: Palestine Government, 1945).



2 The category of “public ownership” under the British Mandate derived from the Ottoman system of land tenure, which included state domain, & private and communal leasehold.



3 The source for this table is the Supplement to a Survey of Palestine (Jerusalem: Government Printer, June 1947).
