# The Drive for an Exclusively Jewish State

> The United Nations General Assembly strongly rejects policies and ideologies aimed at promoting ethnic cleansing in any form

UNGA Resolution 47/80, 16 December 1992

## ZIONISM'S IDEOLOGICAL MOTIVATION

Zionism emerged in the late 1880s in central and eastern Europe as a national revival movement, prompted by the growing pressure on Jews in those regions either to assimilate totally or risk continuing persecution (though, as we know, even complete assimilation was no safeguard against annihilation in the case of Nazi Germany). By the beginning of the twentieth century, most of the leaders of the Zionist movement associated this national revival with the colonization of Palestine. Others, especially the founder of the movement, Theodor Herzl, were more ambivalent, but after his death, in 1904, the orientation towards Palestine was fixed and consensual.

Eretz Israel, the name for Palestine in the Jewish religion, had been revered throughout the centuries by generations of Jews as a place for holy pilgrimage, never as a future secular state. Jewish tradition and religion clearly instruct Jews to await the coming of the promised Messiah at ‘the end of times’ before they can return to Eretz Israel as a sovereign people in a Jewish theocracy, that is, as the obedient servants of God (this is why today several streams of Ultra-Orthodox Jews are either non or anti-Zionist). In other words, Zionism secularised and nationalised Judaism. To bring their project to fruition, the Zionist thinkers claimed the biblical territory and recreated, indeed reinvented, it as the cradle of their new nationalist movement. As they saw it, Palestine was occupied by ‘strangers’ and had to be repossessed. ‘Strangers’ here meant everyone not Jewish who had been living in Palestine since the Roman period.1 In fact, for many Zionists Palestine was not even an ‘occupied’ land when they first arrived there in 1882, but rather an ‘empty’ one: the native Palestinians who lived there were largely invisible to them or, if not, were part of nature’s hardship and as such were to be conquered and removed. Nothing, neither rocks nor Palestinians, was to stand in the way of the national ‘redemption’ of the land the Zionist movement coveted.2

Until the occupation of Palestine by Britain in 1918, Zionism was a blend of nationalist ideology and colonialist practice. It was limited in scope: Zionists made up no more than five per cent of the country’s overall population at that time. Living in colonies, they did not affect, nor were they particularly noticed by, the local population. The potential for a future Jewish takeover of the country and the expulsion of the indigenous Palestinian people, which historians have so clearly recognised in retrospect in the writings of the founding fathers of Zionism, became evident to some Palestinian leaders even before the First World War; others were less interested in the movement.

Historical evidence shows that at some time between 1905 and 1910, several Palestinian leaders discussed Zionism as a political movement aiming to purchase land, assets and power in Palestine, although the destructive potential was not fully comprehended at that period. Many members of the local elite saw it as part of the European missionary and colonialist drive – which in part it was, but of course it had an additional edge to it that turned into a dangerous enterprise for the native population.3

This potential was not often discussed or articulated by the Zionist leaders themselves, but some Palestinian notables and intellectuals must have sensed the looming danger, since we find them trying to convince the Ottoman government in Istanbul to limit, if not totally prohibit, Jewish immigration and settlement into Palestine, which was under Turkish rule until 1918.4

The Palestinian member of the Ottoman Parliament, Said al-Husayni, claimed on 6 May 1911 that ‘the Jews intend to create a state in the area that will include Palestine, Syria and Iraq’.5 However, Al-Husayni belonged to a family, and a group of local notables, who until the 1930s preached against the Zionist colonization while selling lands to the newcomers. As the Mandatory years went by, the sense of a looming danger, indeed a catastrophe, settled in among the more intellectual sections of the elite,6 but it was never translated into proper preparations for the existential danger awaiting their society.

Others around Palestine, such as the leading Egyptian literati, saw the movement of Jews into Palestine as an irresponsible attempt on the part of Europe to transfer its poorest and often stateless people into the country, not as part of a master plan aimed at the dispossession of the local people. To them, this movement of wretched people seemed but a minor threat compared with the far more conspicuous attempt European colonial powers and churches were making to take over the ‘Holy Land’ through their missionaries, diplomats and colonies.7 Indeed, prior to the British occupation of Palestine at the end of 1917, the Zionists were vague where their actual plans were concerned, not so much for lack of orientation, but more because of the need to prioritise the concerns of the as yet small Jewish immigrant community: there was always the threat of being thrown out again by the government in Istanbul.

However, when a clearer vision for the future needed to be spelled out for internal consumption, we find no ambiguity whatsoever. What the Zionists anticipated was the creation of a Jewish state in Palestine in order to escape a history of persecutions and pogroms in the West, invoking the religious ‘redemption’ of an ‘ancient homeland’ as their means. This was the official narrative, and it no doubt genuinely expressed the motivation of most of the Zionist leadership’s members. But the more critical view today sees the Zionist drive to settle in Palestine, instead of other possible locations, as closely interwoven with nineteenth-century Christian millenarianism and European colonialism. The various Protestant missionary societies and the governments in the European Concert competed among themselves over the future of a ‘Christian’ Palestine that they wanted to pry away from the Ottoman Empire. The more religious among the aspirants in the West regarded the return of the Jews to Palestine as a chapter in the divine scheme, precipitating the second coming of Christ and the creation of a pietist state there. This religious zeal inspired pious politicians, such as Lloyd George, the British prime minister during the First World War, to act with even greater commitment for the success of the Zionist project. This did not prevent him from supplying his government at the same time with a host of ‘strategic’, rather than messianic, considerations for why Palestine should be colonised by the Zionist movement, which were mostly infused by his own overriding distrust of, and disdain for, ‘Arabs’ and ‘Mohammedans’, as he called the Palestinians.8

Recent scholarship also tends to question the more Marxist flavour that the official Israeli historiography has claimed for the early colonization of Palestine by portraying Zionism as a positive endeavour to carry the socialist and Marxist revolutions beyond their less successful attempts in Russia.9 The more critical view depicts this aspiration as doubtful at best and as manipulative at worst. Indeed, much like today’s more liberal-minded Israeli Jews who are ready to drop the principles of democracy when faced with the prospect of a demographic majority of non-Jews in the country, so, it seems, did the socialist Zionists quickly substitute their more universal dreams with the powerful allure of nationalism. And when the main objective became making Palestine exclusively Jewish rather than socialist, it was significantly the Labour movement within Zionism that instituted and implemented the ethnic cleansing of the local population.

The early Zionist settlers directed most of their energy and resources towards buying up plots of land in an attempt to enter the local labour market and create social and communal networks that could sustain their as yet small and economically vulnerable group of newcomers. The more precise strategies of how best to take over Palestine as a whole and create a nation-state in the country, or in part of it, were a later development, closely associated with British ideas of how best to solve the conflict Britain itself had done so much to exacerbate.

The moment British Foreign Secretary Lord Balfour gave the Zionist movement his promise in 1917 to establish a national home for the Jews in Palestine,10 he opened the door to the endless conflict that would soon engulf the country and its people. In the pledge he made in his government’s name, Balfour promised to protect the aspirations of the non-Jewish population – a strange reference to the vast native majority – but the declaration clashed precipitately with both the aspirations and natural rights of the Palestinians for nationhood and independence.

By the end of the 1920s, it was clear that this proposal had a potentially violent core, as it had already claimed the lives of hundreds of Palestinians and Jews. This now prompted the British to make a serious, albeit reluctant, attempt to solve the smouldering conflict.

Until 1928, the British government had treated Palestine as a state within the British sphere of influence, not as a colony; a state in which, under British tutelage, the promise to the Jews and the aspirations of the Palestinians could both be fulfilled. They tried to put in place a political structure that would represent both communities on an equal footing in the state’s parliament as well as in government. In practice, when the offer was made it was less equitable; it advantaged the Zionist colonies and discriminated against the Palestinian majority. The balance within the new proposed legislative council was in favour of the Jewish community who were to be allied with members appointed by the British administration.11

As the Palestinians made up the majority of between eighty and ninety per cent of the total population in the 1920s, they understandably refused at first to accept the British suggestion of parity, let alone one that disadvantaged them in practice – a position that encouraged the Zionist leaders to endorse it. A pattern now emerges: when, in 1928, the Palestinian leadership, apprehensive of the growing Jewish immigration into the country and the expansion of their settlements, agreed to accept the formula as a basis for negotiations, the Zionist leadership quickly rejected it. The Palestinian uprising in 1929 was the direct result of Britain’s refusal to implement at least their promise of parity after the Palestinians had been willing to set aside the democratic principal of majoritarian politics, which Britain had championed as the basis for negotiations in all the other Arab states within its sphere of influence.12

After the 1929 uprising, the Labour government in London appeared inclined to embrace the Palestinian demands, but the Zionist lobby succeeded in reorienting the British government comfortably back onto the Balfourian track. This made another uprising inevitable. It duly erupted in 1936 in the form of a popular rebellion fought with such determination that it forced the British government to station more troops in Palestine than there were in the Indian subcontinent. After three years, with brutal and ruthless attacks on the Palestinian countryside, the British military subdued the revolt. The Palestinian leadership was exiled, and the paramilitary units that had sustained the guerilla warfare against the Mandatory forces were disbanded. During this process many of the villagers involved were arrested, wounded or killed. The absence of most of the Palestinian leadership and of viable Palestinian fighting units gave the Jewish forces in 1947 an easy ride into the Palestinian countryside.

In between the two uprisings, the Zionist leadership had wasted no time in working out their plans for an exclusively Jewish presence in Palestine: first, in 1937, by accepting a modest portion of the land when they responded favourably to a recommendation by the British Royal Peel commission to partition Palestine into two states;13 and second, in 1942, by attempting a more maximalist strategy, demanding all of Palestine for itself. The geographical space it coveted may have changed with time and according to circumstances and opportunities, but the principal objective remained the same. The Zionist project could only be realised through the creation in Palestine of a purely Jewish state, both as a safe haven for Jews from persecution and a cradle for a new Jewish nationalism. And such a state had to be exclusively Jewish not only in its socio-political structure but also in its ethnic composition.

## MILITARY PREPARATIONS




From the outset, the British Mandatory authorities had allowed the Zionist movement to carve out an independent enclave for itself in Palestine as the infrastructure for a future state, and in the late 1930s the movement’s leaders were able to translate the abstract vision of Jewish exclusivity into more concrete plans. Zionist preparations for the eventuality of taking the land by force, should it fail to be granted to them through diplomacy, included the building of an efficient military organisation – with the help of sympathetic British officers – and the search for ample financial resources (for which they could tap the Jewish Diaspora). In many ways the creation of an embryonic diplomatic corps was also an integral part of the same general preparations that were aimed at snatching, by force, a state in Palestine.14

It was one British officer in particular, Orde Charles Wingate, who made the Zionist leaders realise more fully that the idea of Jewish statehood had to be closely associated with militarism and an army, first of all to protect the growing number of Jewish enclaves and colonies inside Palestine but also – more crucially – because acts of armed aggression were an effective deterrent against the possible resistance of the local Palestinians. From there, the road to contemplating the enforced transfer of the entire indigenous population would prove to be very short indeed.15

Orde Wingate was born in India in the early twentieth century to a military family and received a very religious upbringing. He began an Arabophile career in the Sudan, where he gained prestige with a particularly effective ambush policy against slave traders. In 1936, he was assigned to Palestine where he quickly became enchanted by the Zionist dream. He decided actively to encourage the Jewish settlers and started teaching their troops more effective combat tactics and retaliation methods against the local population. It is no wonder that his Zionist associates greatly admired him.

Wingate transformed the principal paramilitary organisation of the Jewish community in Palestine, the Hagana. Established in 1920, its name literally means ‘defence’ in Hebrew, ostensibly to indicate that its main purpose was protecting the Jewish colonies. Under the influence of Wingate, and the militant mood he inspired among its commanders, the Hagana quickly became the military arm of the Jewish Agency, the Zionist governing body in Palestine that in the end developed and then implemented plans for the Zionist military takeover of Palestine as a whole, and the ethnic cleansing of its native population.16

The Arab revolt gave the Hagana members a chance to practise the military tactics Wingate had taught them in the Palestinian rural areas, mostly in the form of retaliatory operations against such targets as roadside snipers or thieves taking goods from a kibbutz. The main objective, however, seems to have been to intimidate Palestinian communities who happened to live in proximity to Jewish settlements.

Wingate succeeded in attaching Hagana troops to the British forces during the Arab revolt so that they could learn even better what a ‘punitive mission’ to an Arab village ought to entail. For example, in June 1938 Jewish troops got their first taste of what it meant to occupy a Palestinian village: a Hagana unit and a British company jointly attacked a village on the border between Israel and Lebanon, and held it for a few hours.17

Amatziya Cohen, who took part in the operation, remembered the British sergeant who showed them how to use bayonets in attacking defenseless villagers: ‘I think you are all totally ignorant in your Ramat Yochanan [the training base for the Hagana] since you do not even know the elementary use of bayonets when attacking dirty Arabs: how can you put your left foot in front!’ he shouted at Amatziya and his friends after they had returned to base.18 Had this sergeant been around in 1948, he would have been proud to see how quickly Jewish troops were mastering the art of attacking villages.

The Hagana also gained valuable military experience in the Second World War, when many of its members volunteered for the British war effort. Others who remained behind in Palestine continued to monitor and infiltrate the 1200 or so Palestinian villages that had dotted the countryside for hundreds of years.





## THE VILLAGE FILES




More was needed than just savouring the excitement of attacking a Palestinian village: systematic planning was called for. The suggestion came from a young bespectacled historian from the Hebrew University by the name of Ben-Zion Luria, at the time an employee of the educational department of the Jewish Agency. Luria pointed out how useful it would be to have a detailed registry of all Arab villages, and proposed that the Jewish National Fund (JNF) conduct such an inventory. ‘This would greatly help the redemption of the land,’ he wrote to the JNF.19 He could not have chosen a better audience: his initiative to involve the JNF in the prospective ethnic cleansing was to generate added impetus and zeal to the expulsion plans that followed.

Founded in 1901, the JNF was the principal Zionist tool for the colonization of Palestine. It served as the agency the Zionist movement used to buy Palestinian land upon which it then settled Jewish immigrants. Inaugurated by the fifth Zionist Congress, it spearheaded the Zionization of Palestine throughout the Mandatory years. From the onset it was designed to become the ‘custodian’, on behalf of the Jewish people, of the land the Zionists gained possession of in Palestine. The JNF maintained this role after the creation of the State of Israel, with other missions being added to its primary role over time.20

Most of the JNF’s activities during the Mandatory period and surrounding the Nakba were closely associated with the name of Yossef Weitz, the head of its settlement department. Weitz was the quintessential Zionist colonialist. His main priority at the time was facilitating the eviction of Palestinian tenants from land bought from absentee landlords who were likely to live at some distance from their land or even outside the country, the Mandate system having created borders where before there were none. Traditionally, when ownership of a plot of land, or even a whole village, changed hands, this did not mean that the farmers or villagers themselves had to move;21 Palestine was an agricultural society, and the new landlord would need the tenants to continue cultivating his lands. But with the advent of Zionism all this changed. Weitz personally visited the newly purchased plot of land often accompanied by his closest aides, and encouraged the new Jewish owners to throw out the local tenants, even if the owner had no use for the entire piece of land. One of Weitz’s closest aides, Yossef Nachmani, at one point reported to him that ‘unfortunately’ tenants refused to leave and some of the new Jewish land owners displayed, as he put it, ‘cowardice by pondering the option of allowing them to stay.’22 It was the job of Nachmani and other aides to make sure that such ‘weaknesses’ did not persist: under their supervision these evictions quickly became more comprehensive and effective.

The impact of such activities at the time remained limited because Zionist resources after all were scarce, Palestinian resistance fierce, and the British policies restrictive. By the end of the Mandate in 1948, the Jewish community owned around 5.8% of the land in Palestine. But the appetite was for more, if only for the available resources to expand and new opportunities open up; this is why Weitz waxed lyrical when he heard about the village files, immediately suggesting turning them into a ‘national project’.23

All involved became fervent supporters of the idea. Yitzhak Ben-Zvi, a prominent member of the Zionist leadership, a historian and later the second president of Israel, explained in a letter to Moshe Shertock (Sharett), the head of the political department of the Jewish Agency (and later one of Israel’s prime ministers), that apart from topographically recording the layout of the villages, the project should also include exposing the ‘Hebraic origins’ of each village. Furthermore, it was important for the Hagana to know which of the villages were relatively new, as some of them had been built ‘only’ during the Egyptian occupation of Palestine in the 1830s.24

The main endeavour, however, was mapping the villages, and therefore a topographer from the Hebrew University working in the Mandatory cartography department was recruited to the enterprise. He suggested conducting an aerial photographic surveys, and proudly showed Ben-Gurion two such aerial maps for the villages of Sindiyana and Sabbarin (these maps, now in the Israeli State Archives, are all that remains of these villages after 1948).

The best professional photographers in the country were now invited to join the initiative. Yitzhak Shefer, from Tel-Aviv, and Margot Sadeh, the wife of Yitzhak Sadeh, the chief of the Palmach (the commando units of the Hagana), were recruited too. The film laboratory operated in Margot’s house with an irrigation company serving as a front: the lab had to be hidden from the British authorities who could have regarded it as an illegal intelligence effort directed against them. The British did have prior knowledge of it, but never succeeded in spotting the secret hideout. In 1947, this whole cartographic department was moved to the Red House.25

The end results of both the topographic and Orientalist efforts were the detailed files the Zionist experts gradually built up for each of Palestine’s villages. By the late 1930s, this ‘archive’ was almost complete. Precise details were recorded about the topographic location of each village, its access roads, quality of land, water springs, main sources of income, its sociopolitical composition, religious affiliations, names of its muhktars, its relationship with other villages, the age of individual men (sixteen to fifty) and many more. An important category was an index of ‘hostility’ (towards the Zionist project, that is), decided by the level of the village’s participation in the revolt of 1936. There was a list of everyone who had been involved in the revolt and the families of those who had lost someone in the fight against the British. Particular attention was given to people who had allegedly killed Jews. As we shall see, in 1948 these last bits of information fuelled the worst atrocities in the villages, leading to mass executions and torture.

Regular members of the Hagana who were entrusted with collecting the data on ‘reconnaissance’ journeys into the villages realised, from the start, that this was not a mere academic exercise in geography. One of these was Moshe Pasternak, who joined one of the early excursions and data collection operations in 1940. He recalled many years later:

We had to study the basic structure of the Arab village. This means the structure and how best to attack it. In the military schools, I had been taught how to attack a modern European city, not a primitive village in the Near East. We could not compare it [an Arab village] to a Polish, or an Austrian one. The Arab village, unlike the European ones, was built topographically on hills. That meant we had to find out how best to approach the village from above or enter it from below. We had to train our ‘Arabists’ [the Orientalists who operated a network of collaborators] how best to work with informants.26





Indeed the problem noted in many of the villages’ files was how to create a collaborationist system with the people Pasternak and his friends regarded as primitive and barbaric: ‘People who like to drink coffee and eat rice with their hands, which made it very difficult to use them as informants.’ In 1943, he remembered, there was a growing sense that finally they had a proper network of informants in place. That same year the village files were re-arranged to become even more systematic. This was mainly the work of one man, Ezra Danin, who would play a leading role in the ethnic cleansing of Palestine.27

In many ways, it was the recruitment of Ezra Danin, who had been taken out of his successful citrus grove business, that injected the intelligence work and the organisation of the village files with a new level of efficiency. Files in the post-1943 era included detailed descriptions of the husbandry, the cultivated land, the number of trees in plantations, the quality of each fruit grove (even of each single tree), the average amount of land per family, the number of cars, shop owners, members of workshops and the names of the artisans in each village and their skills.28 Later, meticulous detail was added about each clan and its political affiliation, the social stratification between notables and common peasants, and the names of the civil servants in the Mandatory government.

And as the data collection created its own momentum, one finds additional details popping up around 1945, such as descriptions of village mosques and the names of their imams, together with such characterisations as ‘he is an ordinary man’, and even precise accounts of the living rooms inside the homes of these dignitaries. Towards the end of the Mandatory period the information becomes more explicitly military orientated: the number of guards (most villages had none) and the quantity and quality of the arms at the villagers’ disposal (generally antiquated or even non-existent).29

Danin recruited a German Jew named Yaacov Shimoni, later to become one of Israel’s leading Orientalists, and put him in charge of special projects inside the villages, in particular supervising the work of the informants.30 One of these Danin and Shimoni nicknamed the ‘treasurer’ (ha-gizbar). This man, who proved a fountain of information for the files’ collectors, supervised the network of collaboration for them between 1941–1945. He was exposed in 1945 and killed by Palestinian militants.31

Danin and Shimoni were soon joined by two other people, Yehoshua Palmon and Tuvia Lishanski. These, too, are names to remember as they took an active part in preparing for the ethnic cleansing of Palestine. Lishanski was already busy in the 1940s with orchestrating campaigns against the tenants who lived on plots of lands the JNF had bought from present or absentee landlords, and he directed all his energy towards intimidating and then forcibly evicting these people from the lands their families had been cultivating for centuries.

Not far away from the village of Furaydis and the ‘veteran’ Jewish settlement Zikhron Yaacov, where today a road connects the coastal highway with Marj Ibn Amir (Emeq Izrael) through Wadi Milk, lies a youth village (a kind of boarding school for Zionist youth) called Shefeya. It was here that in 1944 special units in the service of the village files project received their training and it was from here that they went out on their reconnaissance missions. Shefeya looked very much like a spy village in the Cold War: Jews walking around speaking Arabic and trying to emulate what they believed were the customary ways of life and behaviour of rural Palestinians.32

In 2002, one of the first recruits to this special training base recalled his first reconnaissance mission to the nearby village of Umm al-Zinat in 1944. Their aim had been to survey the village and bring back information such as where the mukhtar lived, where the mosque was located, where the rich people of the village resided and who had been active in the 1936 revolt. This was not a very dangerous mission as the infiltrators knew they could exploit the traditional Arab hospitality code, and were even guests at the home of the mukhtar himself. As they failed to collect in one day all the data they were seeking, they asked to be invited back. For their second visit they had been instructed to get information about the fertility of the land, the quality of which seemed to have impressed them greatly. In 1948, Umm al-Zinat was destroyed and all its inhabitants expelled without any provocation on their part whatsoever.33

The final update of the village files took place in 1947. It focused on creating lists of ‘wanted’ persons in each village. In 1948 Jewish troops used these lists for the search-and-arrest operations they carried out as soon as they had occupied a village. That is, the men in the village would be lined up and those appearing on the lists would then be identified, often by the same person who had informed on them in the first place but who would now be wearing a cloth sack over his head with two holes cut out for his eyes so as not to be recognised. The men who were picked out were often shot on the spot. Criteria for inclusion in these lists were involvement in the Palestinian national movement, having close ties to the leader of the movement, the Mufti al-Hajj Amin al-Husayni, and, as mentioned, having participated in actions against the British and the Zionists.34 Other reasons for being included in the lists were a variety of allegations, such as ‘known to have travelled to Lebanon’ or ‘arrested by the British authorities for being a member of a national committee in the village’.35

The first category, involvement in the Palestinian national movement, was very liberally defined and could include whole villages. Affiliation with the Mufti or to the political party he headed was very common. After all, his party had dominated local Palestinian politics ever since the British Mandate was officially established in 1923. The party’s members went on to win national and municipal elections and hold the prominent positions in the Arab Higher Committee that became the embryonic government of the Palestinians. In the eyes of the Zionist experts this constituted a crime. If we look at the 1947 files, we find that villages with about 1500 inhabitants usually had between twenty and thirty such suspects (for instance, around the southern Carmel mountains, south of Haifa, Umm al-Zinat had thirty such suspects and the nearby village of Damun had twenty-five).36

Yigael Yadin recalled that it was this minute and detailed knowledge of what was happening in each single Palestinian village that enabled the Zionist military command in November 1947 to conclude ‘that the Palestine Arabs had nobody to organise them properly.’ The only serious problem was the British: ‘If not for the British, we could have quelled the Arab riot [the opposition to the UN Partition Resolution in 1947] in one month.’37





## FACING THE BRITISH: 1945–1947




Beyond carefully charting rural Palestine in preparation for the future takeover of the country, the Zionist movement had by now also obtained a much clearer sense of how best to get the new state off the ground after the Second World War. A crucial factor in this was that the British had already destroyed the Palestinian leadership and its defence capabilities when they suppressed the 1936 Revolt, thus allowing the Zionist leadership ample time and space to set out their next moves. Once the danger of a Nazi invasion into Palestine was removed in 1942, the Zionist leaders became more keenly aware that the sole obstacle that stood in their way of successfully seizing the land was the British presence, not any Palestinian resistance. This explains why, for example, in a meeting in the Biltmore Hotel in New York in 1942, we find Ben-Gurion putting demands on the table for a Jewish commonwealth over the whole of Mandatory Palestine.38

As the Second World War drew to a close, the Jewish leadership in Palestine embarked on a campaign to push the British out of the country. Simultaneously, they continued to map out their plans for the Palestinian population, the country’s seventy-five per cent majority. Leading Zionist figures did not air their views in public, but confided their thoughts only to their close associates or entered them into their diaries. One of them, Yossef Weitz, wrote in 1940: ‘it is our right to transfer the Arabs’ and ‘The Arabs should go!’39 Ben-Gurion himself, writing to his son in 1937, appeared convinced that this was the only course of action open to Zionism: ‘The Arabs will have to go, but one needs an opportune moment for making it happen, such as a war.’40 The opportune moment came in 1948. Ben-Gurion is in many ways the founder of the State of Israel and was its first prime minister. He also masterminded the ethnic cleansing of Palestine.





## DAVID BEN-GURION: THE ARCHITECT




David Ben-Gurion led the Zionist movement from the mid 1920s until well into the 1960s. Born David Gruen in 1886 in Plonsk, Poland (then part of Czarist Russia), he had come to Palestine in 1906, already an ardent Zionist. Short of stature, with a large shock of white hair swept backwards and invariably dressed in khaki uniform, his figure is by now familiar to many around the world. When the ethnic cleansing operations began, he added a pistol to his military gear and a kufiyya around his neck, imitating the way his elite units were fitted out. He was by then approximately sixty years old and, although suffering from serious backaches, he was the Zionist movement’s highly energetic and hard-working leader.

His central role in deciding the fate of the Palestinians stemmed from the complete control he exercised over all issues of security and defence in the Jewish community in Palestine. He had risen to power as a union leader, but was soon busy engineering the Jewish State in-the-making. When the British offered the Jewish community a state in 1937, but over a much smaller portion of Palestine than they had in mind, Ben-Gurion accepted the proposal as a good start, but he aspired to Jewish sovereignty over as much of Palestine as possible. He then swayed the Zionist leadership into accepting both his supreme authority and the fundamental notion that future statehood meant absolute Jewish domination. How to achieve such a purely Jewish state was also discussed under his guidance around 1937. Two magic words now emerged: Force and Opportunity. The Jewish state could only be won by force, but one had to wait for the opportune historical moment to come along in order to be able to deal ‘militarily’ with the demographic reality on the ground: the presence of a non-Jewish native majority population.

Ben-Gurion’s focus on long-term processes and comprehensive solutions was atypical of most of his colleagues in the Zionist leadership. They still hoped that by purchasing a piece of land here and a few houses there they would be able to establish the envisaged new reality. Ben-Gurion understood early on that this would never be enough – and of course he was right: by the end of the Mandate, as we have already seen, the Zionist movement had only been able to purchase around six per cent of the land.41

But even the more cautious Zionist leaders, such as Ben-Gurion’s second-in-command, Moshe Sharett, the ‘foreign minister’ of the Jewish community in Mandatory Palestine, associated the settlement of Jews in Palestine with the dispossession of the indigenous Palestinians. For example, on 13 December 1938, when giving a lecture to the employees of the Zionist organisations in Jerusalem, Sharett could report to them on a particularly satisfying achievement: the purchase of 2500 dunam in the Baysan Valley in eastern Palestine (one dunam equals 1000 square metres, or 0.1 hectares). He added a telling detail:

This purchase was accompanied, interestingly, by transfer of population [unsure of his audience’s familiarity with the term, he repeated it in English]. There is a tribe that resides west of the Jordan river and the purchase will include paying the tribe to move east of the river; by this [act] we will reduce the number of Arabs [in Palestine].42





In 1942, as we saw above, Ben-Gurion was already aiming much higher when he publicly staked out the Zionist claim for the whole of Palestine. As in the days of the Balfour declaration, Zionist leaders understood the promise to include the country as a whole. But he was a pragmatic colonialist as well as a state-builder. He knew that maximalist schemes such as the Biltmore programme, which clamoured for the whole of Mandatory Palestine, would not be deemed realistic. It was also, of course, impossible to pressure Britain while it was holding the fort against Nazi Germany in Europe. Consequently he lowered his ambitions during the Second World War. But the post-war British Labour government under Clement Attlee had different plans for Palestine. Now that Jews in Europe were no longer facing the danger of annihilation, and most of them preferred to leave for the other side of the Atlantic rather than head towards the Middle East, the new British cabinet and its energetic foreign secretary, Ernest Bevin, were looking for a solution that would be based on the wishes and interests of the people actually living in Palestine, and not of those the Zionist leaders claimed might want to move there – in other words, a democratic solution.

Armed, but especially terrorist, attacks by the Jewish underground militias failed to change that policy. Against the bombing of bridges, military bases and the British headquarters in Jerusalem (the King David Hotel), the British reacted mildly – especially in comparison with the brutal treatment they had meted out to Palestinian rebels in the 1930s. Retaliation took the form of a disarmament campaign of Jewish troops, a large number of whom they themselves had armed and recruited, first in the war against the Palestinian rebellion in 1937, and then against the Axis powers in 1939. Disarmament was very partial, but arrests were relatively numerous, enough for the Zionist leaders to realise they needed to pursue a more adaptive policy as long as the British were still responsible for law and order in the land. As we have already seen, in the immediate aftermath of the Second World War Britain held a disproportionately large number of troops – 100,000 – in a country of less than two million people. This definitely served as a deterrent, even when in the wake of the Jewish terrorist attack on the King David Hotel this force was somewhat reduced. It was these considerations that prompted Ben-Gurion to conclude that a somewhat more ‘reduced’ state, over eighty per cent of Palestine, would be sufficient to allow the Zionist movement to fulfill its dreams and ambitions.43

In the final days of August 1946, Ben-Gurion gathered together the leadership of the Zionist movement in a hotel in Paris, the Royal Monsue, to help him find an alternative to the Biltmore plan that had aimed to take over all of Palestine. An ‘old-new’ idea of the Zionist movement now resurfaced: partitioning Palestine. ‘Give us independence, even on a small part of the land,’ pleaded Nachum Goldman with the British government in London while his colleagues in Paris were deliberating their next move. Goldman was the most ‘dovish’ member of the Zionist leadership at the time, and his call for only a ‘small’ part of Palestine did not reflect Ben-Gurion’s ambitions: he accepted the principle but not the dimensions. ‘We will demand a large chunk of Palestine’ Ben-Gurion told those he had summoned to the French capital. Like generations of Israeli leaders after him, up to Ariel Sharon in 2005, Ben-Gurion found he had to hold back the more extremist Zionist members, and he told them that eighty to ninety per cent of Mandatory Palestine was enough to create a viable state, provided they were able to ensure Jewish predominance. Neither the concept nor the percentage would change over the next sixty years. A few months later the Jewish Agency translated Ben-Gurion’s ‘large chunk of Palestine’ into a map which it distributed to everyone relevant to the future of Palestine. This 1947 map envisaged a Jewish state that anticipated almost to the last dot pre-1967 Israel, i.e., Palestine without the West Bank and the Gaza Strip.44

During all these deliberations, the Zionist leaders never discussed the possibility of any resistance from the local population: their chief concern was the British and, maybe, the international response. This is not accidental. The Zionist leadership was aware of the total collapse of the Palestinian leadership after the Second World War and of the hesitant position the Arab states as a whole were displaying on the Palestine question. The desperate situation of the indigenous population of Palestine becomes poignantly clear the moment we realise that those who had crushed their liberation movement, the British Mandatory authorities, were now the only ones standing between them and a coolly determined and highly motivated Zionist movement that coveted most of their homeland. But worse was to come as Europe prepared to compensate the Jewish people for the Holocaust that had raged on its soil with a state in Palestine, ignoring at the same time that this could only come about at the expense of the indigenous Palestinians.

Given the power vacuum on the Palestinian side, it is not surprising to see the Zionist decision-makers act as though the Palestinians were not a factor to be considered. But, of course, they still formed the vast majority in the land, and as such they were a ‘problem’. Moreover, the Arab world, potentially at least, could come to their rescue and send in armies and provide arms. David Ben-Gurion was fully aware of this possible scenario, and therefore preoccupied himself and his closest associates with the issue of security, bitachon in Hebrew. This became an obsession Ben-Gurion nourished so carefully and successfully that it came to overshadow all other social and political issues on the agenda of the Jewish community in Palestine and later, of course, in Israel.45

Bitachon was then and remains until today a meta-term used by Zionist and, later, Israeli leaders to cover a wide range of issues and justify numerous core policies, from arms purchases abroad, internal struggle with other political parties, preparations for the future state, and the policy adopted against the local Palestinian population. The latter was retaliatory in nature and in discourse, but quite often provocative in action. From 1946 onwards, a more comprehensive set of strategic objectives emerged, aimed at consolidating the future scenarios and plans. David Ben-Gurion played a crucial role in shaping Israel’s bitachon outlook because of the structural changes he introduced into the Zionist decision-making mechanism that placed him at the top of what before had been a rather cumbersome and ineffective pyramid. When in 1946 the 22nd Zionist Congress entrusted Ben-Gurion with the defence portfolio, he had total control over all security issues of the Jewish community in Palestine.46

Though as yet without a state, Ben-Gurion already now functioned as defence minister and as a prime minister of sorts (given his authority to pass resolutions within a government). In many aspects he shared responsibility, and most issues on the agenda of the Jewish community were discussed in a democratic way within institutions that represented the composition of the major political groups among the Jews in Palestine. But as the time came nearer when crucial decisions needed to be made with regards to the fate of the Palestinians, Ben-Gurion began to ignore the official structure and started relying on more clandestine formations.

The major topic on the Zionist agenda in 1946 and 1947, the struggle against the British, resolved itself with the British decision, in February 1947, to quit Palestine and to transfer the Palestine question to the UN. In fact, the British had little choice: after the Holocaust they would never be able to deal with the looming Jewish rebellion as they had with the Arab one in the 1930s and, as the Labour party made up its mind to leave India, Palestine lost much of its attraction. A particularly cold winter in 1947 drove the message home to London that the Empire was on its way to become a second-rate power, its global influence dwarfed by the two new super-powers and its economy crippled by a capitalist system that caused Sterling to drop precipitously. Rather than hold on to remote places such as Palestine, the Labour party saw as its priority the building of a welfare state at home. In the end, Britain left in a hurry and with no regrets.47

Ben-Gurion had already realised by the end of 1946 that the British were on their way out, and with his aides began working on a general strategy that could be implemented against the Palestinian population the moment the British were gone. This strategy became Plan C, or Gimel in Hebrew.

Plan C was a revised version of two earlier plans, A and B. Plan A was also named the ‘Elimelech plan’, after Elimelech Avnir, the Hagana commander in Tel-Aviv who in 1937, at Ben-Gurion’s request, had already set out possible guidelines for the takeover of Palestine in the event of a British withdrawal. Plan B had been devised in 1946 and both plans were now fused into one to form Plan C.

Like Plans A and B, Plan C aimed to prepare the military forces of the Jewish community in Palestine for the offensive campaigns they would be engaged in against rural and urban Palestine the moment the British were gone. The purpose of such actions would be to ‘deter’ the Palestinian population from attacking Jewish settlements, and to retaliate for assaults on Jewish houses, roads and traffic. Plan C spelled out clearly what punitive actions of this kind would entail:

* Killing the Palestinian political leadership.
* Killing Palestinian inciters and their financial supporters.
* Killing Palestinians who acted against Jews.
* Killing senior Palestinian officers and officials [in the Mandatory system].
* Damaging Palestinian transportation.
* Damaging the sources of Palestinian livelihoods: water wells, mills, etc.
* Attacking nearby Palestinian villages likely to assist in future attacks.
* Attacking Palestinian clubs, coffee houses, meeting places, etc.

Plan C added that all data required for the performance of these actions could be found in the village files: lists of leaders, activists, ‘potential human targets’, the precise layout of villages, and so on.48

However, within a few months, yet another plan was drawn up: Plan D (Dalet).49 It was this plan that sealed the fate of the Palestinians within the territory the Zionist Leaders had set their eyes on for their future Jewish State. Indifferent as to whether these Palestinians might decide to collaborate with or oppose their Jewish State, Plan Dalet called for their systematic and total expulsion from their homeland.


