---
title: "Partition and Destruction"
subtitle: "UN Resolution 181 and its Impact"
---

> The most brutal element of the conflict in the former Yugoslavia was the ‘ethnic cleansing’, designed to force minority groups out of areas occupied by a different majority.

> Previously, different peoples had lived together in the same village and there had been no division into ethnic groups and no ethnic cleansing. Thus, the causes of the situation were clearly political.

Summary record of the UN Committee on the Elimination of Racial Discrimination with regard to the former Yugoslavia, 6 March 1995.



## PALESTINE'S POPULATION




When the Zionist movement started its ethnic cleansing operations in Palestine, in early December 1947, the country had a ‘mixed’ population of Palestinians and Jews. The indigenous Palestinians made up the two-third majority, down from ninety per cent at the start of the Mandate. One third were Jewish newcomers, i.e., Zionist settlers and refugees from war torn Europe, most of whom had arrived in Palestine since the 1920s.1 As of the late nineteenth century, the indigenous Palestinians had been seeking the right of self-determination, at first within a pan-Arab identity, but then, soon after the First World War, through the Mandate system that promised to lead the new nation-states it had created in the Middle East to independence and towards a future based on principles of democracy. But Britain’s Mandate charter for Palestine also incorporated, wholesale, the 1917 Balfour Declaration and, with it, Britain’s promise to the Zionist movement to secure a ‘homeland’ for the Jews in Palestine.

Despite Britain’s pro-Zionist policies and the presence of a growing Jewish minority, Palestine was still very much an Arab country by the end of the Mandate. Almost all of the cultivated land in Palestine was held by the indigenous population – only 5.8% was in Jewish ownership in 1947 – which makes the use here of the adjective ‘mixed’ somewhat misleading, to say the least. Although the Zionist leaders had tried to persuade Jewish immigrants, ever since the movement had set foot in Palestine, to settle in the countryside, they had failed to do so: Jewish newcomers overwhelmingly preferred the cities and towns. As a result, most of the Zionist settler colonies in the rural areas lay far apart from each other; in some areas, such as the Galilee in the north and the Naqab (the Negev) in the south, they were effectively isolated islands amidst the surrounding Palestinian countryside.

This isolation meant these colonies were built like military garrisons rather than villages: what inspired their layout and design were security considerations rather than human habitation. Their introverted seclusion contrasted bizarrely with the open spaces of the traditional Palestinian villages with their natural stone houses and their accessible, unhindered, approaches to the nearby fields and the orchards and olive groves around them.

That so few Jews had settled in the Palestinian countryside proved to be a serious problem for those who wanted to base their solution to the growing conflict between the two communities on the principle of partition. On the one hand, logic and common sense dictated that the countryside as a whole – more than three quarters of the territory – should remain Palestinian. The towns, on the other hand, were almost equally inhabited. The question was, how to devise two distinct Palestinian and Jewish entities with homogenous populations when this was the reality on the ground? Partitioning Palestine was originally a British solution, but it became a centrepiece of Zionist policy from 1937. Earlier, the British had put forward several other options, notably the creation of a bi-national state, which the Jews had rejected, and a cantonised Palestine (following the Swiss model), which both sides had refused to consider. In the end, London gave up the attempt to find a solution for the looming conflict and, in February 1947, transferred the question of Palestine to the United Nations. Favoured by the Zionist leadership, and now backed by Britain, partition became the name of the game. The interests of the Palestinians were soon almost totally excised from the process.





## THE UN'S PARTITION PLAN




An inexperienced UN, just two years old in 1947, entrusted the question of the future of Palestine’s fate into the hands of a Special Committee for Palestine, UNSCOP, none of whose members turned out to have any prior experience in solving conflicts or knew much about Palestine’s history.

UNSCOP too decided to sponsor partition as the guiding principle for a future solution. True, its members deliberated for a while over the possibility of making all of Palestine one democratic state – whose future would then be decided by the majority vote of the population – but they eventually abandoned the idea. Instead, UNSCOP recommended to the UN General Assembly to partition Palestine into two states, bound together federation-like by economic unity. It further recommended that the City of Jerusalem would be established as corpus separatum under an international regime administrated by the UN. The report UNSCOP came up with in the end envisaged that the two future states would be identical except for their internal demographic balance, and it therefore stressed the need for both entities to adhere to liberal democratic precepts. On 29 November 1947 this became General Assembly Resolution 181.2

It is clear that by accepting the Partition Resolution, the UN totally ignored the ethnic composition of the country’s population. Had the UN decided to make the territory the Jews had settled on in Palestine correspond with the size of their future state, they would have entitled them to no more than ten per cent of the land. But the UN accepted the nationalist claims the Zionist movement was making for Palestine and, furthermore, sought to compensate the Jews for the Nazi Holocaust in Europe.

As a result, the Zionist movement was ‘given’ a state that stretched over more than half of the country. That the members of UNSCOP veered towards the Zionist point of view was also because the Palestinian leadership had been opposed since 1918 to the partitioning of their land. Throughout its history this leadership, made up mainly of urban notables, quite often failed to truly represent the native population of Palestine; however, this time they got it right and fully backed the popular resentment among Palestine’s society towards the idea of ‘sharing’ their homeland with European settlers who had come to colonise it.

The Arab League, the regional inter-Arab Organisation, and the Arab Higher Committee (the embryonic Palestinian government) decided to boycott the negotiations with UNSCOP prior to the UN resolution, and did not take part in the deliberations on how best to implement it after November 1947. Into this vacuum the Zionist leadership stepped with ease and confidence, quickly setting up a bilateral dialogue with the UN on how to work out a scheme for the future of Palestine. This is a pattern we will see recur frequently in the history of peacemaking in Palestine, especially after the Americans became involved in 1967: up to the present day, ‘bringing peace to Palestine’ has always meant following a concept exclusively worked out between the US and Israel, without any serious consultation with, let alone regard for, the Palestinians.

The Zionist movement so quickly dominated the diplomatic game in 1947 that the leadership of the Jewish community felt confident enough to demand UNSCOP allocate them a state comprising over eighty per cent of the land. The Zionist emissaries to the negotiations with the UN actually produced a map showing the state they wanted, which incorporated all the land Israel would occupy a year later, that is, Mandatory Palestine without the West Bank. However, most of the UNSCOP members felt this was a bit too much, and convinced the Jews to be satisfied with fifty-six per cent of the land. Moreover, Catholic countries persuaded the UN to make Jerusalem an international city given its religious significance, and therefore UNSCOP also rejected the Zionist claim for the Holy City to be part of the future Jewish State.3

Partitioning the country – overwhelmingly Palestinian – into two equal parts has proven so disastrous because it was carried out against the will of the indigenous majority population. By broadcasting its intent to create equal Jewish and Arab political entities in Palestine, the UN violated the basic rights of the Palestinians, and totally ignored the concern for Palestine in the wider Arab world at the very height of the anti-colonialist struggle in the Middle East.

Far worse was the impact the decision had on the country itself and its people. Instead of calming the atmosphere, as it was meant to do, the resolution only heightened tensions and directly caused the country to deteriorate into one of the most violent phases in its history. Already in February 1947, when the British first announced their intention to leave Palestine, the two communities had seemed closer to a total clash than ever before. Although no significant outbursts of violence were reported before the UN adopted its Partition Resolution on 29 November 1947, anxiety was particularly high in the mixed towns. So long as it was unclear which way the UN would go, life continued more or less as normal, but the moment the die was cast and people learned that the UN had voted overwhelmingly in favour of partitioning Palestine, law and order collapsed and a sense of foreboding descended of the final showdown that partition spelled. The chaos that followed produced the first Arab-Israeli war: the ethnic cleansing of the Palestinians had started.





## THE ARAB AND PALESTINIAN POSITIONS




As I explained above, the Palestinian leadership decided from the start to boycott the UN proceedings. This decision features often in contemporary Israeli propaganda as proof that the Palestinians themselves – not Israel – should be held responsible for the fate that befell them in 1948. Palestinian historiography has successfully fended off such accusations by exposing the extent to which the procedures the UN opted to follow were unjust and illegal, and by exploring the raison d’être behind the establishment of UNSCOP. Before we proceed I want to summarise these arguments and examine them in more detail.

By opting for partition as its primary objective, the UN ignored a basic principled objection the Palestinians were voicing against the plan, with which mediators had been familiar since Britain made the Balfour Declaration thirty years earlier. Walid Khalidi succinctly articulated the Palestinian position as follows: ‘The native people of Palestine, like the native people of every other country in the Arab world, Asia, Africa, America and Europe, refused to divide the land with a settler community.’4

Within a few weeks of UNSCOP starting its work, the Palestinians realised the cards had been stacked against them: the final result of this process would be a UN resolution on partitioning the country between the Palestinians, as the indigenous population, and a settler colony of newcomers, many of whom had arrived only recently. When Resolution 181 was adopted in November 1947, their worst nightmare began to unfold in front of their eyes: nine months after the British had announced their decision to leave, the Palestinians were at the mercy of an international organisation that appeared ready to ignore all the rules of international mediation, which its own Charter endorsed, and was willing to declare a solution that in Palestinian eyes was both illegal and immoral. Several leading Palestinians at the time demanded that its legality be tested in the International Court of Justice (founded in 1946), but this was never to happen.5 One does not have to be a great jurist or legal mind to predict how the international court would have ruled on forcing a solution on a country to which the majority of its people were vehemently opposed.

The injustice was as striking then as it appears now, and yet it was hardly commented on at the time by any of the leading Western newspapers then covering Palestine: the Jews, who owned less than six per cent of the total land area of Palestine and constituted no more than one third of the population, were handed more than half of its overall territory. Within the borders of their UN-proposed state, they owned only eleven per cent of the land, and were the minority in every district. In the Negev – admittedly an arid land but still with a considerable rural and Bedouin population, which made up a major chunk of the Jewish state – they constituted one per cent of the total population.

Other aspects that undermined the legal and moral credibility of the resolution quickly emerged. The Partition Resolution incorporated the most fertile land in the proposed Jewish state as well as almost all the Jewish urban and rural space in Palestine. But it also included 400 (out of more than 1000) Palestinian villages within the designated Jewish state. In hindsight, it may be argued in UNSCOP’s defence that Resolution 181 was based on the assumption that the two new political entities would peacefully coexist and therefore not much attention needed to be paid to balances of demography and geography. If this were the case, as some UNSCOP members were to argue later, then they were guilty of totally misreading Zionism and grossly underestimating its ambitions. Again in the words of Walid Khalidi, Resolution 181 was ‘a hasty act of granting half of Palestine to an ideological movement that declared openly already in the 1930s its wish to de-Arabise Palestine.’6 And thus Resolution 181’s most immoral aspect is that it included no mechanism to prevent the ethnic cleansing of Palestine.

Let us look more closely at the final map that the UN proposed in November 1947 (see Map 5). Palestine was actually to be divided into three parts. On forty-two per cent of the land, 818,000 Palestinians were to have a state that included 10,000 Jews, while the state for the Jews was to stretch over almost fifty-six per cent of the land which 499,000 Jews were to share with 438,000 Palestinians. The third part was a small enclave around the city of Jerusalem which was to be internationally governed and whose population of 200,000 was equally divided between Palestinians and Jews.7

The almost equal demographic balance within the allocated Jewish state was such that, had the map actually been implemented, it would have created a political nightmare for the Zionist leadership: Zionism would never have attained any of its principal goals. As Simcha Flapan, one of the first Israeli Jews to challenge the conventional Zionist version of the 1948 events, put it, had the Arabs or the Palestinians decided to go along with the Partition Resolution, the Jewish leadership would have been sure to reject the map UNSCOP offered them.8

Actually, the UN map was an assured recipe for the tragedy that began to unfold the day after Resolution 181 was adopted. As theoreticians of ethnic cleansing acknowledged later, where an ideology of exclusivity is adopted in a highly charged ethnic reality, there can be only one result: ethnic cleansing. By drawing the map as they did, the UN members who voted in favour of the Partition Resolution contributed directly to the crime that was about to take place.





## THE JEWISH REACTION




By 1947, David Ben-Gurion presided over a political structure of decision-making that probably constitutes the only complex aspect of the history related in this book, but this is dealt with in depth elsewhere,9 and is beyond the remit of this book. Briefly, it allowed him to determine almost single-handedly the main policies of the Jewish community vis-à-vis the world, the Arab neighbours and the Palestinians. It was Ben-Gurion who now led his associates simultaneously to accept and ignore the UN Partition Resolution on 29 November 1947.

The categorical rejection of the scheme by the Arab governments and the Palestinian leadership made it undoubtedly easier for Ben-Gurion to believe that he could both accept the plan and work against it. Already in October 1947, before the resolution was adopted, Ben-Gurion clarified to his friends in the leadership that if the map of the partition plan were not satisfactory, the Jewish state would not be obliged to accept it.10

It is clear, therefore, that the rejection or acceptance of the plan by the Palestinians would not have changed Ben-Gurion’s assessment of the plan’s deficiencies where he was concerned. For him and his friends at the top of the Zionist hierarchy, a valid Jewish state meant a state that stretched over most of Palestine and allowed for no more than a tiny number of Palestinians, if any at all, to be included.11 Similarly, Ben-Gurion was unfazed by the resolution’s call that Jerusalem be turned into an international city. He was determined to make the entire city his Jewish capital. That in the end he failed to do so was only because of complications and disagreements arising in the Jordanian-Jewish negotiations over the future of the country and the city, of which more is said later.

As unhappy as he was with the UN map, Ben-Gurion realised that under the circumstances – the total rejection of the map by the Arab world and the Palestinians – the delineation of final borders would remain an open question. What mattered was international recognition of the right of the Jews to have a state of their own in Palestine. An observant British official in Jerusalem wrote to his government that the Zionist acceptance of the partition resolution was selective: the Zionists rejoiced in the international recognition of the Jewish State, but then claimed that the UN had offered ‘non-Zionist conditions for maintaining it’.12

The expected Arab and Palestinian rejection of the plan13 allowed Ben-Gurion and the Zionist leadership to claim that the UN plan was a dead letter the day it was accepted – apart, of course, from the clauses that recognised the legality of the Jewish state in Palestine. Its borders, given the Palestinian and Arab rejection, said Ben-Gurion, ‘will be determined by force and not by the partition resolution.’14 As would be the fate of the Arabs living in it.





## THE CONSULTANCY BEGINS ITS WORK




A formula now emerges. The less important the body Ben-Gurion appeared in front of, the more supportive the leader was of the Partition Resolution; the more significant the forum, the more adamant he proved in his scornful rejection of it. In the special body that advised him on security issues, the Defence Committee, he dismissed the Partition Resolution out of hand, and already on 7 October 1947 – before UN Resolution 181 was even adopted – we find him telling the inner circle of his colleagues in the Consultancy that in the light of the Arab refusal to cooperate with the UN, there ‘are no territorial boundaries for the future Jewish State.’15

In October and November 1947 the Consultancy became Ben-Gurion’s most important reference group. It was only among them that he discussed openly what the implications would be of his decision to disregard the partition map and to use force in order to ensure Jewish majority and exclusivity in the country. In such ‘sensitive’ matters he could confide only in this highly select coterie of politicians and military men.

It was precisely because he understood that these questions could not be aired in public that Ben-Gurion had created the ‘Consultancy’ in the first place. As explained above, this was not an official outfit, and we have no proper minutes from most of their meetings.16 It is doubtful whether notes were taken at all – apart from at one or two very crucial meetings that did get transcribed and to which I will come back later. However, Ben-Gurion recorded summaries of many of the meetings in his diary, an important historical source for those years. Moreover, some of the Consultancy’s members would be interviewed in later years, and others wrote autobiographies and memoirs. In the following pages I take my cues from Ben-Gurion’s diary, archival correspondence and the private archive of Israel Galili, who was present in all the meetings (all sources included in the Ben-Gurion Archives in Sdeh Boker). In addition, an intensive correspondence surrounded these meetings, which can be found in various Israeli archives. The meetings took place partly in Ben-Gurion’s house in Tel-Aviv and partly in the Red House. As on 10 March 1948, some meetings were convened on Wednesdays in the Red House, within the official weekly meeting of the High Command, the Matkal (the formal parts of these meetings are recorded in the IDF archives). Other, more private, consultations took place in Ben-Gurion’s house, a day after the more formal Wednesday meeting. The latter meetings were referred to, very cautiously, in Ben-Gurion’s diary, but can be reconstructed with the help of sources such as Yossef Weitz’s diary, Israel Galili’s archives and the letters of Ben-Gurion to various colleagues, most notable of whom was his second in command, Moshe Sharett (who was abroad for most of this period).17 On 15 May 1948, the meetings moved to a new place east of Tel-Aviv, which became the headquarters of the Israeli Army.

The Consultancy, as we saw, was a combination of security figures and specialists on ‘Arab affairs’, a formula that was to serve as the core for most of the bodies entrusted with advising future governments of Israel throughout the years on issues of state security, strategies and policy planning towards the Arab world in general and the Palestinians in particular.18 This entourage around Ben-Gurion began to hold regular meetings in February 1947, from the moment the British decided to leave Palestine, and more frequently in October 1947, when it transpired that the Palestinians would reject the UN Partition Plan. Once the Palestinian and general Arab positions were clear, the members of the Consultancy knew not only that they were to decide the fate of the Palestinians in the UN-designated Jewish state, but that their policies were also about to affect the Palestinians living in areas the UN had accorded to the Arab state in Palestine. In the next chapter we shall see how the thinking of the Consultancy evolved until it devised a final plan for the dispossession of one million Palestinians, no matter where they happened to be in the country.

The first documented meeting of the Consultancy is that of 18 June 1947, during the regular Wednesday afternoon meeting of the High Command. Ben-Gurion reported the meeting both in his diary and in his published memoirs. He told those present that the Jewish community would need to ‘defend not only our settlements, but the country as a whole and Our National Future’. Later on, in a speech he gave on 3 December 1947, he would repeat the term ‘our national future’ and use it as a code for the demographic balance in the country.19




