---
title: "The Blueprint for Ethnic Cleansing"
subtitle: "Plan Dalet"
---

> The Serbs were interested in creating an ethnically pure Republika Srpska for the Serbs, but large Muslim minorities, especially in the cities, made it difficult for the Serbs to carve out homogenous ethnic entities. As a result, the army of the Republika Srpska under the leadership of General Ratko Mladic began a policy of ‘ethnic cleansing’ against Muslims in what they considered to be Serb lands.

GlobalSecurity.org, 2000–2005

The editors of Ben-Gurion’s diary were surprised to discover that between 1 April and 15 May 1948, the leader of the Jewish community in Palestine seemed rather oblivious to the military side of events.1

Instead, he appeared much more preoccupied with domestic Zionist politics and was dealing intensively with organisational topics such as transforming the Diasporic bodies into organs of the new state of Israel. His diary certainly does not betray any sense of a looming catastrophe or a ‘second Holocaust’, as he proclaimed with pathos in his public appearances.

To his inner circles he spoke a different language. To members of his party Mapai, early in April, he proudly listed the names of the Arab villages Jewish troops had recently occupied. On another occasion, on 6 April, we find him rebuking socialist-leaning members of the Histadrut’s executive who questioned the wisdom of attacking peasants instead of confronting their landlords, the effendis, telling one of its central figures: ‘I do not agree with you that we are facing effendis and not peasants: our enemies are the Arab peasants!’2

His diary does indeed offer a stark contrast to the fear he planted in his audiences during public gatherings and, consequently, the Israeli collective memory. It suggests that by then he had realised Palestine was already in his hands. He was not, however, over-confident and did not join in the celebrations on 15 May 1948, aware of the enormity of the task ahead of him: cleansing Palestine and making sure Arab attempts would not stop the Jewish takeover. Like the Consultancy, he feared the outcome of developments in places where there was an obvious imbalance between isolated Jewish settlements and a potential Arab army – as was the case in remote parts of the Galilee and the Negev, as well as in some parts of Jerusalem. Ben-Gurion and his close associates nonetheless understood perfectly well that these local disadvantages could not change the overall picture: the ability of the Jewish forces to seize, even before the British had left, many of the areas the UN Partition Resolution had allocated to the Jewish state. ‘Seizing’ meaning only one thing: the massive expulsion of the Palestinians living there from their homes, businesses and land in both the cities and the rural areas.

Ben-Gurion may not have publicly rejoiced with the Jewish masses who danced in the streets on the day the British Mandate officially ended, but he was well aware that the power of the Jewish military forces had already begun to show on the ground. When Plan Dalet was put into effect, the Hagana had more than 50,000 troops at its disposal, half of which had been trained by the British army during the Second World War. The time had come to put the plan into effect.





## OPERATION NACHSHON: THE FIRST PLAN DALET OPERATION




The Zionist strategy of building isolated settlements in the midst of densely populated Arab areas, approved retroactively by the British Mandatory authorities, proved a liability at times of tension. Attempts to bring supplies and troops to these faraway posts could not always be guaranteed, and once the country was in flames, the western approach road to Jerusalem, which passed through numerous Palestinian villages, was particularly difficult to safeguard, creating a sense of siege amongst the small Jewish population in the city. The Zionist leaders were also worried about the Jews in Jerusalem, for a different reason: they were made up mainly of Orthodox and Mizrahi communities whose commitment to Zionism and its aspirations was quite tenuous or even questionable. Thus, the first area chosen for putting Plan Dalet into action was the rural hills on the western slopes of the Jerusalem mountains, half way along the road to Tel-Aviv. This was Operation Nachshon, which would serve as a model for future campaigns: the sudden massive expulsions it employed were to prove the most effective means for maintaining isolated Jewish settlements or unblocking routes that were under enemy threat, such as the one leading to Jerusalem.

Every brigade assigned to the operation was asked to prepare to move into Mazav Dalet, State D, that is to ready themselves to implement the orders of Plan D: ‘You will move to State Dalet, for an operative implementation of Plan Dalet,’ was the opening sentence to each unit. And then ‘the villages which you will capture, cleanse or destroy will be decided according to consultation with your advisors on Arab affairs and the intelligence officers.’3 Judging by the end result of this stage, namely April–May 1948, this advice was not to spare a single village. Whereas the official Plan Dalet gave the villages the option to surrender, the operational orders did not exempt any village for any reason. With this the blueprint was converted into military order to begin destroying villages. The dates differed according to the geography: the Alexandroni Brigade, which would storm the coast with its tens of villages, leaving only two behind them, received its orders towards the end of April; the instruction to cleanse the Eastern Galilee arrived at the Golani Brigade headquarters on 6 May 1948, and the next day the first village in their ‘area’, Shajara, was cleansed.4

The Palmach units received their orders for Nachson on the very first day of April 1948. The night before, the Consultancy had met at Ben-Gurion’s house to finalise the directives to the units. Their orders were clear: ‘the principal objective of the operation is the destruction of Arab villages ... [and] the eviction of the villagers so that they would become an economic liability for the general Arab forces.’5

Operation Nachshon was also a novelty in other respects. It was the first operation in which all the various Jewish military organisations endeavoured to act together as a single army – providing the basis for the future Israeli Defence Forces (IDF). And it was the first operation in which the veteran East European Jews, who naturally dominated the military scene, were incorporated into the campaign alongside other ethnic groups such as newcomers the Arab world and from post-Holocaust Europe.

The commander of one battalion who participated in this operation, Uri Ben-Ari, mentioned in his memoirs that ‘melting the Diasporas’ was one of the important goals of Nachshon. Ben-Ari was a young German Jew who had arrived in Palestine a few years earlier. His unit made its final preparations for Nachshon on the Mediterranean coast, near Hadera. He recalled likening himself to Russian generals fighting the Nazis in the Second World War. The ‘Nazis’ in his case were a large number of defenceless Palestinian villages in proximity to the Jaffa–Jerusalem road and the para-military groups of Abd al-Qadir al-Husayni who had come to their rescue. Al-Husayni’s units had been retaliating for earlier Jewish attacks by firing randomly at Jewish traffic on the road, wounding and killing passengers. But the villagers themselves, as elsewhere in Palestine, were trying to continue life as normal, unaware of the demonised image attributed to them by Ben-Ari and his comrades. Within a few days most of them would be expelled forever from the homes and fields where they and their ancestors had lived and worked for centuries. The paramilitary Palestinian groups under the command of Abd al-Qadir al-Husayni put up more resistance than Ben-Ari’s battalion had expected, which meant that the Nachshon operation did not at first go as planned. By 9 April, however, the campaign was over.

This was the day that the first of the many villages around Jerusalem fell into Jewish hands, despite its auspicious name – Qastal (the Castle). It did have ancient fortifications, but these could not protect it from the superior Jewish forces. The Qastal was located on the last western peak before the final ascent to Jerusalem. The monument to the Hagana that Israel has put up at the site fails to mention that there was once on this very spot a Palestinian village. The plaque commemorating the battle is a typical example of how deeply rooted the language of Plan Dalet is in today’s popular Israeli historiography. As in the plan, so on the plaque, the Qastal appears not as a village but as an ‘enemy base’: Palestinian villagers are dehumanised in order to turn them into ‘legitimate targets’ of destruction and expulsion. All over Israel many new settlements and national parks have become part of the country’s collective memory without any reference to the Palestinian villages that once stood there, even where there are vestiges, such as an isolated house or a mosque, which visibly attest to the fact that people used to live there as recently as 1948.

On 9 April, while defending Qastal, Abd al-Qadir al-Husayni was killed in battle. His death so demoralised his troops that all the other villages in the Greater Jerusalem area swiftly fell into the hands of the Jewish forces. One by one, they were surrounded, attacked and occupied, their people expelled and their homes and buildings demolished. In some of them, the expulsion was accompanied by massacres, the most notorious of which is the one Jewish troops perpetrated, on the same day Qastal fell, in Deir Yassin.





### Deir Yassin




The systematic nature of Plan Dalet is manifested in Deir Yassin, a pastoral and cordial village that had reached a non-aggression pact with the Hagana in Jerusalem, but was doomed to be wiped out because it was within the areas designated in Plan Dalet to be cleansed. Because of the prior agreement they had signed with the village, the Hagana decided to send the Irgun and Stern Gang troops, so as to absolve themselves from any official accountability. In the subsequent cleansings of ‘friendly’ villages even this ploy would no longer be deemed necessary.

On 9 April 1948, Jewish forces occupied the village of Deir Yassin. It lay on a hill west of Jerusalem, eight hundred metres above sea level and close to the Jewish neighbourhood of Givat Shaul. The old village school serves today as a mental hospital for the western Jewish neighbourhood that expanded over the destroyed village.

As they burst into the village, the Jewish soldiers sprayed the houses with machine-gun fire, killing many of the inhabitants. The remaining villagers were then gathered in one place and murdered in cold blood, their bodies abused while a number of the women were raped and then killed.6

Fahim Zaydan, who was twelve years old at the time, recalled how he saw his family murdered in front of his eyes:

They took us out one after the other; shot an old man and when one of his daughters cried, she was shot too. Then they called my brother Muhammad, and shot him in front us, and when my mother yelled, bending over him – carrying my little sister Hudra in her hands, still breastfeeding her – they shot her too.7





Zaydan himself was shot, too, while standing in a row of children the Jewish soldiers had lined up against a wall, which they had then sprayed with bullets, ‘just for the fun of it’, before they left. He was lucky to survive his wounds.

Recent research has brought down the accepted number of people massacred at Deir Yassin from 170 to ninety-three. Of course, apart from the victims of the massacre itself, dozens of others were killed in the fighting, and hence were not included in the official list of victims. However, as the Jewish forces regarded any Palestinian village as an enemy military base, the distinction between massacring people and killing them ‘in battle’ was slight. One only has to be told that thirty babies were among the slaughtered in Deir Yassin to understand why the whole ‘quantitative’ exercise – which the Israelis repeated as recently as April 2002 in the massacre in Jenin – is insignificant. At the time, the Jewish leadership proudly announced a high number of victims so as to make Deir Yassin the epicentre of the catastrophe – a warning to all Palestinians that a similar fate awaited them if they refused to abandon their homes and take flight.8

Four nearby villages were next – Qalunya, Saris, Beit Surik and Biddu. Taking only an hour or so in each village, the Hagana units blew up the houses and expelled the people. Interestingly (or ironically, if you wish) Hagana officers claimed they had to struggle with their subordinates in order to prevent a frenzy of looting at the end of each occupation. Ben-Ari, who supervised the sappers unit that blew up the houses, recounts in his memoirs how he had single-handedly stopped the plunder of these villages, but this claim seems exaggerated to say the least, given that the peasants ran away with nothing while their possessions found their way into the living rooms and farms of both soldiers and officers as wartime mementos.9

Two villages in the same area were spared: Abu Ghawsh and Nabi Samuil. This was because their mukhtars had developed a relatively cordial relationship with the local commanders of the Stern Gang. Ironically, this saved them from destruction and expulsion: as the Hagana wanted to demolish them, the more extremist group, the Stern Gang, now came to their rescue. This was, however, a rare exception, and hundreds of villages suffered the same fate as Qalunya and the Qastal.10





## THE URBICIDE OF PALESTINE




The confidence the Jewish command in early April had in their capacity not only to take over, but also to cleanse the areas the UN had granted to the Jewish state, can be gauged from the way, immediately after operation Nachshon, they turned their attention to the major urban centres of Palestine. These were systematically attacked throughout the rest of the month, as UN agents and British officials stood by and watched indifferently.

The offensive against the urban centres began with Tiberias. As soon as news of Deir Yassin and the massacre three days later (12 April) in the nearby village of Khirbat Nasr al-Din reached the large Palestinian population in the city, many fled.11 The people were also petrified by the daily heavy bombardments by the Jewish forces situated in the hills overlooking this historic, ancient capital on the Sea of Galilee, where 6000 Jews and 5000 Arabs and their forbears had for centuries co-existed peacefully. British obstruction meant that the ALA had only managed to supply the city with a force of about thirty volunteers. These were no match for the Hagana forces, who rolled barrel bombs down from the hills and used loudspeakers to broadcast terrifying noises to frighten the population – an early version of the supersonic flights over Beirut in 1983 and Gaza in 2005, which human rights organisations have decried as criminal acts. Tiberias fell on 18 April.12

The British played a questionable role in the attack on Tiberias. At first they offered to protect the Palestinian residents, but soon urged them to negotiate a general evacuation of the town with the Jewish forces. King Abdullah of Jordan was more ‘practical’: he sent thirty trucks to help move women and children. In his memoirs he claimed he was convinced another Deir Yassin was about to occur.13 British officers later professed to having had similar apprehensions, but documents showing heavy British pressure on the community’s leaders to leave do not reveal any great concern about an impending massacre. Some would say that the British thereby prevented Tiberias’ Arab residents from being massacred; others would argue that they collaborated with the expellers. The role of the British is much clearer, and far more negative, in the next chapters of Palestine’s urbicide, when Haifa and Jaffa were occupied.





### The De-Arabisation of Haifa




As mentioned previously, operations in Haifa were retroactively approved and welcomed by the Consultancy, although not necessarily initiated by it. The early terrorization of the city’s Arab population the previous December had prompted many among the Palestinian elite to leave for their residences in Lebanon and Egypt until calm returned to their city. It is hard to estimate how many fell within this category: most historians put the figure at around 15,000 to 20,000.14

On 12 January 1948, a local leader called Farid Sa’ad, the manager of the Arab Bank in Haifa, and a member of the local national committee, telegraphed Dr. Husayn Khalidi, the secretary of the Arab Higher Committee, in despair: ‘It is good the Jews do not know the truth.’15 The ‘truth’ was that the urban elite in Palestine had collapsed after a month of heavy Jewish shelling and aggression. However, the Jews knew exactly what was going on. Indeed, the Consultancy was well aware that the rich and well-to-do had already left in December, that the Arab arms were not arriving, and the Arab governments did little beyond airing their inflammatory war rhetoric in all directions so as to hide their inaction and unwillingness to intervene on behalf of the Palestinians.

The departure of the affluent meant that between 55,000 and 60,000 Palestinians in Haifa were leaderless and, given the relatively small number of armed Arab volunteers in the town, at the mercy of the Jewish forces in April 1948. This was despite the presence of British troops in the city, who were theoretically responsible for the locals’ safety and well-being.

This phase of the Jewish operation around the city was given the ominous name of ‘Scissors’ (Misparayim), indicating both the idea of a pincer movement and of cutting the city off from its Palestinian hinterland. Haifa, like Tiberias, had been allocated in the UN plan to the Jewish state: leaving the only major port in the country in Jewish control was yet another manifestation of the unfair deal the Palestinians were offered in the UN peace proposal. The Jews wanted the port city but without the 75,000 Palestinians who lived there, and in April 1948, they achieved their objective.

As Palestine’s main port, Haifa was also the last station on the trail of the British pull-out. The British had been expected to stay until August, but in February 1948 they decided to bring the date of departure forward to May. Their troops were consequently present in great numbers and they still had the legal and, one could argue, moral authority to impose law and order in the city. Their conduct, as many British politicians were later to admit, forms one of the most shameful chapters in the history of the British Empire in the Middle East.16 The Jewish campaign of terrorization, begun in December, included heavy shelling, sniper fire, rivers of ignited oil and fuel sent down the mountain-side, and detonated barrels of explosives, and went on for the first months of 1948, but it intensified in early April. On 18 April, the day the Palestinians of Tiberias were put to flight, Major General Hugh Stockwell, the British commander of the Northern Sector seated in Haifa, summoned the Jewish authorities in the city to his office and informed them that in two days the British forces would be removed from locations in which they had been serving as a buffer zone between the two communities. This ‘buffer’ was the only obstacle preventing Jewish forces from a direct assault on, and takeover of, the Palestinian areas, where more than 50,000 people still resided. The road was wide open for the de-Arabisation of Haifa.

This task was given to the Carmeli Brigade, one of the top units of the Jewish army (there were brigades of ‘lesser quality’ such as Qiryati, made up of Arab Jews who were sent only on looting or less attractive ‘missions’; the definition of Qiryati as possessing a ‘lesser human quality’ can be found in the Israeli documents).17 The 2000 Carmeli Brigade troops faced a poorly equipped army of 500 local and mainly Lebanese volunteers, who had inferior arms and limited ammunition, and certainly nothing to match the armoured cars and mortars on the Jewish side.

The removal of the British barrier meant Operation Scissors could be replaced by Operation ‘Cleansing the Leaven’ (bi‘ur hametz). The Hebrew term stands for total cleansing and refers to the Jewish religious practice of eliminating all traces of bread or flour from people’s homes on the eve of the Passover, since as these are forbidden during the days of the feast. Brutally appropriate, the cleansing of Haifa, in which the Palestinians were the bread and the flour, began on Passover’s eve, 21 April.

Stockwell, the British commander, knew in advance about the impending Jewish attack, and earlier that same day invited the ‘Palestinian leadership’ in the city for a consultation. He met with a group of four exhausted men, who became the Arab community’s leaders for the hour, as none of the positions they held officially prepared them for the crucial historic moment that unfolded in Stockwell’s office on that morning. Previous correspondence between them and Stockwell shows they trusted him as the keeper of law and order in the city. The British officer now advised them that it would be better for their people to leave the city, where they and most of their families had lived and worked ever since the mid-eighteenth century, when Haifa came to prominence as a modern town. Gradually, as they listened to Stockwell and their confidence in him faded, they realised that they would be unable to safeguard their community, and so they prepared for the worst: as the British would not protect them, they were doomed to be expelled. They told Stockwell they wanted to leave in an organised manner. The Carmeli Brigade made sure they would leave in the midst of carnage and havoc.18

On their way to meet the British commander, the four men could already hear the Jewish loudspeakers urging the Palestinian women and children to leave before it was too late. In other parts of the town, loudspeakers delivered a diametrically opposing message from the town’s Jewish mayor, Shabtai Levi, a decent person by all accounts, who beseeched the people to stay and promised no harm would befall them. But it was Mordechai Maklef, the operation officer of the Carmeli Brigade, not Levi who called the shots. Maklef orchestrated the cleansing campaign, and the orders he issued to his troops were plain and simple: ‘Kill any Arab you encounter; torch all inflammable objects and force doors open with explosives.’ (He later became the Israeli army Chief of Staff.)19

When these orders were executed promptly within the 1.5 square kilometres where thousands of Haifa’s defenceless Palestinians were still residing, the shock and terror were such that, without packing any of their belongings or even knowing what they were doing, people began leaving en masse. In panic they headed towards the port where they hoped to find a ship or a boat to take them away from the city. As soon as they had fled, Jewish troops broke into and looted their houses.

When Golda Meir, one of the senior Zionist leaders, visited Haifa a few days later, she at first found it hard to suppress a feeling of horror when she entered homes where cooked food still stood on the tables, children had left toys and books on the floor, and life appeared to have frozen in an instant. Meir had come to Palestine from the US, where her family had fled in the wake of pogroms in Russia, and the sights she witnessed that day reminded her of the worst stories her family had told her about the Russian brutality against Jews decades earlier.20 But this apparently left no lasting mark on her or her associates’ determination to continue with the ethnic cleansing of Palestine.

In the early hours of dawn on 22 April, the people began streaming to the harbour. As the streets in that part of the city were already overcrowded with people seeking escape, the Arab community’s self-appointed leadership tried to instil some order into the chaotic scene. Loudspeakers could be heard, urging people to gather in the old marketplace next to the port, and seek shelter there until an orderly evacuation by sea could be organised. ‘The Jews have occupied Stanton road and are on their way’, the loudspeakers blared.

The Carmeli Brigade’s war book, chronicling its actions in the war, shows little compunction about what followed thereafter. The brigade’s officers, aware that people had been advised to gather near the port’s gate, ordered their men to station three-inch mortars on the mountain slopes overlooking the market and the port – where the Rothschild Hospital stands today – and to bombard the gathering crowds below. The plan was to make sure people would have no second thoughts, and to guarantee that the flight would be in one direction only. Once the Palestinians were gathered in the marketplace – an architectural gem that dated back to the Ottoman period, covered with white arched canopies, but destroyed beyond recognition after the creation of the State of Israel – they were an easy target for the Jewish marksmen.21

Haifa’s market was less than one hundred yards from what was then the main gate to the port. When the shelling began, this was the natural destination for the panic-stricken Palestinians. The crowd now broke into the port, pushing aside the policemen who guarded the gate. Scores of people stormed the boats that were moored there, and began to flee the city. We can learn what happened next from the horrifying recollections of some of the survivors, published recently. Here is one of them:

Men stepped on their friends and women on their own children. The boats in the port were soon filled with living cargo. The overcrowding in them was horrible. Many turned over and sank with all their passengers.22





The scenes were so horrendous that when reports reached London, they spurred the British government into action as some officials, probably for the first time, began to realise the enormity of the disaster their inaction was creating in Palestine. The British foreign secretary, Ernest Bevin, was furious with Stockwell’s behaviour, but Field-Marshal Montgomery, the chief of the imperial staff and thus Stockwell’s boss, defended him.23 The last communication between Haifa’s Palestinian leaders and Stockwell took the form of a letter that speaks volumes:

We feel distressed and profoundly aggrieved by the lack of sympathy on the part of the British Authorities to render aid to the wounded although they have been requested to do so.24





### Safad is Next [25]




By the time Haifa fell, only a few towns in Palestine were still free, among them Acre, Nazareth and Safad. The battle over Safad began in the middle of April and lasted until 1 May. This was not due to any stubborn resistance from the Palestinians or the ALA volunteers, although they did make a more serious effort here than elsewhere. Rather, tactical considerations directed the Jewish campaign first to the rural hinterland around Safad, and only then did they move on the town itself.

In Safad there were 9500 Arabs and 2400 Jews. Most of the Jews were Ultra-Orthodox and had no interest at all in Zionism, let alone in fighting their Arab neighbours. This, and the relatively gradual way the Jewish takeover developed, may have given the eleven members of the local national committee the illusion that they would fare better than other urban centres. The committee was a fairly representative body that included the town’s notables, ulama (religious dignitaries), merchants, landowners and ex-activists from the 1936 Revolt, of which Safad had been a major centre.26 The false sense of security was reinforced by the relatively large presence of Arab volunteers in Safad, totaling more than 400, although only half of them were armed with rifles. Skirmishes in the town had begun in early January, triggered by an aggressive reconnaissance incursion by some Hagana members into the Palestinian neighbourhoods and market. A charismatic Syrian officer, Ihasn Qam Ulmaz, held the defences against repeated attacks by the Hagana’s commando unit, the Palmach.

At first, these Palmach attacks were sporadic and ineffective, as its units focused their actions on the rural area around the town. But once they were through with the villages in Safad’s vicinity (described later in this chapter) they could concentrate fully on the town itself, on 29 April 1948. Unfortunately for the people of Safad, at precisely the moment they needed him most, they lost the able Ulmaz. The volunteers army’s new commander in the Galilee, Adib Shishakly (to become one of Syria’s rulers in the 1950s) replaced him with one of the ALA’s more incompetent officers. However, it is doubtful whether even Ulmaz would have fared better in view of the imbalance of power: 1000 well-trained Palmach troops confronting 400 Arab volunteers, one of many local imbalances that show the falsity of the myth of a Jewish David facing an Arab Goliath in 1948.27

The Palmach troops drove most of the people out, only allowing 100 old people to stay on, though not for long. On 5 June, Ben-Gurion noted dryly in his dairy: ‘Abraham Hanuki, from [Kibbutz] Ayelet Hashahar, told me that since there were only 100 old people left in Safad they were expelled to Lebanon.’28





### The Phantom City of Jerusalem




The urbicide did not skip Jerusalem, which quickly changed from the ‘Eternal City’, as a recent book by Salim Tamari puts it, into a ‘Phantom City’.29 Jewish troops shelled, attacked and occupied the western Arab neighbourhoods in April 1948. Some of the richer Palestinian inhabitants of these more affluent sections had left town a few weeks before. The rest were expelled from houses that still testify to the architectural beauty of the neighbourhoods the Palestinian elite had started building outside the walls of the Old City by the end of the nineteenth century. In recent years some of these masterpieces have begun to disappear: real estate fervour, architectural eccentricism and constructors’ greed have combined to transform these elegant residential areas into streets of monstrous villas and extravagant palaces for rich American Jews who tend to flock to the city in their old age.

The British troops were still in Palestine when these areas were cleansed and occupied, but they remained aloof and did not intervene. Only in one area, Shaykh Jarrah – the first Palestinian neighborhood built outside the Old City’s walls, where the leading notable families such as the Husaynis, the Nashashibis and the Khalidis had their domicile – did a local British commander decide to step in.

The instruction to the Jewish forces was very clear in April 1948. ‘Occupy the neighbourhood and destroy all its houses.’30 The cleansing attack began on 24 April 1948 but was halted by the British before it could be fully implemented. We have vital testimony of what happened in Shaykh Jarrah from the secretary of the Arab Higher Committee, Dr Husayn Khalidi, who lived there: his desperate telegrams to the Mufti were often intercepted by the Israeli intelligence and are kept in the Israeli archives.31 Khalidi reports how the British commander’s troops saved the neighbourhood, with the exception of the 20 houses the Hagana succeeded in blowing up. This confrontational British stance here indicates how very different the fate of many Palestinians would have been had British troops elsewhere intervened, as both the imperatives of the Mandatory charter and the terms of the UN partition resolution required them to do.

British inaction was the rule, however, as Khalidi’s frantic appeals highlight as regards the rest of the Jerusalemite neighbourhoods, especially in the western part of the city. These areas had come under repeated shelling from the first day of January and here, unlike in Shaykh Jarrah, the British played a truly diabolical role, as they disarmed the few Palestinian residents who had weapons, promising to protect the people against Jewish attacks, but then instantly reneged on that promise.

In one of his telegraphs in early January, Dr Khalidi reported to Al-Hajj Amin, in Cairo, how almost every day a crowd of angry citizens would demonstrate in front of his house seeking leadership and calling for help. Doctors in the crowd told Khalidi that the hospitals were overcrowded with the injured and that they were running out of shrouds to cover the dead bodies. There was total anarchy and people were in a state of panic.

But worse was to come.32 A few days after the aborted attack on Shaykh Jarrah, with the help of the same three-inch mortar bombs used in Haifa, Palestinian Northern and Western Jerusalem were hammered by endless shelling. Only Shu’fat held on and refused to surrender. Qatamon fell in the last days of April. Itzhak Levy, the head of the Hagana intelligence in Jerusalem, recalls: ‘While the cleansing of Qatamon went on, pillage and robbery began. Soldiers and citizens took part in it. They broke into the houses and took from them furniture, clothing, electric equipment and food.’33

The entry of the Jordanian Arab Legion into the fighting changed the picture, and the cleansing operations were halted in the middle of May 1948. Some Jordanians were involved in the fighting before, as volunteers, and their contribution had helped slow down the Jewish advance, especially during the takeover of Qatamon, which involved intensive fighting with Jewish troops in the monastery of San Simon. But despite their heroic – in the description of Levy and his friends – attempt to defend the Palestinian neighbourhoods of the west, they failed. All in all, eight Palestinian neighbourhoods and thirty-nine villages were ethnically cleansed in the Greater Jerusalem area, their population transferred to the eastern part of the city. The villages are all gone today, but some of Jerusalem’s most beautiful houses are still standing, now inhabited by Jewish families who took them over immediately after their eviction – silent reminders of the tragic fate of the people who used to own them.





### Acre and Baysan




The urbicide continued into May with the occupation of Acre on the coast and Baysan in the east on 6 May 1948. In the beginning of May, Acre proved once again that it was not only Napoleon who found it hard to defeat it: despite severe overcrowding due to the huge influx of refugees from the neighbouring city of Haifa, heavy daily shelling by the Jewish forces failed to subdue the Crusader city. However, its exposed water supply ten kilometres to the north, from the Kabri springs, via an almost 200-year old aqueduct, proved its Achilles’ heel. During the siege typhoid germs were apparently injected into the water. Local emissaries of the International Red Cross reported this to their headquarters and left very little room for guessing whom they suspected: the Hagana. The Red Cross reports describe a sudden typhoid epidemic and, even with their guarded language, point to outside poisoning as the sole explanation for this outbreak.34

On 6 May 1948, in Acre’s Lebanese hospital, which belonged to the Red Cross, an emergency meeting was convened. Brigadier Beveridge, chief of the British medical services, Colonel Bonnet of the British army, Dr Maclean of the Medical Services, and Mr de Meuron, the Red Cross delegate in Palestine, met with city officials to discuss the seventy casualties the epidemic had already claimed. They concluded that the infection was undoubtedly water-borne, not due to crowded or unhygienic conditions, as the Hagana claimed. Tellingly, it had affected fifty-five British soldiers who were transferred to Port Said hospital in Egypt. ‘Nothing like that ever happened in Palestine,’ Brigadier Beveridge told de Meuron. The minute they had identified the aqueduct as the source, they switched to artesian wells and water from the agricultural station north of Acre. The refugees from Acre already in camps in the north were also examined in order to prevent the epidemic from spreading.

With their morale weakened by both the typhoid epidemic and the intensive shelling, residents heeded the call from loudspeakers that shouted at them: ‘Surrender or commit suicide. We will destroy you to the last man.’35 Lieutenant Petite, a French UN observer, reported that after the city fell into Jewish hands, there was widespread and systematic looting by the army, including furniture, clothes, and anything that might be useful to the new Jewish immigrants, and the removal of which might discourage the refugees’ return.

A similar attempt to poison the water supply in Gaza on 27 May was foiled. The Egyptians caught two Jews, David Horin and David Mizrachi, trying to inject typhoid and dysentery viruses into Gaza’s wells. General Yadin reported the incident to Ben-Gurion, then Israel’s Prime Minister, who duly entered it in his diary, without comment. The two were later executed by the Egyptians without any official Israeli protestations.36

Ernest David Bergman, together with the Katzir brothers mentioned earlier, was part of a team working on Israel’s biological warfare capability set up by Ben-Gurion in the 1940s, euphemistically called the Science Corps of the Hagana. Ephraim Katzir was appointed its director in May 1948, when the outfit was renamed ‘HEMED’ (Sweetness, the acronym of Hayl Mada – the Science corps). It did not contribute in any major way to the 1948 campaigns but its early input was indicative of the unconventional aspirations the state of Israel would pursue in the future.37

Roughly at the same time that Acre was occupied, the Golani Brigade seized the town of Baysan in Operation Gideon. As in Safad, after occupying several villages in the vicinity, they moved in on the town. The Jewish forces, with the successful takeovers of Haifa, Tiberias and Safad behind them, were confident and highly effective. Experienced now in mass evictions, they tried to force a swift departure in Baysan by issuing an ultimatum to the people to leave their homes within ten hours. The ultimatum was delivered to the ‘city notables’, namely a fraction of the local national committee. These notables declined and hastily tried to accumulate food stocks for a long siege; they organised some weapons, mainly two cannons brought in by volunteers, in order to repel the impending assault. Nahum Spigel, the commander of the Golani Brigade, wanted a swift offensive and to take a number of prisoners of war in order to exchange them for some Jewish prisoners the Jordanian forces had captured earlier in their successful bid for both the Jewish quarter in the Old City and the Zionist settlement of Gush Etzion. In fact, the Legion rescued the Gush Etzion settlers from the hands of angry Palestinian paramilitary groups that had attacked the isolated Jewish colony and the convoy that had come to save it.38 (Today, Gush Etzion is a large Jewish settlement in the West Bank.) These settlers, together with the residents of the old Jewish quarter, were among the few Jewish POWs captured during the war. They were treated fairly and released soon after, unlike the thousands of Palestinians who were now, according to international law, citizens of the State of Israel, but on becoming prisoners were caged in pens.

After heavy daily bombardments, including from the air, the local committee in Baysan decided to surrender. The body that took the decision consisted of the qadi, the local priest, the municipal secretary and the richest merchant in town. They met Palti Sela and his colleagues to discuss the terms of surrender (before the meeting, the members asked permission to travel to Nablus to discuss capitulation, but this was refused). On 11 May, the town passed into Jewish hands. Palti Sela remembered particularly the two pathetic old artillery guns that had been meant to protect Baysan: two French anti-air cannon from the First World War, antiquated weaponry representative of the overall level of the arms the Palestinians and the volunteers possessed, on the eve of the regular Arab armies’ entrance into Palestine.

Immediately after, Palti Sela and his colleagues were able to oversee the ‘orderly expulsion’ of the town’s people. Some were transferred to Nazareth – still a free Palestinian city in May, but not for much longer – some to Jenin, but the majority were driven across the nearby Jordan River onto the opposite bank.39 Eyewitnesses remember the hordes of people from Baysan as particularly panic-stricken and cowed, hurriedly making their way in the direction of the Jordan River and from there inland to makeshift camps. While the Jewish troops were busy with other operations nearby, however, quite a few of them succeeded in returning; Baysan is very close to both the West Bank and the River Jordan and therefore slipping back unnoticed was relatively easy. They succeeded in staying on until mid-June when the Israeli army loaded the people at gunpoint onto trucks and drove them across the river once again.





### The Ruination of Jaffa




Jaffa was the last city to be taken, on 13 May, two days before the end of the Mandate. Like so many of Palestine’s cities, it had a long history going back as far as the Bronze age, with an impressive Roman and Byzantine heritage. It was the Muslim commander, Umar Ibn al-‘Aas, who took the town in 632 and imbued it with its Arab character. The Greater Jaffa area included twenty-four villages and seventeen mosques; today one mosque survives, but not one of the villages is left standing.

On 13 May, 5000 Irgun and Hagana troops attacked the city as Arab volunteers headed by Michael al-Issa, a local Christian, tried to defend it. Among them was an extraordinary unit of fifty Muslims from Bosnia as well as members of the second generation of the Templars, German colonists who had come in the mid-nineteenth century as religious missionaries and now decided to try and defend their colonies (other Templars in the Galilee surrendered without a fight, and were swiftly driven out of their two pretty colonies, Waldheim and Beit Lehem, west of Nazareth).

All in all, Jaffa enjoyed the largest defense force available to the Palestinians in any given locality: a total of 1500 volunteers confronted the 5000 Jewish troops. They survived a three-week siege and attack that began in the middle of April and ended in the middle of May. When Jaffa fell, its entire population of 50,000 was expelled with the ‘help’ of British mediation, meaning that their flight was less chaotic than in Haifa. Still, there were scenes reminiscent of the horrors that took place in the northern harbour of Haifa: people were literally pushed into the sea when the crowds tried to board the far-too-small fishing boats that would take them to Gaza, while Jewish troops shot over their heads to hasten their expulsion.

With the fall of Jaffa, the occupying Jewish forces had emptied and depopulated all the major cities and towns of Palestine. The vast majority of their inhabitants – of all classes, denominations and occupations – never saw their cities again, while the more politicised among them would come to play a formative role in the re-emergence of the Palestinian national movement in the form of the PLO, demanding first and foremost their right to return.





## THE CLEANSING CONTINUES




Already towards the end of March the Jewish operations had destroyed much of the rural hinterland of Jaffa and Tel-Aviv. There was an apparent division of labour between the Hagana forces and the Irgun. While the Hagana moved in an orderly fashion from one place to the next according to plan, the Irgun was allowed sporadic actions in villages beyond the scope of the original list. This is how the Irgun arrived in the village of Shaykh Muwannis (or Munis, as it is known today) on 30 March and expelled its inhabitants by force. Today you will find the elegant campus of Tel-Aviv University sprawling over the ruins of this village, while one of the village’s few remaining houses has become the university’s faculty club.40

Had there not been the tacit understanding between the Hagana and the Irgun, Shaykh Muwannis might have been saved. The heads of the village had made a serious effort to cultivate a cordial relationship with the Hagana in order to prevent their expulsion, but the ‘Arabists’ who had concluded the treaty were nowhere to be found on the day the Irgun showed up and expelled the entire village.41

In April the operations in the countryside were more closely connected to the urbicide. Villages near urban centres were taken and expelled, and sometimes subjected to massacres, in a campaign of terror designed to prepare the ground for a more successful takeover of the cities.

The Consultancy met again on a Wednesday, 7 April 1948. It was decided to destroy, and expel the inhabitants from, all the villages on the Tel-Aviv–Haifa road, Jenin–Haifa road and the Jerusalam–Jaffa road. At the end of the day, apart from a tiny handful of villages, no one was spared.42

Thus, on the day the Irgun wiped out Shaykh Muwannis, the Hagana occupied six villages in the same area within a week: Khirbat Azzun was the first, on 2 April, followed by Khirbat Lid, Arab al-Fuqara, Arab al-Nufay’at and Damira, all cleansed by 10 April, and Cherqis on the 15th. By the end of the month another three villages in the vicinity of Jaffa and Tel-Aviv – Khirbat al-Manshiyya, Biyar ‘Adas and the large village of Miska – had all been taken and destroyed.43

All of this took place before a single regular Arab soldier had entered Palestine, and the pace now becomes hard to follow, for contemporary as well as for later historians. Between 30 March and 15 May, 200 villages were occupied and their inhabitants expelled. This is a fact that must be repeated, as it undermines the Israeli myth that the ‘Arabs’ ran away once the ‘Arab invasion’ began. Almost half of the Arab villages had already been attacked by the time the Arab governments eventually and, as we know, reluctantly decided to send in their troops. Another ninety villages would be wiped out between 15 May and 11 June 1948, when the first of two truces finally came into effect.44

Eyewitnesses on the Jewish side recall clearly thinking throughout April that the army could strive for more. In his recent interview with official historians, Palti Sela, whose testimony can be found in the Hagana Archives in Tel-Aviv, used colourful language to reconstruct that atmosphere of extra zeal. Palti Sela was a member of the Jewish forces that occupied and cleansed the town of Baysan, and who were ordered to push out the large Bedouin tribes that had for centuries seasonally resided in the area. He later remarked:

After we cleansed the area from the Bedouin tribes the pus [he used the Yiddish word for a purulent wound: farunkel] of the Baysan are still infected with two villages, Faruna and Samariyya. They did not seem to be afraid and were still cultivating their fields and continued using the roads.45





One of the many villages captured during these attacks in the east was that of Sirin. Its story epitomises the fate that befell scores of villages depopulated by Jewish forces in Marj Ibn Amir and the Baysan Valley, where today one searches in vain for any trace of the Palestinian life that once flourished there.





### The Village of Sirin




Sirin was occupied on 12 May 1948. It lay near Baysan on one of the Jiftiliq’s lands: historically these lands, at times referred to as ‘mudawar’ lands, were nominally under the Ottoman Sultan’s title but were cultivated by Palestinian farmers. Sirin grew into a thriving community around the burial place (maqam) of a Muslim holy man named Shaykh Ibn Sirin. The terrain in that part of Palestine is tough and the summers are unbearably hot. And yet the habitation that developed around the maqam and the nearby springs, three kilomotres away, resembled that of villages endowed with a much better climate and an endless flow of fresh water. Animals carried the water from the wells and diligent farmers used it to turn the rugged land into a small Garden of Eden. Sirin was an isolated community as it was unreachable by car, but outsiders who did frequent the village single out the particular style of the buildings there: Sirin’s houses were made of volcanic black stones mixed with clay, and the roofs were covered with intertwined layers of wood and bamboo.

Sirin was noted as a fine example of the collective system of land-sharing to which the villagers adhered, dating back to the Ottoman period, and here had survived both the capitalization of the local agriculture and the Zionist drive for land. It boasted three rich bustans (gardens with fruit trees) and olive groves, which spread out over 9000 cultivated dunam of land (out of 17,000). The land belonged to the village as a whole and the size of the family determined its share in the crops and territory.

Sirin was also a village that had all the right connections. The main family, the Zu’bi, had been promised immunity by the Jewish Agency because they belonged to a collaborative clan. Mubarak al-Haj al-Zu’bi, the mukhtar, a young well-educated man, with close connections to the opposition parties, was a friend of the Jewish mayor of Haifa, Shabtai Levi, from the time they had both worked in Baron Rothschild’s company. He was sure his 700 villagers would be exempt from the fate of the nearby villages. But there was another clan in the village, the hamulla of Abu al-Hija, who were more loyal to the ex-Mufti, al-Hajj Amin al-Husayni, and his national party. According to the 1943 Hagana village file on Sirin, it was the presence of this clan that doomed the village. The file noted that in Sirin ten members of the Abu al-Hija had participated in the 1936 Revolt and that ‘none of them was arrested or killed and kept their ten rifles’.

The village suffered from time to time from the animosity between the two main hamullas, but, as everywhere in Palestine, matters improved after the Great Revolt, and by the end of the Mandate the village had put behind it the rift that tore it apart during the rebellious days of the 1930s.

Sirin’s mukhtar hoped that the village’s immunity would be further ensured by the presence of a small Christian clan that had an excellent relationship with the rest of the people. One of them was the village teacher who, in his class of 40 children, educated the next generation without any prejudice to politics or clannish affiliations. His best friend was Shaykh Muhammad al-Mustafa, the imam in the local mosque and the guardian of the Christian church and monastery that were also located inside the village.

Within a few short hours, this microcosm of religious coexistence and harmony was laid waste. The villagers did not put up a fight. The Jewish troops gathered the Muslims – of both clans – and Christians together and ordered them to start crossing the River Jordan to the other side. They then demolished the mosque, the church and the monastery, together with all the houses. Soon, all the trees in the bustans had withered away and died.

Today, a cactus hedge surrounds the rubble that was Sirin. Jews never succeeded in repeating the success of the Palestinians in holding on to the tough soil in the valley, but the springs in the vicinity are still there – an eerie sight as they serve no one.46





### The ALA in Marj Ibn Amir




West of Sirin, in the Marj Ibn Amir (Izrael Valley), Fawzi al-Qawqji did what he could to limit the Jewish takeover, and carried out a few abortive attacks on the main Jewish kibbutz in the area, Mishmar Ha-Emek. In one of the bombardments of the kibbutz by the one cannon he had available, a direct hit killed three children. This awful tragedy is the only hostile event you will find mentioned in official Israeli history books as having taken place in this area.

The villages nearby did not contribute much to the ALA’s efforts to bring good news back from the front to the Arab League that had sent them. In fact, many of them had signed non-aggression pacts with the kibbutzim in their vicinity. But as the ALA attack on Mishmar Ha-Emek fuelled the vengeful rage of the kibbutzniks, these villages were no longer immune from the growing aggression in the valley. The kibbutzniks urged the troops to continue the ethnic cleansing they had started to the east of the area. Many of the kibbutzim in this part of the Galilee belonged to the Zionist socialist party, Hashomer Ha-Tza‘ir, some of whose members tried to adopt a more humane position. In July, some prominent Mapam members complained to Ben-Gurion about what they saw as an ‘unnecessary’ expansion of the cleansing operation. Ben-Gurion was quick to remind these conscientious kibbutzniks that they themselves had been glad to see the first phase initiated in the area back in April.47 Indeed, if you were a Zionist Jew in 1948, this meant one thing and one thing only: full commitment to the de-Arabisation of Palestine.

Al-Qawqji’s attack on Kibbutz Mishmar Ha-Emek on 4 April was in direct response to the Jewish mass expulsions that had started around 15 March. The first villages to go on that day had been Ghubayya al-Tahta and Ghubayya al-Fawqa, each with more than 1000 inhabitants. Later the same day it was the turn of the smaller village of Khirbat al-Ras. Occupation here, too, carried the by now familiar features of ethnic cleansing: expulsion of the people and destruction of their houses.

After the Mishmar Ha-Emek incident it was the turn of even larger villages: Abu Shusha, Kafrayn, Abu Zurayq, Mansi, and Naghnaghiyya (pronounced Narnariya): the roads east to Jenin soon filled with thousands of Palestinians whom the Jewish troops had expelled and sent walking, not far from where the bastion of Zionist socialism had its kibbutzim. The smaller village of Wadi Ara, with 250 people, was the last to be wiped out in April.48

Here, too, the Irgun contributed its share of the continued destruction of Palestine’s countryside. They completed the vengeful attack on the remaining villages in Marj Ibn Amir, while the British Mandate troops were still there: Sabbarin, Sindiyana, Barieka, Khubbeiza and Umm al-Shauf. Some of the people in these villages fled under the heavy mortar fire of the attacking forces, while others who waved white flags signaling surrender were instantly exiled. In Sabbarin, the Irgun bandits, angered by the fact that they encountered some armed resistance, as punishment kept the women, old men and children confined for a few days within barbed wire – very much like the cages in which Palestinians today are kept for hours at checkpoints in the West Bank when they fail to present the right permits. Seven young Palestinian men found carrying arms were executed on the spot by Jewish troops, who then expelled the rest of the villagers to Umm al-Fahm, then not yet in Jewish hands.49

Each phase or operation in the various geographical locations produced new patterns of behaviour that were later adopted by the rest of the troops. A few days after the village of Kafrayn had been occupied and its people expelled, the army practised its skills on the now empty village, wiping it off the face of the earth.50 This type of manoeuvre was used again and again, long after the war of 1948 had ended, well into the 1950s.

The operation in Safad’s hinterland was already motivated less by rage than by efficient planning, and had been given the ominous codename of ‘Broom’ (matateh). It began with the cleansing of the villages along the Tiberias–Safad highway. The first village to go was Ghuwayr. After Tiberias fell, the mukhtar immediately realised what was in store for his village, as it was the nearest to the city. He asked Adib Shishakly, the head of the ALA volunteers, to help, and suggested distributing arms to the villagers, but Shishakly refused. The news demoralised the villagers, and women and children began fleeing to Rama on the road to Acre on the other side of the Galilee mountains. The mukhtar proceeded to recruit fifty peasants who, armed with their hartooush (old hunting guns from the First World War) awaited the Jewish assault. On 22 April, the Jews, as was to become their custom, first sent a delegation proposing a collective evacuation of the men without fighting. In this case, however, the delegation was unusual: it was made up of people who in the past had maintained friendly ties with the village, and the Palestinians who were present at the meeting later recalled their apologetic tone when they explained that all the villages on the road between Tiberias and Safad were scheduled to be expelled. The mukhtar did not reveal the fact that the village was almost deserted and avowed that the people ‘will defend their homes’.51

After the swift occupation of the village, another pattern emerged. A Jewish soldier went out on the roof of one of the houses and inquired whether among the men captured there were any Druze. ‘If so’, he shouted, ‘they can stay. The rest have to go to Lebanon.’ But even that option was not open to all, as the occupying force decided to conduct a selection process before ‘allowing’ the villagers to leave for Lebanon. Such selection operations were to become the model for the following expulsions, and one that has remained deeply engraved in the collective memory of Palestinians from the Nakba years, haunting them to this very day. Young men between the age of ten and thirty were taken aside and sent to prison camps. Forty men of Ghuwayr were thus separated from their families for eighteen months, languishing in pens.

The village of Ghuwayr was frequently visited by UN observers checking first-hand how the partition resolution was being implemented. They witnessed the expulsions. Representatives of the western media, including a New York Times reporter, were still filing stories about individual villages, although the public interest in their fate was by this time diminishing; in any case, western readers were never given the full picture of events.52 Furthermore, it seems that none of the foreign correspondents dared openly to criticise the actions of the Jewish nation just three years after the Holocaust.

It was in and around Haifa that the ethnic cleansing operation gathered momentum, its deadly pace heralding the destruction to come. Fifteen villages – some of them small, that is with less than 300 people, some of them huge, with around 5000 – were expelled in quick succession. Abu Shusha, Abu Zurayq, Arab al-Fuqara, Arab al-Nufay‘at, Arab Zahrat al-Dumayri, Balad Al-Shaykh, Damun, Khirbat al-Kasayir, Khirbat al-Manshiyya, Rihaniyya, Khirbat al-Sarkas, Khirbat Sa‘sa, Wa‘rat al-Sarris and Yajur were wiped off Palestine’s map within a sub-district full of British soldiers, UN emissaries and foreign reporters.

Expulsion and flight were not enough to save the villagers. Many of them were hunted down by the Marxist kibbutzniks of Hashomer Ha-Tza‘ir, who swiftly and efficiently looted their houses before detonating them. We have records of the verbal condemnation by concerned Zionist politicians from this period – which provided ‘new historians’ in Israel with material on the atrocities they had not encountered in other archival sources.53 Today, these documents of complaint read more as an attempt by ‘sensitive’ Jewish politicians and soldiers to absolve their consciences. They form part of an Israeli ethos that can best be described as ‘shoot and cry’, the title of a collection of expressions of supposedly moral remorse by Israeli soldiers who had participated in a small-scale ethnic cleansing operation in the June 1967 war. These concerned soldiers and officers were then invited by the popular Israeli writer Amoz Oz and his friends to perform a ‘rite of exoneration’ in the Red House before it was demolished. Back in 1948, three years after the Holocaust, similar remonstrations served to ease the troubled consciences of Jewish soldiers involved in atrocities and war crimes against a largely defenseless civilian population.

Crying aloud while killing and expelling innocent people was one tactic for dealing with the moral implications of Plan D. The other one was dehumanizing the Palestinians who, as the Jewish Agency had promised the UN, were to become full citizens of the State of Israel. Instead, they were expelled, imprisoned or killed: ‘Our army marches forward and conquers Arab villages and their inhabitants flee like mice,’ wrote Yossef Weitz.54

The spectrum of military activity was still quite wide in April. Unlike in later months when vast areas were to be cleansed, in April some villages were still left intact; other villagers suffered a worse fate than expulsion and were subjected to massacres. The military orders reflected this spectrum when they distinguished between two kinds of action to be taken against Palestinian villages: cleansing (le-taher) and harassing (le-hatrid). Harassment was never specified. It consisted of the random shelling of cities, towns and villages and hit-or-miss fire on civilian traffic.55 On 14 April, Ben-Gurion wrote to Sharett: ‘From day to day we expand our occupation. We occupy new villages and we have just begun.’56

In some of the villages that were close to urban centres, the Jewish troops followed a policy of massacres in order to precipitate the flight of the people in the cities and towns nearby. This was the case of Nasr al-Din near Tiberias, Ayn al-Zaytun near Safad, and Tirat Haifa near Haifa. In all three of these villages, groups of men that were, in the parlance of the Hagana, ‘males between the age of 10 and 50’, were executed in order to intimidate and terrorise the village population and those living in the nearby towns.57 Out of the three massacres, historians do not yet have the full picture for Nasr al-Din, but the other two are well documented, the most well-known of which is Ayn al-Zaytun.





### Ayn al-Zaytun




Ayn al-Zaytun is the best known of the three massacres because its story formed the basis for the only epic novel on the Palestinian catastrophe we have so far, Bab al-Shams by Elias Khoury. The events in the village were also chronicled in a semi-fictional Israeli novella on the period, Netiva Ben-Yehuda’s Between the Knots.58 Bab al-Shams was made into a film, a French-Egyptian co-production.59 The scenes on the screen closely resemble the descriptions we find in Between the Knots, which Ben-Yehuda largely based on reports in the military archives and on oral recollections. The film also faithfully represents the beauty of the village, which lay in a low-lying canyon bisecting the high mountains of the Galilee on the road between Mayrun and Safad, and was graced by a stream of fresh water surrounded by hot mineral pools.

The village’s strategic location, a mile west of Safad, made it an ideal target for occupation. It was also coveted by local Jewish settlers, who had started buying land nearby and who maintained an uneasy relationship with the villagers towards the end of the Mandate. Operation ‘Broom’ provided a chance for the Hagana’s elite unit, the Palmach, not only to cleanse the village in accordance with Plan Dalet on 2 May 1948, but also to settle ‘old accounts’, namely the hostility with which the Palestinian villagers had viewed and received the settlers.

The operation was entrusted to Moshe Kalman, who had already successfully supervised savage attacks on Khisas, Sa‘sa and Husayniyya in the same distinct. His troops encountered very little resistance, as the Syrian volunteers positioned there left hurriedly once the shelling of the village started at dawn: heavy mortar bombardment followed by the systematic throwing of hand grenades. Kalman’s forces entered the village towards noon. Women, children, old people and a few younger men who had not left with the Syrian volunteers came out of hiding waving a white flag. They were immediately herded into the village centre.60

The film then re-enacts the search-and-arrest – in this case the search-and-execute – routine as performed by the special intelligence units of the Hagana. First, they brought in a hooded informer who scrutinised the men lined up in the village square; those whose names appeared on a pre-prepared list the intelligence officers had brought with them were identified. The men selected were then taken to another location and shot dead. When other men rebelled or protested, they were killed as well. In one incident, which the film captured extremely well, one of the villagers, Yusuf Ahmad Hajjar, told his captors that he, like the others, had surrendered and thus ‘expected to be treated humanely’. The Palmach commander slapped him in the face and then ordered him, by way of punishment, to pick thirty-seven teenagers at random. While the rest of the villagers were forced into the storage room of the village mosque, the teenagers were shot with their hands tied behind their backs.

In his book, Hans Lebrecht offers another glimpse of the atrocities, and explains that ‘at the end of May 1948, I was ordered by the military unit in which I served to build a temporary pump station, and to divert the “deserted” village’s stream, Ayn Zaytun, to supply water to the battalion. The village had been totally destroyed, and among the debris there were many bodies. In particular, we found many bodies of women, children and babies near the local mosque. I convinced the army to burn the bodies’.61

These graphic descriptions are also found in the Hagana military reports,62 but how many of Ayn al-Zaytun’s villagers were actually executed is hard to tell. The military documents reported that all in all, including the executions, seventy people had been shot; other sources give a much higher number. Netiva Ben-Yehuda was a member of the Palmach and was in the village when the execution happened, but she preferred to tell the story in a fictionalised way. However, her story offers a chilling detailed description of the way the men of the village were shot while handcuffed, giving the number executed as several hundred:

But Yehonathan continued to yell, and suddenly he turned with his back to Meirke, and walked away furiously, all the time continuing to complain: ‘He is out of his mind! Hundreds of people are lying there tied! Go and kill them! Go and waste hundreds of people! A madman kills people bound like this and only a madman wastes all the ammunition on them! ... I don’t know who they had in mind, who is coming to inspect them, but I understand it’s become urgent, suddenly we have to untie the knots around these POWs’ hands and legs, and then I realized they are all dead, ‘problem solved’.63





According to this account the massacre, as we know from many other mass killings, occurred not only as ‘punishment’ for ‘impertinence’ but also because the Hagana had as yet no POW camps for the large numbers of villagers captured. But even after such camps were set up, massacres occurred when large groups of villagers were captured, as in Tantura and Dawaymeh after 15 May 1948.

Oral histories, which provided Elias Khoury with the material for Bab al-Shams, also reinforce the impression that the archival material does not tell the full story: it is economical about the methods employed and misleading about the number of people killed on that fateful day in May 1948.

As noted, each village served as a precedent that would become part of a pattern and a model that then facilitated more systematic expulsions. In Ayn al-Zaytun, the villagers were taken to the edge of the village where the Jewish troops then started firing shots over their heads as they ordered them to flee. The routine procedures were followed as well: the people were stripped of all their belongings before being banished from their homeland.

The Palmach later seized the nearby village, Biriyya, and, as in Ayn al-Zaytun, ordered all the houses to be burnt in order to demoralize the Arabs of Safad.64 Only two villages remained in the area. The Hagana now faced a more complicated task: how to similarly homogenize, or rather ‘Judaize’, the Marj Ibn Amir region and the vast plains that stretched between the valley and the River Jordan, all the way eastwards to occupied Baysan, and all the way north up to the city of Nazareth, which was still free in those days.





### Completing the mission in the East




It was Yigael Yadin who in April demanded a more determined effort to depopulate this vast area. He seemed to suspect the troops of not being enthusiastic enough, and wrote directly to several members of the kibbutzim in the vicinity to check if the troops had indeed occupied and destroyed the villages they had been ordered to eliminate.65

However, the soldiers’ hesitations were not for lack of motivation or zeal. It was, in fact, the intelligence officers who restricted the operations. In part of the area, especially close to the city of Nazareth, all the way down to Afula, there were large clans who had cooperated – read: ‘collaborated’ – with them for years. Should they be expelled as well?

Local intelligence officers, such as Palti Sela, were particularly concerned about the fate of one huge clan: the Zu’bis. Palti Sela wanted them to be exempted. In an interview he gave in 2002 he explained that he was not sure how, in the haste of the operation, they would be able to select the right people. It all depended, he remembered, on his ability to tell the difference between them and the others: ‘The Zu’bis were always different in their external look from the other villagers. The men, not the females. You could not tell the difference with the females, neither among the old males.’ In any case, he later regretted the effort as the Zu’bis in the end proved not that cooperative and after 1948 had reinforced their Palestinian identity. ‘Today they are “cholera”,’ (Hebrew colloquial for scum) he told his interviewer, adding that they ‘spit into the plate that fed them.’66

Eventually, it was decided to leave intact those villages that had a large share of the Zu’biyya clan. The most ‘difficult’ decision concerned the village of Sirin as it had only a few members of the clan; as we saw, the whole village was eventually expelled. Palti Sela wrote a letter to the heads of the families: ‘Although you are part of the seven villages that were allowed to stay, we cannot protect you. I suggest you all leave for Jordan,’67 which they did.

For many years, his fellow kibbutzniks refused to forgive him for one village that he had ‘saved’: the village of Zarain. ‘Behind my back, people call me traitor, but I am proud,’ he told his interviewer many years later.68





## SUCCUMBING TO A SUPERIOR POWER




One of the major indications that the Jewish forces had the upper hand in 1948, and that the Jewish community in Palestine as a whole was far from facing the fate of extinction and destruction the official Zionist myth paints for us, was the decision of several ethnic minorities in the country to leave the Palestinian camp and join the Jewish forces.

The first and most important of these were the Druze, a religious sect that regards itself as Muslim although Islamic orthodoxy does not accept their claim. The Druze emerged as an offshoot of the Ismailis, themselves a splinter group of Shia Islam. Particularly important in this context are the Druze who had joined the ALA when it entered the country. In the beginning of April 1948, 500 of them deserted the ALA to join the Jewish forces. How this took place forms one of the more curious chapters in the 1948 war. The deserters first pleaded with the Jewish commanders in the Galilee that before they changed sides, they would participate in a phony battle and be taken captive, and only then would they declare their loyalty to Zionism. Such a battle was duly staged near the town of Shafa‘Amr, between the villages of Khirbat al-Kasayir and Hawsha – both later destroyed – and the Druze then signed a pompous-sounding ‘treaty of blood’.69

Khirbat al-Kasayir and Hawsha were the first two villages Jewish troops attacked and occupied within the area the UN partition resolution had allocated to a Palestinian state. These attacks highlight the determination of the Zionist movement to occupy as much of Palestine as possible, even before the end of the Mandate.

One of the more tragic consequences of their defection was that the Druze troops became the main vehicle for the Jews to carry out the ethnic cleansing of the Galilee. Their alliance with the Zionist movement has inexorably alienated the Druzes from the rest of the Palestinians. Only recently do we find a younger generation seemingly beginning to rebel against this isolation, but also discovering how difficult this proves in a patriarchal society ruled firmly by its elders and spiritual leaders.

Another sect, the Circassians, who had several villages in the north of the country, also decided to show allegiance to the powerful Jewish military presence, and 350 of them joined the Jewish forces in April. This mixture of Druze and Circassians would form the nucleus for the future Border Police of Israel, the main military unit policing, first, the Arab areas in pre-1967 Israel, and then enforcing Israel’s occupation of the West Bank and the Gaza Strip after 1967.





## ARAB REACTIONS




When the Jewish forces occupied and destroyed the first villages in December 1947, it seemed that Galilee was the only area where there was a chance of stopping these assaults, with the help of Fawzi al-Qawqji. He commanded an army of 2000 men and impressed the local population with a series of attacks he conducted against isolated Jewish settlements (as have other units coming in via today’s West Bank). But these were ultimately unsuccessful attempts and never caused any significant change in the balance of power. Al-Qawqji was limited in his ability because of the strategy he followed of dividing his troops into small units and sending them to as many cities, towns and villages as possible, where they then formed inadequate defence forces.

The presence of such an army of volunteers could have caused the situation to deteriorate further, pushing Palestine into a direct confrontation, but this did not happen. On the contrary, having attacked a series of isolated settlements as well as the Jewish convoys that came to assist them, al-Qawqji began seeking a truce in January, and continued this all through February and March 1948. Realising that the Jews enjoyed superiority in every military parameter, he tried to negotiate directly with the Consultancy, some of whose members he knew from the 1930s. At the end of March, he met Yehoshua Palmon, apparently with the blessing of Transjordan’s King Abdullah. He offered Palmon a non-aggression pact that would keep the Jewish forces within the designated Jewish state, and would eventually allow negotiations over a cantonised Palestine. His proposals, needless to say, were rejected. Still, al-Qawqji never conducted a significant offensive, nor could he wage one, until the Jewish forces pushed into the areas the UN had allocated to the Arab state.

Al-Qawqji offered not only a cease-fire but also to bring the issue of a Jewish presence in Palestine back to the Arab League to discuss its future. However, Palmon was sent more as a spy than a delegate for negotiations: he was struck by the poor equipment and lack of motivation to fight among the ALA. This was the main piece of information the Consultancy wanted to hear.70

Al-Qawqji’s appearance was accompanied by the arrival in the southern coastal plain of Muslim Brotherhood volunteers from Egypt. They were full of enthusiasm, but totally ineffective as soldiers or troops, as was quickly proven when the villages they were supposed to defend were occupied, emptied and destroyed in quick succession.

In January 1948, the level of war rhetoric in the Arab world had reached new heights, but the Arab governments by and large never moved beyond talking about the need to salvage Palestine, at the same time that both the local media and dailies, such as Filastin, and the foreign press, especially The New York Times, were methodically reporting Jewish attacks on Palestinian villages and neighbourhoods.

The Arab League’s general secretary, Azzam Pasha, an Egyptian politician, hoped at that point that the UN would re-intervene and absolve the Arab states from direct confrontation in Palestine.71 But the international organisation was at a loss. Intriguingly, the UN had never posed the question of how it should act if the Palestinians were to decide to reject the partition plan. The UN had left the issue open while its officials, through the good services of countries such as Britain and France, inquired only whether neighbouring Arab countries might annex the areas allocated to the Palestinians, and were basically satisfied to learn that one such neighbour, Jordan, was already negotiating with the Jews a possible takeover of ‘Arab’ Palestine. The Jordanians eventually did gain control over that area, which became known as the West Bank, most of it annexed without a shot being fired. The other Arab leaders were unwilling to play the game as yet, so they kept up the rhetoric that their intervention was for the sake of helping the Palestinians liberate Palestine, or at least salvage parts of it.

The Arab decision as to how much to intervene and assist was directly affected by developments on the ground. And on the ground they watched – politicians with growing dismay, intellectuals and journalists with horror – the beginning of a depopulation process unfolding in front of their eyes. They had enough representatives in the area to be fully aware of the intent and scope of the Jewish operations. Few of them were in any doubt at that early stage, in the beginning of 1948, of the potential disaster awaiting the Palestinian people. But they procrastinated, and postponed, for as long as they could, the inevitable military intervention, and then were only too happy to terminate it sooner rather than later: they knew full well not only that the Palestinians were defeated, but also that their armies stood no chance against the superior Jewish forces. In fact, they sent troops into a war they knew they had little or no chance of winning.

Many of the Arab leaders were cynical about the looming catastrophe in Palestine, and few were genuinely concerned. But even the latter needed time to assess, not so much the situation as the possible implications of any involvement on their precarious positions back home. Egypt and Iraq were embroiled in the final stages of their own wars of liberation, and Syria and Lebanon were young countries that had just won independence.72 Only when the Jewish forces intensified their actions and their true intentions became fully exposed did Arab governments design some sort of a coordinated reaction. In order not to be sucked into a whirlwind that could undermine their already shaky standing in their own societies, they transferred the decision to their regional outfit, the Arab League Council, made up, as mentioned above, of the Arab states’ foreign ministers. This was an ineffective body as its decisions could be rejected, freely misinterpreted or, if accepted, only partly implemented. This body dragged out its discussions even after the reality in rural and urban Palestine had become too painfully clear to be ignored, and only at the end of April 1948 was it decided that they would send troops into Palestine. By then a quarter of a million Palestinians had already been expelled, two hundred villages destroyed and scores of towns emptied.

It was in many ways al-Qawqji’s defeat in Marj Ibn Amir that convinced the Arab leaders they would have to send regular forces. Al-Qawqji had failed to occupy Kibbutz Mishmar Ha-Emeq after ten days of fighting which had begun on April 4, the only Arab offensive action before May 1948.

Before the final decision to enter was taken, on 30 April, responses from the Arab states varied. All were asked by the Council to send arms and volunteers, but not all complied with the request. Saudi Arabia and Egypt pledged small-scale financial help, Lebanon promised a limited number of guns, and it seems that only Syria was willing to engage in proper military preparations, also persuading its Iraqi neighbour to train and send volunteers into Palestine.73

There was no lack of volunteers. Many people in the surrounding Arab countries came out and demonstrated against their governments’ inaction; thousands of young men were willing to sacrifice their life for the Palestinians. Much has been written about this strong outpouring of sentiment but it remains an enigma – classifying it as pan-Arabism hardly does it justice. Perhaps the best explanation one can offer is that Palestine and Algeria became models for a fierce and bold anti-colonialist struggle, a confrontation that inflamed the national fervour of young Arabs around the Middle East, whereas in the rest of the Arab world national liberation came about through drawn-out diplomatic negotiations, always far less exciting. But I stress again, this is only a partial analysis of the willingness of young Baghdadis or Damascenes to leave everything behind for the sake of what they must have regarded as a sacred, though by no means a religious, mission.

The odd man out in this matrix was King Abdullah of Transjordan. He used the new situation to intensify his negotiations with the Jewish Agency over a joint agreement in post-Mandatory Palestine. While his army had units inside Palestine, and some of them were, here and there, willing to help the villagers protect their houses and lands, they were largely restrained by their commanders. Fawzi al-Qawqji’s diary reveals the ALA commander’s growing frustration with the unwillingness of the Arab Legion units stationed in Palestine to cooperate with his troops.74

During the Jewish operations between January and May 1948, when around 250,000 Palestinians were driven by force from their homes, the Legion stood idly by. In fact, it was in January that the Jordanians and the Jews had cemented their unwritten agreement. In early February 1948 the Jordanian prime minister had flown to London to report on the conclusion of their tacit alliance with the Jewish leadership over the partition of post-Mandatory Palestine between the Jordanians and the Jewish state: the Jordanians were to annex most of the areas allocated to the Arabs in the partition resolution, and in return would not join the military operations against the Jewish state. The British gave the scheme their blessing.75 The Arab Legion, the Jordanian army, was the best trained in the whole Arab world. It matched, and in some areas was even superior to, the Jewish troops. But it was confined by the King and his British General Chief of Staff, John Glubb Pasha, to act only in those areas the Jordanians deemed theirs: East Jerusalem and the area now known as the West Bank.

The final meeting that determined the limited role the Legion was to play in the rescue of Palestine took place on 2 May 1948. A top-ranking Jewish officer, Shlomo Shamir, met with two senior Legion officers, British, as most of them were: Colonel Goldie and Major Crocker. The Jordanian guests brought a message from their king saying he recognised the Jewish state, but wondered whether the Jews ‘wanted to take the whole of Palestine?’ Shamir was candid: ‘We could, if we wanted to; but this is a political question.’ The officers then explained where the Jordanians’ main apprehensions lay: they had noticed that the Jewish forces were occupying and cleansing areas that were within the UN-designated Arab state, such as Jaffa. Shamir responded by justifying the Jaffa operation as necessary for safeguarding the road to Jerusalem. Shamir then made it clear to the emissaries from Jordan that, as far as the Zionsts were concerned, the UN designated Arab state had shrunk to include only the West Bank, which the Israelis were willing to ‘leave’ for the Jordanians.76

The meeting ended with an abortive attempt by the Jordanian officers to come to an agreement over the future of Jerusalem. If the Jewish Agency were willing to partition Palestine with the Jordanians, why not apply the same principle to Jerusalem? As Ben-Gurion’s faithful proxy, Shamir rejected the offer. Shamir knew the Zionist leader was convinced his army was strong enough to take the city as a whole. An entry in his diary a few days later, on 11 May, shows that Ben-Gurion was aware the Legion would fight fiercely over Jerusalem and, if necessary, for its overall share in post-Mandatory Palestine, that is, the West Bank. This was duly confirmed two days later when Golda Meir met King Abdullah in Amman (on 13 May), where the king seemed more tense than ever before because of the double game he was playing in his effort to come out on top: promising the member states of the League to head the military effort of the Arab countries in Palestine on the one hand, and striving to reach an agreement with the Jewish state on the other.77

At the end of the day, the latter became decisive for the course of action he would take. Abdullah did everything he could to be seen to be taking a serious part in the overall Arab effort against the Jewish state, but in practice his main objective was to secure Israeli consent for the Jordanian annexation of the West Bank.

Sir Alec Kirkbride was the British representative in Amman, a position that combined those of Ambassador and High Commissioner. On 13 May 1948, Kirkbride wrote to Ernest Bevin, Britain’s foreign secretary:

There have been negotiations between the Arab Legion and the Hagana which have been conducted by British officers of the Arab Legion. It is understood that the object of these top secret negotiations is to define the areas of Palestine to be occupied by the two forces.





Bevin replied:

I am reluctant to do anything that might prejudice the success of these negotiations, which appear to aim at avoiding hostility between the Arabs and the Jews. The implementation of this agreement depends on the British officers of the Legion. That is why we should not withdraw the Legion officers [from Palestine].78





But Ben-Gurion never took for granted that the Jordanians would stick to the limited role he had set aside for them, which reinforces the impression that he felt confident the new state had enough military power to successfully confront even the Legion while simultaneously continuing the ethnic cleansing.

At the end of the day, the Legion had to fight for their annexation, notwithstanding Jordan’s collusion with Israel. At first the Jordanians were allowed to take over the areas they wanted without a shot being fired, but a few weeks after the end of the Mandate the Israeli army tried to wrest parts of it back. David Ben-Gurion seemed to regret his decision not to exploit the war more fully in order to enlarge the Jewish state even beyond the seventy-eight per cent he coveted. The general Arab impotence seemed to give the Zionist movement an opportunity that was too good to be missed. However, he underestimated the Jordanian determination. Those parts of Palestine that King Abdullah was adamant were his, the Legion successfully defended until the war was over. In other words, the Jordanian occupation of the West Bank at first came about thanks to a prior agreement with the Jews, but it remained in Hashemite hands thereafter due to the tenacious defensive efforts of the Jordanians and the Iraqi forces that helped repel Israeli attacks. It is possible to see this episode from a different angle: by annexing the West Bank, the Jordanians saved 250,000 Palestinians from being ousted – until, that is, they were occupied by Israel in 1967 and subjected – as they still are – to new waves of expulsion, be they more measured and slow. The actual Jordanian policy in the very last days of the Mandate is detailed in the next chapter.

As for the Palestinian leadership, what remained of it was fragmented and in total disarray. Some of its members left hurriedly and, they hoped in vain, temporarily. Very few of them wished to stay and confront the Jewish aggression in December 1947 and the onset of the cleansing operations in January 1948, but some did stay behind, and remained official members of the national committees. Their activities were supposed to be coordinated and supervised by the Arab Higher Committee, the unofficial government of the Palestinians since the 1930s, but half of its members had by now also left and those remaining found it difficult to cope. For all their failings in the past, however, they stood alongside their communities almost to the bitter end, although they could easily have opted to leave. They were Emil Ghori, Ahmad Hilmi, Rafiq Tamimi, Mu’in al-Madi and Husayn al-Khalidi. Each of them was in contact with several local national committees and with al-Hajj Amin al-Husayni, chairman of the Arab Higher Committee, who followed events with his close associates Shaykh Hasan Abu Su’ud and Ishaq Darwish, in Cairo, where he now resided. Amin al-Husayni had been exiled in 1937 by the British. Would he have been able to return in those days of chaos and turmoil, given the British presence in the land? He never tried to go back so the point is moot. His relative, Jamal al-Husayni, acting chairman of the Arab Higher Committee in his absence, left in January for the US to try to initiate a belated diplomatic campaign against the UN resolution. The Palestinian community for all intents and purposes was a leaderless nation.

In this context, Abd al-Qadir al-Husayni should be mentioned once more since he tried to organise a paramilitary unit from among the villagers themselves to protect them. His army, the ‘Holy War Army’, a rather grand name for the shaky outfit he headed, held on until 9 April, when it was defeated and Abd al-Qadir was killed by the Hagana forces that outnumbered them with their superior equipment and military experience.

A similar effort was attempted in the Greater Jaffa area by Hasan Salameh, whom I have already mentioned, and Nimr Hawari (who later surrendered to the Jews and became the first Palestinian judge in 1950s Israel). They tried to transform their scouts’ movements into paramilitary units, but these, too, were defeated within a few weeks.79

Thus, prior to the end of the Mandate, neither the Arab volunteers from outside Palestine nor the paramilitary troops on the inside put the Jewish community at any serious risk of either losing the battle or being forced to surrender. Far from it; all that these foreign and local forces tried, but were unable, to do was to protect the local Palestinian population against Jewish aggression.

Israeli, and in particular American, public opinion, however, succeeded in perpectuating the myth of potential destruction or a ‘second Holocaust’ awaiting the future Jewish state. Exploiting this mythology, Israel was later able to secure massive support for the state in Jewish communities around the world, while demonising the Arabs as a whole, and the Palestinians in particular, in the eyes of the general public in the US. The reality on the ground was, of course, almost the complete opposite: Palestinians were facing massive expulsion. The month that Israeli historiography singles out as the ‘toughest’ actually saw the Palestinians simply attempting to be saved from that fate, rather than being preoccupied with the destruction of the Jewish community. When it was over, nothing stood in the way of the cleansing troops of Israel.





## TOWARDS THE ‘REAL WAR’




On the face of it, from the Palestinian point of view, the situation seemed to improve towards the second half of April 1948. Abdullah informed his Jewish interlocutors that the Arab League had decided to send regular armies into Palestine: the events in Palestine in the months of March and April left the leaders of the Arab world no other choice. They now began to prepare in earnest for a military intervention. Then from Washington came the unexpected news that the State Department was pushing towards a novel American approach. US representatives on the ground were by now fully aware of the expulsions that were going on and had suggested to their chiefs back home to halt the implementation of the partition plan and try to work towards an alternative solution.

Already by 12 March 1948, the State Department had drafted a new proposal to the UN, which suggested an international trusteeship over Palestine for five years, during which the two sides would negotiate an agreed solution. It has been suggested that this was the most sensible American proposal ever put forward in the history of Palestine, the like of which, alas, was never repeated. In the words of Warren Austin, the US ambassador to the United Nations: ‘The USA position is that the partition of Palestine is no longer a viable option.’80

Member states of the UN coming together in Flushing Meadows, New York, where the UN was located before it moved to its current high rise in Manhattan, liked the idea. It made a lot of sense to conclude that partition had failed to bring peace to Palestine and, in fact, was breeding more violence and bloodshed. However, while logic was one aspect to take into consideration, the wish not to antagonise a powerful domestic lobby was another, and in this case a superior one. Had it not been for highly effective pressure by the Zionist lobby on President Harry Truman, the course of Palestine’s history could have run very differently. Instead, the Zionist sections of the American Jewish community learned an important lesson about their ability to impact American policy in Palestine (and later beyond, in the Middle East as a whole). In a longer process that continued through the 1950s and early 1960s, the Zionist lobby succeeded in sidelining the State Department’s experts on the Arab world and left American Middle Eastern policy in the hands of Capitol Hill and the White House, where the Zionists wielded considerable influence.

But the victory on Capitol Hill was not easily won. The ‘Arabists’ in the State Department, reading more carefully the reports from the New York Times than the President’s men, desperately tried to convice Truman, if not to substitute partition with trusteeship, at least to allow more time for rethinking the partition plan. They persuaded him to offer the two sides a three month armistice.

On 12 May, a Wednesday afternoon, the ordinary meeting of the Matkal and the Consultancy was postponed for a crucial meeting in a new body, the ‘People’s Board’, which was three days later to become the government of the State of Israel. Ben-Gurion claimed that almost all those present supported the decision to reject the American offer. Historians later claimed he had a difficult time passing the resolution, which meant not only rejecting the American plan but declaring, three days later, a state. This was not such an important meeting after all, as the Consultancy was already pushing ahead with its ethnic cleansing operations, which Ben-Gurion would not have allowed others in the Zionist political elite to halt, who were not privy in the past to the vision and the plan. The White House then went on to recognise the new state and the State Department was pushed again to its back bench on US policy on Palestine.81

On the last day of April, the Arab world had appointed the man most of its leaders knew had a secret agreement with the Jews to head the military operations against Palestine. No wonder that Egypt, the largest Arab state, waited until the failure of the last American initiative before deciding to join the military effort, something its leaders knew would end in a fiasco. The decision passed in the Egyptian Senate on 12 May left the Egyptian army with less than three days to prepare for the ‘invasion’, and its performance on the battlefield testified to this impossibly short period of preparation.82 The other armies, as we shall see later, did not fare any better. Britain remained the last hope in those days of April and May, but nowhere in its Empire did Albion demonstrate such perfidious behaviour.





### British Responsibility




Did the British know about Plan Dalet? One assumes they did, but it is not easy to prove. Highly striking is that after Plan Dalet was adopted, the British announced that they were no longer responsible for law and order in the areas where their troops were still stationed, and limited their activities to protecting these troops. This meant that Haifa and Jaffa and the whole coastal region between them were now one open space where the Zionist leadership could implement Plan Dalet without any fear of being thwarted or even confronted by the British army. Far worse was that the disappearance of the British from the countryside and the towns meant that in Palestine as a whole law and order totally collapsed. The newspapers of the day, such as the daily Filastin, reflected the people’s anxiety about the rising level of such crimes as theft and burglary in the urban centres and looting around the villages. The withdrawal of British policemen from the cities and towns also meant, for example, that many Palestinians could no longer collect their salaries in the local municipalities: most of the governmental services were located in Jewish neighbourhoods in which they were likely to be assaulted.

No wonder one can still hear Palestinians say today: ‘The main responsibility for our catastrophe lies with the British Mandate,’ as Jamal Khaddura, a refugee from Suhmata near Acre, put it.83 He bore this sense of betrayal with him throughout his life and re-articulated it in front of a joint British parliamentary Middle East commission of inquiry on the Palestinian refugees established in 2001. Other refugees who gave testimonies to this commission echoed Khaddura’s bitterness and accusations of blame.

Indeed, the British avoided any serious intervention as early as October 1947, and stood idly by in the face of attempts by the Jewish forces to control outposts; nor did they try to stop small-scale infiltration by Arab volunteers. In December, they still had 75,000 troops in Palestine, but these were dedicated solely to safeguard the eviction of the Mandatory soldiers, officers and officials.

The British sometimes assisted in other, more direct, ways in the ethnic cleansing, by providing the Jewish leadership with ownership deeds and other vital data, which they had photocopied before destroying them, as was quite common in their decolonization process. This inventory added to the village files the final details the Zionists needed for the massive depopulation. Military force, and a brutal one at that, is the first requirement for expulsion and occupation, but bureaucracy is no less important for efficiently carrying out a huge cleansing operation that entails not only dispossession of the people but also the repossession of the spoils.





### UN Betrayal




According to the Partition Resolution, the UN was to be present on the ground to supervise the implementation of its peace plan: the making of Palestine as a whole into an independent country, with two distinct states that were to form one economic unity. The resolution of 29 November 1947 included very clear imperatives. Among them, the UN pledged to prevent any attempt by either side to confiscate land that belonged to citizens of the other state, or the other national group – be it cultivated or uncultivated land, i.e., land that had lain fallow for about a year.

To the local UN emissaries’ credit, it can be said that they at least sensed things were going from bad to worse and were tying to push for a re-evaluation of the partition policy, but they took no action beyond watching and reporting the beginning of the ethnic cleansing. The UN had only limited access to Palestine, since the British authorities forbade an organised UN outfit to be present on the ground, thereby ignoring that part of the Partition Resolution that demanded the presence of a United Nations committee. Britain allowed the cleansing to take place, in front of the eyes of its soldiers and officials, during the Mandate period, which came to an end at midnight on 14 May 1948, and hampered the UN efforts to intervene in a way that might have saved a number of Palestinians. After 15 May, there was no excuse for the way the UN abandoned the people whose land they had divided and whose welfare and lives they had surrendered to the Jews who, since the late nineteenth century, wished to uproot them and take their place in the country they deemed as theirs.



