---
title: "Completing the Job"
subtitle: "October 1948–January 1949"
---

> Over 1.5 million ethnic Albanians – at least 90% of the Kosovo population of the province had been forcibly expelled from their homes. At least a million left the province and half a million appear to be internally displaced persons. This is a campaign on a scale not seen in Europe since the Second World War.

State Department Report on Kosovo, 1999.

> In 1948, 85% of the Palestinians living in the areas that became the state of Israel became refugees.

> It is estimated that there were more than 7 million Palestinian refugees and displaced persons at the beginning of 2003.

Badil Resource Centre: Facts and figures.

The month of October began rather frustratingly for the Israeli cleansing forces. The Galilee, especially in its upper parts, was still controlled by Palestinian volunteers reinforced by al-Qawqji’s ALA units. The latter could still be found in many villages in the northern Galilee – all part of the UN-designated Arab state – where they tried to wage a miniguerilla warfare against the armed Jewish forces, mainly in the form of sniper fire at convoys and troops. But theirs was an ineffective kind of resistance, largely in vain. October also saw the final futile attempt by regular forces from Lebanon to add their firepower in a last pathetic gesture of Arab solidarity as they shelled one Jewish settlement, Manara, high up in the Galilee. Down south in the lower Galilee the Arab volunteers were left with one artillery gun in Ilabun. It symbolised their imminent and total collapse.

Whatever resistance may still have existed was wiped out during the onslaught of Operation Hiram in the middle of the month. Hiram was the name of the biblical king of Tyre, which was one of the targets of this ambitious and expansionist scheme: Israel’s takeover of the upper Galilee and Southern Lebanon. With intensive artillery and air force attacks, Jewish troops captured both in a matter of two weeks.





## OPERATION HIRAM




These two weeks now rank, together with the heroic struggle to save Wadi Ara, as one of the most impressive chapters in the history of the Palestinian resistance during the Nakba. The Israeli air force dropped about 10,000 leaflets calling upon the villagers to surrender, although not promising them any immunity from expulsion. None of the villages did and, almost as a whole, came out to confront the Israeli forces.

Thus, for a brief period, in courageous defiance of the vastly superior Israeli military power, Palestinian villages, for the first time since the ethnic cleansing started, turned themselves into strongholds, standing up to the besieging Israeli troops. A mixture of local youth and the remnants of the ALA were entrenched for a week or two, holding out with what meagre arms they had before being overpowered by the assailants. Fifty such brave men defended Ramaysh; others could be found in Deir al-Qasi, most of them in fact not locals but refugees from Saffuriyya, vowing not to be displaced again. They were commanded by a man called Abu Hammud from the ALA. Unfortunately, we only have the names of a few officers from the Israeli intelligence files and oral histories, such as Abu Ibrahim who defended Kfar Manda, but, like the Iraqi officers mentioned in the Wadi Ara campaign, they should all be written into the Palestinian, and universal, book of heroes who did everything they could to try to prevent ethnic cleansing from taking place. Israel, and the West in general, refers to them anonymously and collectively as Arab insurgents or terrorists – as they have done with the Palestinians who fought within the PLO until the 1980s, and others who led the two uprisings against the Israeli occupation in the West Bank and the Gaza Strip in 1987 and 2000. I have no illusion that it will take more than this book to reverse a reality that demonises a people who have been colonised, expelled and occupied, and glorifies the very people who colonised, expelled and occupied them.

This handful of warriors of a sort were inevitably defeated, subjected to heavy bombardments from the air and fierce ground attacks. The ALA volunteers withdrew first, after which the local villagers decided to surrender, quite often through UN mediation. But a distingushing feature of this phase in the Nakba was that the withdrawal of the volunteers, who by now had already spent ten months in Palestine, only came about after they had desperately fought to defend the villages, quite often disobeying orders from their headquarters to leave: four hundred such volunteers lost their lives in those days in October.

The Israeli air bombardments were massive and caused a considerable amount of ‘collateral damage’ to the Palestinian villages. Some villages suffered more than others from heavy pounding: Rama, Suhmata, Malkiyya and Kfar Bir‘im. Only Rama was left intact; the other three were occupied and destroyed.

Most of the villages in the upper Galilee were seized in a single day at the end of October: Deir Hanna, Ilabun, Arraba, Iqrit, Farradiyya, Mi’ilya, Khirbat Irribin, Kfar Inan, Tarbikha, Tarshiha, Mayrun, Safsaf, Sa‘sa, Jish, Fassuta, and Qaddita. The list is long and includes another ten villages. Some villagers were evicted, some were allowed to stay.

The main question about those days is no longer why villages were expelled, but rather why some were allowed to remain, obviously almost always as a result of the decision made by a local commander. Why was Jish left intact and nearby Qaddita and Mayrun expelled by force? And why was Rama spared, while nearby Safsaf was totally demolished? It is hard to tell and much of what follows is based on speculation.

Located on the well-travelled road between Acre and Safad, the village of Rama was already overcrowded, having earlier taken in a large number of refugees from other villages. The size of the village, but quite possibly its large Druze community, were two factors that probably influenced the local decision not to expel its population. However, even for villages that were allowed to stay, scores, sometimes hundreds, of their inhabitants were imprisoned in POW camps or expelled to Lebanon. In fact, the Hebrew noun tihur, ‘cleansing’, assumed new meanings in October. It still described, as before, the total expulsion and destruction of a village, but it could now also represent other activities, such as selective search-and-expulsion operations.

While Israel’s divide-and-rule policy proved effective in the case of the Druze, to whom it promised not only immunity but also arms as rewards for their collaboration, the Christian communities were less ‘cooperative’. Israeli troops at first routinely deported them together with the Muslims, but then started transferring them to transit camps in the central coastal areas. In October, Muslims rarely remained long in these camps but were ‘transported’ – in the language of the Israeli army – to Lebanon. But Christians were now offered a different deal. In return for a vow of allegiance to the Jewish state, they were allowed to return to their villages for a short time. To their credit, most of the Christians refused to participate willingly in such a selection process. As a result, the army soon meted out the same treatment to Christian as to Muslim villages where they did not have a Druze population.

Instead of waiting to be deported, imprisoned or killed, many villagers simply ran away. Heavy bombardments in advance of the occupation precipitated the flight of many villagers, varying in numbers from case to case. But in most instances, the majority of the people bravely stayed put until they were forcibly uprooted. Additionally, it would appear that during the very last days of October the ‘cleansing’ stamina of the Israeli troops was beginning to wane, because villages with large populations were eventually allowed to stay. This may help explain why Tarshiha, Deir Hanna and Ilabun are still intact today.

Or rather, half of the people of Ilabun are still with us today: the other half of the original population live in refugee camps in Lebanon. Those who were allowed to resettle in the village went through horrific experiences. During the occupation, the villagers had taken refuge in Ilabun’s two churches. The frightened community crowded inside the small church buildings, cowering at the entrances as they were forced to listen to a long ‘speech’ by the Israeli commander of the operation. A sadistic and capricious person, he told the besieged villagers that he blamed them for the mutilation of two Jewish bodies, for which he instantly retaliated by mowing down several young men in front of the horrified congregation. The rest of the people were then forcibly evicted, apart from the men between the ages of ten and fifty who were led away as prisoners of war.1

At first, everyone the village was expelled, and started making their way in a long column marching towards the Lebanese border, several of the villagers dying on the way. Then the Israeli commander changed his mind and ordered the Christians, who made up half the deportees, to turn back along the same painful and arduous route they had just taken through the rocky mountains of the Galilee. Seven hundred and fifty people were thus allowed to return to their village.

The question of why certain villages were allowed to remain is perplexing, but equally hard to understand is why the Israeli forces subjected certain villages and not others to treatment that proved exceptionally savage. Why, for example, from all the villages conquered in the final days of October were Sa‘sa and Safsaf exposed to such barbarity while others were exempted from it?





### War Crimes During the Operation




As mentioned earlier, in February 1948 Jewish troops had perpetrated a massacre in the village of Sa‘sa that ended in the killing of fifteen villagers, including five children. Sa‘sa is located on the main road to Mount Myarun (today Meron), the highest mountain peak in Palestine. After it had been occupied, the soldiers of Brigade Seven ran amok, firing randomly at anyone in the houses and on the streets. Besides the fifteen villagers killed, they left behind them a large number of wounded. The troops then demolished all the houses, apart from a few that the members of Kibbutz Sasa, built on the ruins of the village, took over for themselves after the forced eviction of their original owners. The chronicle of what happened in Sa‘sa in 1948 cannot easily be constructed from the archival material, but there is a highly active community of survivors bent on preserving their testimonies for posterity. Most of the refugees live in Naher al-Barid, a refugee camp near Tripoli, Lebanon; some are in Rashidiyya camp near Tyre, and others, mostly from a single clan, live in Ghazzawiyya. A smaller community also resides in the Ayn Hilwa refugee camp in southern Lebanon, while I met a few of the survivors now living in the village of Jish, in the Galilee.2 They find it difficult to revisit the horrible events surrounding the occupation of their village. Though more information needs to be gathered before we can reconstruct exactly how events unfolded in Sa‘sa, the story they tell does indicate, as in the case of the survivors of Tantura, that the Israeli troops perpetrated a massacre in the village.

We know more about Safsaf. Muhammad Abdullah Edghaim was born 15 years before the Nakba. He had attended elementary school in the village until the seventh grade and had completed his first year in Safad’s high school when the city fell into Jewish hands in May. No longer able to attend school, he was at home when a mixed unit of Jewish and Druze soldiers entered his village on 29 October 1948.

Their arrival had been preceded by heavy bombardment that had killed, among others, one of Galilee’s best known singers, Muhammad Mahmnud Nasir Zaghmout. He died when a shell hit a group of villagers working in the vineyards to the west of the village. The young boy witnessed the singer’s family trying to carry his body to the village, but they had to abandon the attempt due to the heavy shelling.

Every one of the defenders of Safsaf, among them ALA volunteers, was waiting, for some reason, for a Jewish attack to arrive from the east, but it came from the west and the village was quickly overrun. The following morning the people were ordered to assemble in the village square. The familiar procedure for identifying ‘suspects’ now took place, this time also involving the Druze soldiers, and a large number were picked out from the captured population. Seventy of the unfortunate men were taken out, blindfolded and then moved to a remote spot and summarily shot. Israeli archival documents confirm this case.3 The rest of the villagers were then ordered to leave. Unable to collect even their most meagre personal possessions, they were driven out, with the Israeli troops firing shots above their heads, towards the nearby border with Lebanon.

The oral testimonies, unlike the Israeli military archives, tell of even worse atrocities. There is very little reason to doubt these eyewitness accounts, as so many of them have been corroborated by other sources for other cases. Survivors recall how four women and a girl were raped in front of the other villagers and how one pregnant woman was bayoneted.4

A few people were left behind, as in Tantura, to collect and bury the dead – several elderly men and five boys. Safsaf in Arabic means ‘weeping willow’. Mahmoud Abdulah Edghaim, our main source for the atrocities, is today an old man, still living in the refugee camp of Ayn Hilwah. His little hut is surrounded by the many weeping willows he planted when he first arrived there almost sixty years ago. This is all that remains of Safsaf.

Bulayda was the last village taken during Operation Hiram. It was left until the end as its people proved steadfast in their determination to protect their homes. It was very close to the Lebanese border and Lebanese soldiers crossed the fence and fought alongside the villagers – probably the only significant Lebanese contribution to the defence of the Galilee. For ten days, the village withstood repeated assaults and raids. In the end, realising the hopelessness of their situation, the population fled even before the Israeli soldiers moved in: they did not want to undergo the horrors the people of Safsaf had experienced.

By 31 October, the Galilee, once an area almost exclusively Palestinian, was occupied in its entirety by the Israeli army.





### Mopping-Up Operations




In November and December, some cleansing activity continued in the Galilee, but it took the form of what the Israelis called ‘mopping up operations’. These were in essence ‘second-thought’ operations to cleanse villages that had not originally been targeted. They were added to the list of villages to be evicted because Israel’s political elite wanted to eradicate the unmistakably ‘Arabic’ character of the Galilee. But today, despite all of Israel’s efforts to ‘Judaize’ the Galilee – beginning with direct expulsions in the 1940s, military occupation in the 1960s, massive confiscation of land in the 1970s, and a huge official Judaization settlement effort in the 1980s – it is still the only area in Palestine that has retained its natural beauty, its Middle Eastern flavour and its Palestinian culture. Since half the population is Palestinian, the ‘demographic balance’ prevents many Israeli Jews from thinking of the region as their ‘own’, even at the beginning of the twenty-first century.

Back in the winter of 1948, Israeli attempts to tip this ‘balance’ in their favour included the expulsion of additional small villages such as Arab al-Samniyya near Acre with its 200 inhabitants, and the large village of Deir al-Qasi with a population of 2500.5 In addition, there is the unique story of the three villages of Iqrit, Kfar Bir’im and Ghabisiyya, which began in October 1948 but has still not ended. The tale of Iqrit is fairly representative of what also happened to the other two villages.

The village was close to the Lebanese border, perched high in the mountains, about thirty kilometres east of the coast. An Israeli battalion occupied it on 31 October 1948. The people surrendered without a fight – Iqrit was a Maronite community and they expected to be welcome in the new Jewish state. The commander of the battalion ordered the people to leave on the grounds that it was dangerous for them to stay, but promised them they would be able to return in two weeks time, after the military operations were over. On 6 November, the people of Iqrit were evicted from their houses and transported by army trucks to Rama. Fifty people, including the local priest, were allowed to stay behind to keep an eye on the houses and property but six months later, the Israeli army came back and drove them out as well.6

This is another example of how the methodology of cleansing varied. The case of Iqrit and the neighbouring village of Kfar Bir’im is one of the few publicised instances where, in a long drawn-out process, the indigenous people decided to seek redress through the Israeli courts. The villagers, being Christians, were allowed to stay in the country, but not in their village. They did not capitulate, however, and began a protracted legal struggle for their right to return home, demanding that the army keep its promise. Almost sixty years later, the struggle to regain their stolen lives is still not over.

On 26 September 1949, the Minister of Defence announced that Emergency Regulations (dating from the British Mandate) applied to Iqrit, in order to prevent the repatriation the occupying officer had promised earlier. Almost a year and a half later, on 28 May 1951, the people of Iqrit decided to take their case to the Israeli Supreme Court, which on 31 July declared that the eviction was illegal and ordered the army to allow the people of Iqrit to resettle in their original village. To bypass the Supreme Court ruling, the army needed to show that it had issued a formal order of expulsion during the 1948 war, which would have turned Iqrit into just another depopulated village, like the other 530 Palestinian villages whose expulsion the Israeli courts had condoned retrospectively. The IDF subquently fabricated this formal order without hesitation or scruples. And in September 1951, the former residents of Iqrit, now refugees living in the village of Rama were bewildered to receive the official military order for their ‘formal’ expulsion showing the date of 6 November 1948, but sent almost three years later.

In order to settle the matter once and for all, on Christmas Eve 1951 the Israeli army completely demolished all the houses in Iqrit, sparing only the church and the cemetery. That same year, similar destruction was carried out on nearby villages, among them Qaddita, Deir Hanna, Kfar Bir’im and Ghabisiyya, to prevent repatriation.7 The people of Kfar Bir’im and Ghabisiyya had also managed to secure a categorical ruling from the Israeli courts. As with Iqrit the army had immediately ‘retaliated’ by destroying their villages, offering the cynical excuse that they had been conducting a military exercise in the area involving an air bombardment, somehow leaving the village in ruins – and uninhabitable.

The destruction was part of an ongoing Israeli battle against the ‘Arabisation’ of the Galilee, as Israel sees it. In 1976, the highest official in the Ministry of Interior, Israel Koening, called the Palestinians in the Galilee a ‘cancer in the state’s body’ and the Israeli Chief of Staff, Raphael Eitan, openly spoke of them as ‘cockroaches’. An intensified process of ‘Judaization’ has so far failed to make the Galilee ‘Jewish’, but since so many Israelis today, politicians as well as academics, have come to accept and justify the ethnic cleansing that took place and to recommend it to future policy makers, the danger of additional expulsions still hovers above the Palestinian people in this part of Palestine.

The ‘mopping-up’ operations actually continued well into April 1949, and sometimes resulted in further massacres. This happened in the village of Khirbat Wara al-Sawda, where the Bedouin tribe al-Mawassi resided. This small village in the eastern Galilee had held out against repeated assaults during Operation Hiram and had then been left alone. After one of the attacks, several of the villagers had severed the heads of the dead Israeli soldiers. After the overall hostilities had finally come to an end, in November 1948, revenge followed. The report of the commanding officer from Battalion 103, which committed the crime, describes it graphically. The men of the village were gathered in one place while the troops set fire to all the houses. Fourteen people were then executed on the spot, and the rest moved to a prison camp.8





## ISRAEL'S ANTI-REPATRIATION POLICY




The major activities towards the end of the 1948 ethnic cleansing operation now focused on implementing Israel’s anti-repatriation policy on two levels. The first level was national, introduced in August 1948 by an Israeli governmental decision to destroy all the evicted villages and transform them into new Jewish settlements or ‘natural’ forests. The second level was diplomatic, whereby strenuous efforts were made to avert the growing international pressure on Israel to allow the return of the refugees. The two were closely interconnected: the pace of demolition was deliberately accelerated with the specific aim of invalidating any discussion on the subject of refugees returning to their houses, since those houses would no longer be there.

The major international endeavour to facilitate the return of the refugees was led by the UN Palestine Conciliation Commission (the PCC). This was a small committee with only three members, one each from France, Turkey and the United States. The PCC called for the unconditional return of the refugees to their homes, which the assassinated UN mediator, Count Folke Bernadotte, had demanded. They turned their position into a UN General Assembly resolution that was overwhelmingly supported by most of the member states and adopted on 11 December 1948. This resolution, UN Resolution 194, gave the refugees the option to decide between unconditional return to their homes and/or accepting compensation.

There was a third anti-repatriation effort, and that was to control the demographic distribution of Palestinians both within the villages that had not been cleansed and in the previously mixed towns of Palestine, at that point already totally ‘de-Arabised’. For this purpose, the Israeli army established, on 12 January 1949, a new unit, the Minority Unit. It was made up of Druze, Circassians and Bedouin who were recruited to it for one specific job only: to prevent Palestinian villagers and town dwellers from returning to their original homes. Some of their methods for achieving this objective can be seen in the summary report of Operation Number 10, submitted by the Minority Unit on 25 February 1949:

A report on the search and identification of the villages of Arraba and Deir Hanna. In Deir Hanna, shots were fired above the heads of the citizens (ezrahim) that were gathered for the identification. Eighty of them were taken to prison. There were cases of ‘unbecoming’ behaviour of the military police towards the local citizens in this operation.9





As we shall see, ‘unbecoming’ behaviour usually meant physical and mental harassment of all kinds. In other reports these cases were detailed, yet here we find them obfuscated by vague terminology.

Those who were arrested were deported to Lebanon; but if they found refuge in the area Israel continued to occupy until the spring of 1949, they were likely to be expelled again. Only on 16 January 1949 did the order came to stop the selective deportations from southern Lebanon, and the Minority Unit was instructed to confine its activity solely to the Galilee and the former mixed towns and cities. The mission there was clear: to prevent any attempt – and there were quite a few – by refugees to try to smuggle their way back home, no matter whether they tried to return to a village or a house to live, or just wanted to retrieve some of their personal possessions. The ‘infiltrators’, as the Israeli army called them, were in many cases farmers who sought surreptitiously to harvest their fields or pick the fruit from their now unattended trees. Refugees who tried to slip past the army lines quite often met their death at the hands of Israeli army patrols. In the language of Israeli intelligence reports, they were ‘successfully shot at’. A quote from such a report dated 4 December 1948 records: ‘successful shooting at Palestinians trying to return to the village of Blahmiyya and who attempted to retrieve their belongings.’10

The ‘main problem’, complained one intelligence unit, was that ‘the Syrians are shooting at the refugees [from their side], so we are shooting back at them to enable the refugees to cross the River Jordan.’11 Those who tried to cross the river to Jordan were often turned back by the Hashemite Kingdom as it began to feel the burden of an ever-growing refugee community on its territory, which had already doubled the size of the Jordanian population. The same report commended the Lebanese for ‘allowing’ free passage of refugees into their country.

But even when they were not subjected to ‘arrest-and-deport’ operations or fired at as ‘infiltrators’ or returnees, those villagers who were allowed to remain (around fifty villages out of 400 within the borders Israel had established for itself, as yet excluding the Wadi Ara) were still in danger of being forcibly evicted or transferred to other places because of the greed of Jewish farmers, especially kibbutzniks, who coveted their lands or their location.

This happened on 5 November to a small village, Dalhamiyya, near Kibbutz Ashdot Yaacov in the Jordan Valley area, which was evicted so that the kibbutz could expand its arable land.12 Even worse was the fate of the village of Raml Zayta, near the city of Hadera. It was moved once in April 1949, closer to the West Bank, and then a second time, when in 1953 a new Jewish settlement made up of the younger generation of older kibbutzim decided to move near the new location of Zayta. Upon arrival, the young kibbutzniks were not content with merely grabbing the land, but demanded the government move the houses of the Palestinian village out of their sight.13

The crudeness of the kibbutzim’s demands was matched by the overall transformation of the language of the expellers. For Operation Hiram, the operative commands read as follows:

Prisoners: cars will be ready to transport the refugees (plitim) to points on the Lebanese and Syrian borders. POW camps will be built in Safad and Haifa, and a transit camp in Acre; all the Muslim inhabitants have to be moved out.14





Under the watchful eyes of UN observers who were patrolling the skies of the Galilee, the final stage of the ethnic cleansing operation, begun in October 1948, continued until the summer of 1949. Whether from the sky or on the ground, no one could fail to spot the hordes of men, women and children streaming north every day. Ragged women and children were conspicuously dominant in these human convoys: the young men were gone – executed, arrested or missing. By this time UN observers from above and Jewish eyewitnesses on the ground must have become desensitised towards the plight of the people passing by in front of them: how else to explain the silent acquiescence in the face of the massive deportation unfolding before their eyes?

UN observers did draw some conclusions in October, writing to the Secretary General – who did not publish their report – that Israeli policy was that of ‘uprooting Arabs from their native villages in Palestine by force or threat’.15 Arab member states attempted to bring the report on Palestine to the attention of the Security Council, but to no avail. For almost thirty years the UN uncritically adopted the rhetorical obfuscations of Abba Eban, Israel’s ambassador to the UN, who referred to the refugees as constituting a ‘humane problem’ for which no one could be held accountable or responsible. UN observers were also shocked by the scope of the looting that went on, which by October 1948 had reached every village and town in Palestine. After so overwhelmingly endorsing a partition resolution, almost a year earlier, the UN could have passed another resolution condemning the ethnic cleansing, but it never did. And worse was to come.





## A MINI EMPIRE IN THE MAKING




So successful was Israel during this final phase that dreams re-emerged of creating a mini-empire. The Israeli forces were once again put on the alert to expand the Jewish state into the West Bank and southern Lebanon. The difference with these orders was that the allusions to the West Bank (called Samariyya or the Arab Triangle in those days) were clearer, actually forming the first transparent and official breach of the tacit Israeli–Transjordanian understanding. The order was to try to take the areas around Jenin in the northern part of today’s West Bank and, if they were successful, to proceed to Nablus. Although the attack was postponed, in the months to come the military High Command remained obsessed with the areas the army had not yet occupied, especially the West Bank. We have the names that were given to the different operations Israel had planned to implement there between December 1948 and March 1949, the best known of which was Operation ‘Snir’; when Israel and Jordan finally signed an armistice agreement, they had to be set aside.

These last operations were cancelled because of concerns over the military alliance Britain had with Jordan, which at least officially obliged His Majesty’s government to resist with force an Israeli invasion into Jordanian territory. What the Israeli ministers did not know was that the British government did not regard the West Bank as falling under the terms of this Anglo-Jordanian treaty. Interestingly, Ben-Gurion reports at one point to his government that he had secured French approval for such an operation, but that he was apprehensive of a possible British retaliation.16 As we know, these plans were eventually reactivated in June 1967, when the Israeli government exploited Gamal Abdel Nasser’s brinkmanship policies to wage an attack on the West Bank as a whole.

Ben-Gurion took the discussion of future plans, including the need to occupy Southern Lebanon, to a committee of five (all veterans of the Consultancy) whom he invited to the Israeli army’s new headquarters, called the ‘Hill’. They met several times through October and November, which must have made Ben-Gurion nostalgic about the cabals of earlier days. Ben-Gurion now consulted this five-man body of decision-makers about a future occupation of the West Bank. His comrades brought to the fore another argument against the occupation of the West Bank. In the words of one of the participants, Yitzhak Greenbaum, Israel’s Minister of the Interior: ‘It would be impossible to do there what was done in the rest of Palestine,’ i.e., ethnic cleansing. Greenbaum continued: ‘If we take places such as Nablus, the Jewish world will demand of us to keep it’ [and hence we would have not only Nablus but also the Nabulsians].17 Only in 1967 did Ben-Gurion recognise the difficulties of re-enacting the 1948 mass expulsions in the areas Israel occupied in the June war. Ironically, it may have been he who dissuaded the then Chief of Staff, Yitzhak Rabin, to refrain from such a massive operation, and be content with the deportation of ‘only’ 200,000 people. Consequently, he recommended withdrawing the Israeli army from the West Bank immediately. Rabin, supported by the rest of the government at that time, insisted instead on annexing the territories to Israel.

Plans to seize southern Lebanon were based on intelligence reports that the Lebanese had no offensive, but only defensive plans. Thirteen villages were captured in southern Lebanon, which left the Israelis with a larger number of what they called ‘prisoners of war’ – a mixture of villagers and regular soldiers – than they could handle. Consequently, executions took place here as well. On 31 October 1948, the Jewish forces executed more than eighty villagers in the village of Hula alone, while in the village of Saliha Israeli troops butchered more than 100 people. One person, Shmuel Lahis, later to become Director-General of the Jewish Agency, was brought before a military court at the time for single-handedly executing thirty-five people. Dov Yirmiya, a commander who had himself participated in ethnic cleansing operations between May and July, was one of the few IDF officers who was genuinely appalled when he realised what the operations were leading to. He began protesting vociferously against any atrocities he witnessed or heard about. It was Yirmiya who brought Lahis to trial. Lahis received a seven-year prison term, but was almost immediately pardoned and exonerated by Israel’s president, and subsequently rose to high positions in government.18

When Israel re-invaded Southern Lebanon in 1978, and again in 1982, the POW ‘problem’ was solved: the IDF built a network of prisons to interrogate and quite often torture the people it held captive there, with the help of the South Lebanese Army. The prison at Khiyam has become a byword for Israeli cruelty.

Back in 1948, another pattern appeared, inevitable in the repertoire of an occupying army, which would reoccur in the 1982–2001 occupation, and this was the exploitative and abusive conduct towards the occupied population. A complaint from 14 December 1948 by the commander of the Israeli forces in Lebanon to the High Command notes: ‘The soldiers in southern Lebanon order the villagers to provide and prepare food for them.’19 In the light of the Israeli disposition in later years in the West Bank and the Gaza Strip, one can only imagine this was just the tip of the iceberg of abuse and humiliation. The Israeli forces withdrew from southern Lebanon in April 1949, but, as happened in 1978 and once more in 1982, their occupation had created a lot of bad blood and stirred up feelings of revenge as it extended the practices of the 1948 ethnic cleansing in Palestine to the south of Lebanon.

The whole of the Galilee was now in Jewish hands. The Red Cross was allowed to go in and examine the conditions of the people who had been left, or rather allowed to remain, in the region, as Israel knew that barring the Red Cross from such inspections would stand in the way of its application to become a full member of the UN. The toll of siege, bombardment and expulsion could be seen everywhere. In November 1948 the organisation’s representatives reported a scene of devastation: in every village they visited, the able men had been imprisoned, leaving behind women and children without their traditional breadwinners and creating total disarray; crops were not harvested and were left to rot in the fields, and diseases were spreading in the rural areas at an alarming pace. The Red Cross reported malaria as being the main problem, but also found numerous cases of typhoid, rickets, diphtheria and scurvy.20





## FINAL CLEANSING OF THE SOUTH AND THE EAST




The last front was the southern Negev, which the Israelis reached in November 1948. Driving out the remaining Egyptian forces, they continued south and arrived in March 1949 at a fishing village near the Red Sea, Umm Rashrash, today the city of Eilat.

Yigal Allon, aware that the best brigades were being used for the ethnic cleansing operations in the populated areas, now wished to redirect them to the occupation of the Negev: ‘I need to replace the Negev Brigade with Brigade Harel and I wish to have Brigade Eight. The enemy is strong, fortified and well equipped and will wage stubborn war but we can win.’21

The main worry, however was a British counter-attack, since the Israelis wrongly believed this area was coveted by Britain or that His Majesty’s Government would activate its defense treaty with Egypt, as some of the Israeli forces were about to move into Egyptian territories proper. In the event, the British did neither, although they did clash here and there with the Israeli air force that mercilessly and, perhaps, pointlessly bombarded Rafah, Gaza and El-Arish.22 As a result, the Gazans, refugees and veteran population alike, have had the longest history as victims of Israeli air bombardment – from 1948 until the present.

On the ethnic cleansing front, the final operations in the south provided, unsurprisingly, an opportunity for further depopulation and expulsions. The two southern coastal towns of Isdud and Majdal were taken in November 1948 and their populations expelled to the Gaza Strip. Several thousands of people who had remained in Majdal were expelled in December 1949, shocking some left-wing Israelis as this was done during a ‘time of peace’.23

The month of December 1948 was devoted to cleansing the Negev of many of the Bedouin tribes that resided there. A huge tribe, the Tarabins, was expelled to Gaza; the army only allowed 1,000 of its members to remain. Another tribe, the Tayaha, was split into two: half of them were deported to Gaza and the other half forcibly evicted in the direction of Jordan. The al-Hajajre, whose land straddled the railway line, were pushed into Gaza by December. Only the al-Azazmeh succeeded in returning, but they were driven out again between 1950 and 1954, when they became the favourite target of a special Israeli commando force, Unit 101, led by a young ambitious officer called Ariel Sharon. In December the Israeli units also completed the depopulation of the Bersheba district that they had started in the autumn of 1948. When they had finished, ninety per cent of the people who had lived for centuries in this, the most southern inhabited region of Palestine, were gone.24

In November and December, Israeli troops attacked Wadi Ara again, but the presence of volunteers, Iraqi units and local villagers both deterred and in several cases defeated this plan yet again. Villages that are familiar names to Israelis travelling on the busy Route 65 that connects Afula and Hadera succeeded in protecting themselves against a far superior military force: Mushayrifa, Musmus, Mu‘awiya, Arara, Barta’a, Shuweika and many others. The largest of these villages has grown into the town we know today as Umm al-Fahm. There, with some training from the Iraqi soldiers, the villagers themselves had organised a force that they called the ‘Army of Honour’. This fifth Israeli attempt to occupy these villages was called ‘Hidush Yameinu ke-Kedem’, that is ‘Restoring our Glorious Past’, possibly in the hope that such a charged codename would imbue the attacking forces with particular zeal, but it was destined to fail once again.

Another ominous-sounding name was given to the operation in the Beersheba–Hebron area: ‘Python’. Apart from the small town of Beersheba, which with its 5,000 inhabitants was occupied on 21 October, two large villages, Qubayba and Dawaymeh were taken. Habib Jarada, who today lives in the city of Gaza, remembered the people of Beersheba being driven out at gunpoint to Hebron. His most vivid image is that of the town’s mayor beseeching the occupying officer not to deport the people. ‘We need land, not slaves,’ was the blunt answer.25

The town of Beersheba was protected mainly by Egyptian volunteers from the Muslim Brotherhood’s movement under the command of a Libyan officer, Ramadan al-Sanusi. When the fighting was over, the captive soldiers and all local people the Israeli troops suspected of holding arms were rounded up and randomly fired at. Jarada remembers to this day many of the names of the people killed, which included his cousin Yussuf Jarada and his grandfather Ali Jarada. Jarada was taken to a prison camp and was released only in the summer of 1949 in a prisoner exchange following Israel’s armistice with Jordan.





## THE MASSACRE IN DAWAYMEH




Then there was the village of Dawaymeh, between Beersheba and Hebron. The events that unfolded in Dawaymeh are probably the worst in the annals of Nakba atrocities. The village was occupied by Battalion 89 of Brigade Eight.

The UN’s Palestine Conciliation Commission, mentioned before as replacing Count Bernadotte in the UN mediation efforts, convened a special session to investigate what happened in this village on 28 October 1948, less than three miles west of the city of Hebron. The original population was 2,000, but an additional 4,000 refugees had tripled that.

The UN report from 14 June 1949 (accessible today on the Internet by simply searching for the village name) says the following:

The reason why so little is known about this massacre which, in many respects, was more brutal than the Deir Yassin massacre, is because the Arab Legion (the army in control of that area) feared that if the news was allowed to spread, it would have the same effect on the moral of the peasantry that Deir Yassin had, namely to cause another flow of Arab refugees.





More likely, the Jordanians feared accusations being rightly leveled against them for their impotence and lack of action. The report to the PCC was based mainly on the mukhtar’s testimony. He was Hassan Mahmoud Ihdeib and much of what he says was corroborated by the reports that lie in the Israeli military archives. A well-known Israeli writer, Amos Keinan, who participated in the massacre, confirmed its existence in an interview he gave in the late 1990s to the Palestinian actor and film maker Muhammad Bakri, for Bakri’s documentary ‘1948’.

Half an hour after the midday prayer on 28 October, recalled the mukhtar, twenty armoured cars entered the village from Qubayba while soldiers attacked simultaneously from the opposite flank. The twenty people guarding the village were immediately paralysed with fear. The soldiers on the armoured cars opened fire with automatic weapons and mortars, making their way into the village in a semi-circular movement. Following the established routine, they surrounded the village from three flanks, leaving open the eastern flank with the aim of driving out 6,000 people in one hour. When this failed to happen, the troops jumped out of their vehicles and started shooting at the people indiscriminately, many of whom ran to the mosque to seek shelter or fled to a nearby holy cave, called Iraq al-Zagh. Venturing back into the village the next day, the mukhtar beheld with horror the piles of dead bodies in the mosque – with many more strewn about in the street – men, women and children, among them his own father. When he went to the cave, he found the entrance blocked by dozens of corpses. The count the mukhtar carried out told him that 455 people were missing, among them around 170 children and women.

The Jewish soldiers who took part in the massacre also reported horrific scenes: babies whose skulls were cracked open, women raped or burned alive in houses, and men stabbed to death. These were not reports delivered years later, but eye-witness accounts sent to the High Command within a few days of the event.26 The brutality they describe reinforces my faith in the accuracy of the descriptions, mentioned earlier on, of the hideous crimes Israeli soldiers committed in Tantura, Safsaf and Sa‘sa, all reconstructed mainly with the help of Palestinian testimonies and oral histories.

This was the end result of the order that the commander of Battalion 89 of Brigade Eight had received from the Chief of Staff, Yigael Yadin: ‘Your preparations should include psychological warfare and “treatment” (tipul) of citizens as an integral part of the operation.’27

The massacre at Dawaymeh was the last large massacre Israeli troops perpetrated until 1956, when forty-nine villagers of Kfar Qassim, a village transferred to Israel in the armistice agreement with Jordan, were butchered.

Ethnic cleansing is not genocide, but it does carry with it atrocious acts of mass killing and butchering. Thousands of Palestinians were killed ruthlessly and savagely by Israeli troops of all backgrounds, ranks and ages. None of these Israelis was ever tried for war crimes, in spite of the overwhelming evidence.

And if, here and there, in 1948, some remorse was to be found, as in a poem by Natan Alterman – the same Alterman who had in 1945 compared the Palestinians to the Nazis – it was no more than another show of ‘shoot and cry’, a typically righteous Israeli way of seeking self-absolution. When he first heard of the brutal slaughtering of innocent civilians in the north in Operation Hiram, Alterman wrote:

> On a Jeep he crossed the street<br>A young man, Prince of Beasts<br>An old couple cowered to the wall<br>And with his angelic smile he called:<br>'The submachine I will try', and he did<br>Spreading the old man's blood on the lid.

Nor did any contrition such as Alterman’s stop the forces from completing their mission of cleansing Palestine, a job to which they now applied increasing levels of ruthlessness and cruelty. Hence, starting in November 1948 and all the way up to the final agreement with Syria and Lebanon in the summer of 1949, another eighty-seven villages were occupied; thirty-six of these were emptied by force, while from the rest a selective number of people were deported. As 1950 began, the energy and purposefulness of the expellers finally began to wane and those Palestinians who were still living in Palestine – by then divided into the State of Israel, a Jordanian West Bank and an Egyptian Gaza Strip – were largely safe from further expulsions. True, they were placed under military rule both in Israel and Egypt, and as such remained vulnerable. But, whatever the hardships they incurred, it was a better fate than they had suffered throughout that year of horrors we now call the Nakba.
