# Fortress Israel

> The significance of the disengagement plan [from Gaza] is the freezing of the peace process. And when you freeze that process, you prevent the establishment of a Palestinian state, and you prevent a discussion on the refugees, the borders and Jerusalem. Effectively, this whole package called the Palestinian state, with all that it entails, has been removed indefinitely from our agenda. All with [US] presidential blessings and the ratification of both houses of Congress.

Dov Weissglas, spokesperson for Ariel Sharon, Ha'aretz, 6 October 2004

> So, if we want to remain alive, we have to kill and kill and kill. All day, every day. [...] If we don’t kill, we will cease to exist. [...] Unilateral separation doesn’t guarantee ‘peace’ – it guarantees a Zionist-Jewish state with an overwhelming majority of Jews.

Arnon Soffer, professor of geography at Haifa University, Israel, The Jerusalem Post, 10 May, 2004.

In the dead of night on 24 January 2006, an elite unit of Israel’s border police seized the Israeli Palestinian village of Jaljulya. The troops burst into houses, dragging out thirty-six women and eventually deporting eight of them. The eight women were ordered to go back to their old homes in the West Bank. Some of them had been married for years to Palestinian men from Jaljulya, some were pregnant, many had children. They were abruptly cut off from their husbands and children. One Palestinian member of the Knesset protested, but the action was backed by the government, the courts and the media: the soldiers were demonstrating to the Israeli public that when the presence of the Palestinian minority population threatens to change from a ‘demographic problem’ to a ‘demographic danger’, the Jewish state will act swiftly and without mercy.

The police raid on Jaljulya was entirely ‘legal’: on 31 July 2003, the Knesset passed a law prohibiting Palestinians from obtaining citizenship, permanent residency or even temporary residency when they marry Israeli citizens. In Hebrew ‘Palestinians’ always means Palestinians living in the West Bank, the Gaza Strip and in the diaspora, so as to distinguish them from ‘Israeli Arabs’, as though they are not all part of the same Palestinian nation. The initiator of the legislation was a liberal Zionist, Avraham Poraz, of the centrist party Shinui, who described the bill as a ‘defence measure’. Only twenty-five of the 120 members of the Knesset opposed it and Poraz at the time explained that those ‘Palestinians’ already married ‘to Israeli citizens’ and with families ‘will have to go back to the West Bank’, regardless of how long they had been living in Israel.

The Arab members of the Knesset were among a group of Israelis who appealed to the Israeli Supreme Court against this latest racist law. When the Supreme Court turned the appeal down, their energy petered out.1 The Supreme Court ruling made clear how irrelevant they were in the eyes of both Israel’s parliamentary and judicial systems. It also revealed once again how it prefers to uphold Zionism rather than justice. Israelis enjoy telling Palestinians they should be happy they live in ‘the only democracy’ in the region where they have the right to vote, but no one is under any illusion that voting comes with any actual political power or influence.





## THE 'DEMOGRAPHIC PROBLEM'




The raid on Jaljulya and the law behind it help explain why Israel’s Palestinian minority were at the heart of the recent Israeli elections. From left to right, the platforms of all the Zionist parties during the 2006 election campaign highlighted policies that they claimed would effectively counter the ‘demographic problem’ the Palestinian presence in Israel poses for the state. Ariel Sharon decided the pullout from Gaza was the best solution to it, while the Labour Party endorsed the Segregation Wall as the optimal way of ensuring the number of Palestinians inside Israel remains limited. Extra-parliamentary groups, too – among them the Geneva Accord movement, Peace Now, the Council for Peace and Security, Ami Ayalon’s Census group and the Mizrahi Democratic Rainbow – all had their own favourite recipes for how to tackle the ‘demographic problem’.

Apart from the ten members of the Palestinian parties and two eccentric Ashkenazi ultra-Orthodox Jews, all members of Israel’s new parliament were sent to the Knesset on the strength of the promise that their magic formulae would solve the ‘demographic problem’ once and for all. Strategies varied, from reducing Israeli occupation and control over the Occupied Territories – for most of them Israeli withdrawal would never be from more than fifty per cent of these territories – to more drastic and far-reaching action. For example, right-wing parties such as Yisrael Beytenu, the Russian ethnic party of Avigdor Liberman, and the religious parties openly argue for the ‘voluntary transfer’ – their euphemism for ethnic cleansing – of Palestinians to the West Bank. In other words, the Zionist response seeks to solve the problem of the ‘demographic balance’ either by giving up territory (that Israel holds illegally under international law) or by ‘shrinking’ the ‘problematic’ population group.

None of this is new. Already in the late nineteenth century Zionism had identified the ‘population problem’ as the major obstacle for the fulfillment of its dream. It had also identified the solution: ‘We shall endeavour to expel the poor population across the border unnoticed, procuring employment for it in the transit countries, but denying it any employment in our own country,’ Herzl had written in his diary in 1895.2 And David Ben-Gurion was very clear in December 1947 that ‘there can be no stable and strong Jewish state so long as it has a Jewish majority of only 60 per cent.’3 Israel, he warned on the same occasion, would have to deal with this ‘severe’ problem with ‘a new approach in due course’.

The ethnic cleansing of Palestine Ben-Gurion instigated the following year, his ‘new approach’, ensured that the number of Palestinians was reduced to less than twenty per cent of the overall population in the new Jewish state. In December 2003, Binyamin Netanyahu recycled Ben-Gurion’s ‘alarming’ statistics: ‘If the Arabs in Israel form 40 per cent of the population,’ Netanyahu said, ‘this is the end of the Jewish state.’ ‘But 20 per cent is also a problem,’ he added. ‘If the relationship with these 20 per cent becomes problematic, the state is entitled to employ extreme measures.’4 He did not elaborate.

Twice in its short history Israel has boosted its population with two massive Jewish immigrations, each of about a million people, in 1949 and again in the 1980s. This has kept the percentage of Palestinians down to nearly twenty per cent of Israel’s total population, when we do not include the Occupied Territories. Here lies the crux for today’s politicians. Ehud Olmert, now prime minister, knows that if Israel decides to stay in the Occupied Territories and its inhabitants become officially part of Israel’s population, Palestinians will outnumber Jews within fifteen years. Thus he has opted for what he calls hitkansut, Hebrew for ‘convergence’ or, better, ‘ingathering’, a policy that aims at annexing large parts of the West Bank but at the same time leaves several populous Palestinian areas outside direct Israeli control. In other words, hitkansut is the core of Zionism in a slightly different garb: to take over as much of Palestine as possible with as few Palestinians as possible. This explains the 670-km long serpentine route of the 8m-high concrete slabs, barbed wire and manned watchtowers that make up the Wall, and why it runs more than twice the length of the 315 km long ‘Green Line’ (the June 1967 border). But even if Olmert’s government should succeed and this ‘consolidation’ goes ahead, there will still be a large population of Palestinians inside the eighty-eight per cent of Palestine where Olmert envisages he will build his future, stable Jewish state. How many Palestinian citizens exactly we don’t know: Israeli demographers belonging to the centre or the left provide a low estimate, which makes ‘disengagement’ seem a reasonable solution,5 while those on the right tend to exaggerate the figure. But they all seem to agree that the ‘demographic balance’ will not stay the same, given the higher birth-rate of Palestinians compared with Jews. Thus, at some point soon, Olmert may well come to the conclusion in the end that pull-outs are not the solution.

By now most mainstream journalists, academics and politicians in Israel have liberated themselves from their earlier inhibitions when it comes to talking about the ‘demographic problem’. On the domestic scene, no one feels the need any more to explain what is at the heart of it and who it affects. And abroad, once Israel succeeded, after 9/11, in making the West think of the ‘Arabs’ in Israel and the Palestinians in the Occupied Territories as ‘Muslims’, it found it easy to elicit support for its demographic policies there too, certainly where it counted most: on Capitol Hill. On 2 February 2003 the popular daily Ma‘ariv carried the following headline, typical of the new ‘mood’: ‘A quarter of the children in Israel are Muslims.’ The piece went on to describe this fact as Israel’s next ‘ticking bomb’. The natural increase in the population, no longer Palestinian, but ‘Muslim’ – 2.4% a year – was not portrayed as a problem any more: it had become a ‘danger’.

In the run-up to the 2006 Knesset election, pundits discussed the question of the ‘demographic balance’ using language akin to that employed by majority populations in Europe and the United States in debates over immigration and how to absorb or deter immigrants. In Palestine, however, it is the immigrant community that decides the future of the indigenous people, not the other way round. As we already saw, on 7 February 1948, after driving to Jerusalem from Tel-Aviv and seeing how Jewish troops had already emptied the first Palestinian villages on the western outskirts of Jerusalem of their inhabitants, a jubilant Ben-Gurion reported to a gathering of Zionist leaders how ‘Hebrew’ Jerusalem had become.

But despite Zionist ‘perseverance’, a sizable community of Palestinians survived the ethnic cleansing. Today, their children are students at university where they follow courses by professors of political science or geography who lecture on how severe the problem of ‘demographic balance’ has become for Israel. Palestinian law students – the lucky ones who constitute an informal quota – at the Hebrew University of Jerusalem may well come across Professor Ruth Gabison, a former head of the Association for Civil Rights and a candidate for the Supreme Court, who has come out recently with strong views on the subject, views that she may well think reflect a broad consensus. ‘Israel has the right to control Palestinian natural growth,’ she has declared.6

Away from university campuses, Palestinians can’t escape realising that they are viewed as a problem. From the Zionist left to the extreme right, it is broadcast to them daily that Israel’s Jewish society longs to get rid of them. And they worry, and rightly so, each time they hear that they and their families have become a ‘danger’, because while still only a problem, they may feel protected by the pretence Israel keeps up to the outside world of being a liberal democracy. Once the state officially declares they constitute a danger, however, they know they will be the subject of emergency policies Israel has been happy to keep handy from the time of the British Mandate. Houses could be demolished, newspapers shut down and people expelled under such a regime.

The right of the Palestinian refugees whom Israel expelled in 1948 to return home was acknowledged by the UN General Assembly in December 1948. That right is anchored in international law and is consonant with all notions of universal justice. More surprisingly perhaps, it also makes sense in terms of realpolitik, as shown in Chapter 11: unless Israel acknowledges the cardinal role it has played, and continues to play, in the dispossession of the Palestinian nation, and accepts the consequences this recognition of the ethnic cleansing implies, all attempts to solve the Israel–Palestine conflict are bound to fail, as became clear in 2000 when the Oslo initiative broke down over the Palestinians’ Right of Return.

But then, the aim of the Zionist project has always been to construct and then defend a ‘white’ (Western) fortress in a ‘black’ (Arab) world. At the heart of the refusal to allow Palestinians the Right to Return is the fear of Jewish Israelis that they will eventually be outnumbered by Arabs. The prospect this calls up – that their fortress may be under threat – arouses such strong feelings that Israelis no longer seem to care that their actions might be condemned by the whole world. The principle of maintaining an over-whelming Jewish majority at all costs supersedes all other political and even civil concerns, and the Jewish religious propensity to seek atonement has been replaced by the arrogant disregard for world public opinion and the self-righteousness with which Israel routinely fends off criticism. This position is not unlike that of the medieval Crusaders whose Latin Kingdom of Jerusalem remained for nearly a century a fortified isolated island as they shielded themselves behind the thick walls of their impenetrable castles against integration with their Muslim surroundings, prisoners of their own warped reality. A more recent example of this same kind of siege mentality we find in the white settlers in South Africa during the heyday of Apartheid rule. The aspiration of the Boers to maintain a racially pure, white enclave, like that of the Crusaders in Palestine, held out only for a brief historical moment before it, too, collapsed.

The Zionist enclave in Palestine, as we saw in the opening pages of this book, was constructed around 1922 by a group of Jewish colonialists from Eastern Europe with considerable help and assistance from the British Empire. The political borders the British decided on for Palestine simultaneously enabled the Zionists to define in concrete geographical terms the Eretz Israel they had in mind for their future Jewish state. The colonialists dreamed of massive Jewish immigration to strengthen their hold, but the Holocaust reduced the number of ‘white’, European Jews and, disappointingly from a Zionist point of view, those who had survived the Nazi onslaught preferred either to emigrate to the United States or even to remain in Europe itself, despite the recent horrors. Reluctantly, Israel’s Ashkenazi leadership then decided to prompt one million Arab Jews from the Middle East and North Africa to join them in the enclave they had carved for themselves in the land of Palestine. Here, another discriminatory side of Zionism comes to the fore, perhaps even more poignant for the fact that it was directed against their own co-religionists. This group of Jewish newcomers from the Arab world, Mizrahim,7 was put through an invidious process of de-Arabisation that scholars who are part of the second and third generation of these immigrants (notable among them Ella Shohat, Sami Shalom Shitrit and Yehuda Shenhav) have done much to expose in recent years. From a Zionist point of view, this process of dispossession also eventually proved a success story. Never threatened by the presence of a small Palestinian minority inside Israel, the illusion was maintained that the enclave was well built and rested on solid foundations.

When, in the mid-1960s, it became clear that the Arab world and the nascent Palestinian national movement refused to reconcile themselves with the reality Fortress Israel had created for them, Israel decided to extend its territorial grasp and, in June 1967, conquered the rest of Palestine, along with parts of Syria, Egypt and Jordan. Subsequently, after the Sinai had been ceded back to Egypt in 1979 in return for ‘peace’, in 1982, Israel added southern Lebanon to its mini-empire. An expansionist policy had become necessary to protect the enclave.

The withdrawals in May 2000 from southern Lebanon and, in August 2005, from the Gaza Strip, tell us that the Israeli government has shifted its sights to concentrate on aspects it deems more valuable to keeping the Fortress impenetrable: nuclear capability, unconditional American support, and a strong army. Zionist pragmatism has re-emerged in a policy that will finally define where the enclave’s borders will run. According to international law, no state can set its own borders unilaterally, but this is not a notion likely to penetrate the thick walls of the Fortress. The consensus in contemporary Israel is for a state whose borders include about ninety per cent of Palestine, provided that territory will be surrounded by electric fences and visible as well as invisible walls.

As in 1948, when Ben-Gurion led the Consultancy to ‘reconcile’ themselves with a future state over seventy-eight per cent of Palestine, the problem is no longer how much land to grab, but rather what the future of the indigenous Palestinians who live there will be. In 2006, in the ninety per cent Israel covets there are about 2.5 million Palestinians sharing the state with six million Jews. There are also another 2.5 million Palestinians in the Gaza Strip and in the areas Israel does not want in the West Bank. For most mainstream Israeli politicians and the Jewish public this demographic balance is already a nightmare.

However, Israel’s adamant refusal even to contemplate the possibility of negotiating the right of the Palestinians to come back to their homes, for the sake of maintaining a predominantly Jewish majority – even if this would bring about an end to the conflict – rests on very shaky ground. For almost two decades, the State of Israel has been unable to claim an over-whelming Jewish majority, thanks to the influx in the 1980s of Christians from former Soviet Union countries, the increasing number of foreign guest workers and the fact that secular Jews find it more and more difficult to define what their Jewishness amounts to in the ‘Jewish’ state. These realities are known to the captains of the ship of state, and yet none of this alarms them: their primary goal is to keep the population of the state ‘white’, that is, non-Arab.8

Israeli governments have failed in their attempts both to encourage further Jewish immigration and to increase Jewish birth rates within the state. And they have not found a solution to the conflict in Palestine that would entail a reduction in the number of Arabs in Israel. On the contrary, all the solutions Israel contemplates lead to an increase in the Arab population since they include the Greater Jerusalem area, the Golan Heights and the large settlement blocs in the West Bank. And while Israeli proposals after 1993 for ending the conflict may have met with the approval of some Arab regimes in the region – such as those of Egypt and Jordan, both securely located in the US sphere of influence – they never convinced the civil societies in those countries. Neither does the way the Americans go about ‘democratising’ the Middle East, as currently pursued by US troops in Iraq, make life inside the ‘white’ Fortress any less anxious, as the invasion of Iraq is so closely identified with Israel by the Muslim world. Levels of social violence inside the Fortress are high, and the standard of living of the majority is constantly dropping. None of these concerns is dealt with: they are almost as low on the national agenda as the environment and women’s rights.

Rejecting the Palestinian refugees’ Right of Return is tantamount to making an unconditional pledge to the continuing defence of the ‘white’ enclave and to upholding the Fortress. Apartheid is particularly popular among Mizrahi Jews, who today are the Fortress’ most vociferous supporters, although few of them, especially since they come from North African countries, will find themselves leading the comfortable lives their Ashkenazi counterparts enjoy. And they know this – betraying their Arabic heritage and culture has not brought the reward of full acceptance.

Still, the solution would appear simple: as the last postcolonial European enclave in the Arab world, Israel has no choice but willingly to transform itself one day into a civic and democratic state.

That this is possible we see from the close social relationships that Palestinians and Jews have created between themselves over these long and troubled years and against all odds, both inside and outside Israel. That we can put an end to the conflict in the torn land of Palestine also becomes obvious if we look at those sections of Jewish society in Israel that have chosen to let themselves be shaped by human considerations rather than Zionist social engineering. That peace is within reach we know, above all, from the majority of the Palestinians who have refused to let themselves be de-humanised by decades of brutal Israeli occupation and who, despite years of expulsion and oppression, still hope for reconciliation.

But the window of opportunity will not stay open forever. Israel may still be doomed to remain a country full of anger, its actions and behaviour dictated by racism and religious fanaticism, the features of its people permanently distorted by the quest for retribution. How long can we go on asking, let alone expecting, our Palestinian brothers and sisters to keep the faith with us, and not to succumb totally to the despair and sorrow into which their lives were transformed the year Israel erected its Fortress over their destroyed villages and towns?



