# Endnotes {.unnumbered}

## PREFACE


1. Central Zionist Archives, minutes of the meeting of Jewish Agency Executive, 12 June 1938.



2. While some are convinced it was painted red at the front as a show of solidarity with Socialism.



3. One historian, Meir Pail, claims the orders were sent a week later (Meir Pail, From Hagana to the IDF, p. 307).



4. The documents from the meeting are summarized in the IDF Archives, GHQ/Operations branch, 10 March 1948, File 922/75/595 and in the Hagana Archives, 73/94. The meeting is reported by Israel Galili in the Mapai center meeting, 4 April 1948, which is to be found in the Hagana Archives 80/50/18. The composition of the group and its discussions are the product of a mosaic reconstruction of several documents as will be explained in the next chapters. In chapter four the messages that went out on March 10 and the meetings prior to the finalizing of the plan are also documented. For a similar interpretation of Plan Dalet, which was adopted a few weeks before that meeting, see Uri Ben-Eliezer, The Emergence of Israeli Militarism, 1936–1956, p. 253; he writes: ‘Plan Dalet aimed at cleansing of villages, expulsion of Arabs from mixed towns’. For the dispatch of the orders see also Meir Pail, p. 307 and Gershon Rivlin and Elhanan Oren, The War of Independence: Ben-Gurion’s Diary, vol. 1, p. 147. The orders dispatched can be found in the Hagana Archives 73/94, for each of the units: orders to the brigades to move to Position D – Mazav Dalet– and from the brigade to the Battalions, 16 April 1948.



5. Simcha Flapan, The Birth of Israel: Myths and Realities, p. 93.



6. David Ben-Gurion, in Rebirth and Destiny of Israel noted candidly that: “Until the British left [May 15, 1948] no Jewish settlement, however remote, was entered or seized by the Arabs, while the Haganah ... captured many Arab positions and liberated Tiberia, and Haifa, Jaffa, and Safad ... So on the day of destiny, that part of Palestine where the Haganah could operate was almost clear of Arabs.” Ben-Gurion, Rebirth and Destiny of Israel, p. 530.



7. The Eleven composed what I call in this book the Consultancy – see chapter three. It is possible that other people, apart from this caucus of decision-makers, were present, but as bystanders. As for the senior officers, there were twelve orders sent to twelve Brigades on the ground, see 922/75/595 ibid.



8. Walid Khalidi, Palestine Reborn; Michael Palumbo, The Palestinian Catastrophe: The 1948 Expulsion of a People from their Homeland and Dan Kurzman, Genesis 1948: The First Arab-Israeli War.



9. Avi Shlaim, ‘The Debate about the 1948 War’ in Ilan Pappe (ed.), The Israel/Palestine Question, pp. 171–92.



10. Benny Morris, The Birth of the Palestinian Refugee Problem, 1947–1949.



11. He makes this claim in the Hebrew version of the book published by Am Oved, Tel-Aviv in 1997, p. 179.



12. Morris in the same place talks about 200–300,000 refugees. There were in fact 350,000 if one adds all of the population from the 200 towns and villages that were destroyed by 15 May 1948.



13. Walid Khalidi (ed.), All That Remains: The Palestinian Villages Occupied and Depopulated by Israel in 1948.





## CHAPTER 1




1. State Department, Special Report on ‘Ethnic Cleansing’, 10 May 1999.



2. United Nations, Report Following Security Council Resolution 819, 16 April 1993.



3. Drazen Petrovic, ‘Ethnic Cleansing – An attempt at Methodology’, European Journal of International Law, 5/3 (1994), pp. 342–60.



4. This is actually taken directly from Petrovic, ibid., p. 10, note 4, who himself quotes Andrew Bell-Fialkow’s ‘A Brief History of Ethnic Cleansing’.



5. The most important meetings are described in chapter 4.



6. Ben-Gurion Archives, The Correspondence Section, 1.01.1948–07.01.48, documents 79–81. From Ben-Gurion to Galili and the members of the committee. The document also provides a list of forty Palestinian leaders that have been targeted for assassination by the Hagana forces.



7. Yideot Achronot, 2 February 1992.



8. Ha’aretz, Pundak, 21 May 2004.



9. I will detail how it worked in the following chapters, but the authority to destroy is the order sent on 10 March to the troops, and the specific orders authorizing executions are in IDF Archives, 49/5943 doc. 114, 13 April 1948.



10. See the sources below.



11. Nur Masalha, Expulsion of the Palestinians: The Concept of ‘Transfer’ in Zionist Political Thought, 1882–1948 and The Politics of Denial: Israel and the Palestinian Refugee Problem.



12. Alexander Bein (ed.), The Mozkin Book, p. 164.



13. Baruch Kimmerling, Zionism and Territory: The Socio-Territorial Dimensions of Zionist Politics; Gershon Shafir, Land, Labour and the Origins of the Israel-Palestinian Conflict, 1882–1914 and Uri Ram, ‘The Colonialism Perspective in Israeli Sociology’ in Pappe (ed.), The Israel/Palestine Question, pp. 55–80.



14. Khalidi (ed.) All That Remains, and Samih Farsoun and C. E. Zacharia, Palestine and the Palestinians.





## CHAPTER 2




1. See, for instance, Haim Arlosarov, Articles and Essays, Response to the 1930 Shaw Commission on the concept of strangers in Palestine’s history, Jerusalem 1931.



2. A very good description of this myth can be found in Israel Shahak, Racism de l’état d’Israel, p. 93.



3. Alexander Schölch, Palestine in Transformation, 1856–1882: Studies in Social, Economic and Political Development.



4. Neville Mandel, Arabs and Zionism before World War I, p. 233.



5. Reported in Alharam of the same date.



6. The warning came in a story published by Ishaq Musa al-Husayni, The Memories of a Hen published in Jerusalem, first as a series of articles in the newspaper Filastin, then as a book in 1942.



7. For a general analysis, see Rashid Khalidi, Palestinian Identity: The Construction of Modern National Consciousness, and more specifically see Al-Manar, vol. 3, issue 6, pp. 107–8 and vol. 1, issue 41, p. 810.



8. See Uri Ram in Pappe (ed.), The Israel/Palestine Question and David Lloyd George, The Truth about the Peace Treaties.



9. The most notable of these works is Zeev Sternahal, The Founding Myths of Israel: Nationalism, Socialism, and the Making of the Jewish State.



10. The Balfour Declaration was a letter dated November 2, 1917, from British Foreign Secretary Arthur James Balfour, to Lord Rothschild, a leader of the British Jewish community. The text of the Balfour Declaration, agreed at a Cabinet meeting on October 31, 1917, set out the position of the British Government: ‘His Majesty’s Government view with favour the establishment in Palestine of a national home for the Jewish people, and will use their best endeavours to facilitate the achievement of this object, it being clearly understood that nothing shall be done which may prejudice the civil and religious rights of existing non-Jewish communities in Palestine, or the rights and political status enjoyed by Jews in any other country.’



11. Yehosua Porath, The Emergence of the Palestinian Arab National Movement, 1919–1929.



12. Eliakim Rubinstein, ‘The Treatment of the Arab Question in Palestine in the post-1929 Period’ in Ilan Pappe (ed.), Arabs and Jews in the Mandatory Period –A Fresh View on the Historical Research (Hebrew).



13. On Peel see Charles D. Smith, Palestine and the Arab–Israeli Conflict, pp. 135–7.



14. Barbara Smith, The Roots of Separatism in Palestine: British Economic Policy, 1920–1929.



15. This connection is made by Uri Ben-Eliezer, The Making of Israeli Militarism.



16. John Bierman and Colin Smith, Fire in the Night: Wingate of Burma, Ethiopia and Zion.



17. Hagana Archives, File 0014, 19 June 1938.



18. Ibid.



19. The Bulletin of the Hagana Archives, issues 9–10, (prepared by Shimri Salomon) ‘The Intelligence Service and the Village Files, 1940–1948’ (2005).



20. For a critical survey of the JNF see Uri Davis, Apartheid Israel: Possibilities for the Struggle Within.



21. Kenneth Stein, The Land Question in Palestine, 1917–1939.



22. This correspondence is in the Central Zionist Archives and is used in Benny Morris, Correcting A Mistake, p. 62, notes 12–15.



23. Ibid.



24. Hagana Archives, File 66.8



25. Hagana Archives, Village Files, File 24/9, testimony of Yoeli Optikman, 16 January 2003.



26. Hagana Archives, File 1/080/451, 1 December 1939.



27. Hagana Archives, File 194/7, pp. 1–3, interview given on 19 December 2002.



28. See note 15.



29. Hagana Archives, S25/4131, 105/224 and 105/227 and many others in this series each dealing with a different village.



30. Hillel Cohen, The Shadow Army: Palestinian Collaborators in the Service of Zionism.



31. Interview with Palti Sela in the Hagana Archives, File 205.9, 10 January 1988.



32. See note 27.



33. Hagana Archives, Village Files, 105/255 files from January 1947.



34. IDF Archives, 49/5943/114, orders from 13 April 1948.



35. See note 27.



36. Ibid., File 105.178.



37. Quoted in Harry Sacher, Israel: The Establishment of Israel, p. 217.



38. Smith, Palestine and the Arab–Israeli Conflict, pp. 167–8.



39. Yossef Weitz, My Diary, vol. 2, p. 181, 20 December 1940.



40. Ben-Gurion’s Diary, 12 July 1937, and in New Judea, August– September 1937, p. 220.



41. Shabtai Teveth, Ben-Gurion and the Palestinian Arabs: From Peace to War.



42. Hagana Archives, File 003, 13 December 1938.



43. On British policy see Ilan Pappe, Britain and the Arab–Israeli Conflict, 1948–1951.



44. Interview of Moshe Sluzki with Moshe Sneh, in Gershon Rivlin (ed.), Olive-Leaves and Sword: Documents and Studies of the Hagana, and Ben-Gurion’s Diary, 10 October 1948.



45. See Yoav Gelber, The Emergence of a Jewish Army, pp. 1–73.



46. Michael Bar-Zohar, Ben-Gurion: A Political Biography, vol. 2, pp. 639–66 (Hebrew).



47. See Pappe, Britain and the Arab–Israeli Conflict.



48. Yehuda Sluzki, The Hagana Book, vol. 3, part 3, p. 1942.



49. See chapter four.





## CHAPTER 3




1. Palestine was divided into several administrative districts. In 1947 these were the percentages of Jews in them: Safad 12%; Acre 4%; Tiberias 33%; Baysan 30%; Nazareth 16%; Haifa 47%; Jerusalem 40%; Lyyd 72% (this includes Jaffa, Tel-Aviv and Petah Tikva); Ramla 24% and Beersheba 7.5%.



2. See Ilan Pappe, The Making of the Arab– Israeli Conflict, 1947–1951, pp. 16–46.



3. See United Nations Archives: The UNSCOP Documents, Box 2.



4. Walid Khalidi, ‘Revisiting the UNGA Partition Resolution’, Journal of Palestine Studies, 105 (Autumn 1997), p. 15. For more on UNSCOP and how, prompted by the Zionists, it maneuvered the UN towards the pro-Zionist solution of the partition of Palestine, see Pappe, The Making of the Arab–Israeli Conflict, pp. 16–46.



5. Khalidi, ibid.



6. Ibid.



7. Plenary Meetings of the General Assembly, 126th Meeting, 28 November 1947, UN Official Record, vol. 2, pp. 1390–1400.



8. Flapan, The Birth of Israel, pp. 13–54.



9. See, for example, David Tal, War in Palestine, 1948: Strategy and Diplomacy, pp. 1–145.



10. Bar-Zohar, Ben-Gurion, part II, pp. 660–1.



11. See his speech in the Mapai Centre on 3 December, 1947.



12. Private Archives, Middle East Centre, St. Antony’s College, Cunningham’s Papers, Box 2, File 3.



13. Ibid.



14. For an extensive analysis of the Arab reaction see Eugene L. Rogan and Avi Shlaim (eds.), The War For Palestine: Rewriting the History of 1948; see especially Charles Tripp, ‘Iraq and the 1948 War: Mirror of Iraq’s Disorder’; Fawaz A. Geregs, ‘Egypt and the 1948 War: Internal Conflict and Regional Ambition’ and Joshua Landis, ‘Syria and the Palestine War: Fighting King Abdullah’s “Greater Syria” Plan.



15. Ben-Gurion’s Diary, 7 October, 1947.



16. Only once did Ben-Gurion refer to it by name. In an entry in his diary (1.1.1948) he called it ‘a party of experts’, Mesibat Mumhim. The editors of the published diary added that a party means a meeting of the experts on Arab Affairs. The document of that meeting shows a larger forum that included, in addition to the experts, certain members of the High Command. Indeed when the two groups met together they became what I have called the Consultancy.



17. Ben-Gurion’s Diary refers to the following meetings: 18 June 1947, 1–3 December 1947, 11 December 1947, 18 December 1947, 24 December 1947 (which was reported in his diary on the 25th and dealt with fortifications in the Negev), 1 January 1948, 7 January 1948 (discussion on the future of Jaffa), 9 January 1948, 14 January 1948, 28 January 1948, 9–10 February 1948, 19 February 1948, 25 February 1948, 28 February 1948, 10 March 1948 and 31 March 1948. Pre and post correspondence of all the meetings mentioned in the diary are to be found in the Ben-Gurion Archives, the correspondence section and the private correspondence section. They fill many gaps in the sketchy diary references.



18. Here is a reconstruction of the individuals who were part of the Consultancy: David Ben-Gurion, Yigael Yadin (Head of Operations), Yohanan Ratner (Strategic Adviser to Ben-Gurion), Yigal Allon (Head of the Palmach and Southern Front), Yitzhak Sadeh (Head of Armoured units), Israel Galili (Head of the High Command), Zvi Ayalon (Deputy to Galili and Commander of the Central Front). Others not part of the Matkal, the High Command, were Yossef Weitz (Head of settlement department in the Jewish Agency), Isar Harel (Head of intelligence) and his people: Ezra Danin, Gad Machnes and Yehoshua Palmon. In one or two meetings, Moshe Sharett and Eliahu Sasson were present too, although Ben-Gurion met Sasson almost every Sunday separately with Yaacov Shimoni in Jerusalem, as his diary testifies. Some officers from the field were also alternately called in to join: Dan Even (Commander of the Coastal Front), Moshe Dayan, Shimon Avidan, Moshe Carmel (Commander of the Northern Front), Shlomo Shamir and Yitzhak Rabin.



19. The meeting is also reported in his book When Israel Fought, pp. 13–18.





## CHAPTER 4




1. We have testimony from the British High Commissioner in Palestine, Sir Alan Cunningham, about how this protest, initially a strike, turned violent: ‘The initial Arab outbreaks were spontaneous and unorganized and were more demonstrations of displeasure at the UN decision than determined attacks on Jews. The weapons initially employed were sticks and stones and had it not been for Jewish recourse to firearms, it is not impossible that the excitement would have subsided and little loss of life been caused. This is more probably since there is reliable evidence that the Arab Higher Committee as a whole and the Mufti in particular, although pleased at the strong response to the strike call, were not in favour of serious outbreaks’; quoted in Nathan Krystal, ‘The Fall of the New City, 1947–1950,’ in Salim Tamari, Jersualem 1948. The Arab Neighbourhoods and their Fate in the War, p. 96.



2. This is discussed in detail in the next chapter.



3. Bar-Zohar, Ben-Gurion, p. 663.



4. Meir Pail, ‘External and Internal Features in the Israeli War of Independence’ in Alon Kadish (ed.), Israel’s War of Independence 1948–1949, pp. 485–7.



5. Smith, Palestine and the Arab–Israeli Conflict, pp. 91–108.



6. Avi Shlaim, Collusion.



7. Avi Shlaim, ‘The Debate about 1948’ in Pappe (ed.), The Israel/Palestine Question, pp. 171–92.



8. Rivlin and Oren, The War of Independence, vol. 1, p. 320, 18 March 1948; p. 397, 7 May 1948; vol. 2, p. 428, 15 May 1948.



9. Ibid., 28 January 1948, p. 187.



10. This included an arms deal worth $12,280,000, which the Hagana concluded with Czechoslovakia, purchasing 24,500 rifles, 5,200 machine guns and 54 million rounds of ammunition.



11. See note 8.



12. The order to the Intelligence Officers will be mentioned again. It can be found in the IDF Archives, File 2315/50/53, 11 January, 1948.y t



13. As can be seen from his letters to Ben-Artzi quoted in Bar-Zohar, Ben-Gurion, p. 663 and to Sharett in Ben-Gurion Archives, Correspondence Section, 23.02–1.03.48 document 59, 26 February 1948.



14. Ben-Gurion’s letters, ibid.



15. Israeli State Archives Publications, Political and Diplomatic Documents of the Zionist Central Archives and Israeli State Archives, December 1947–May 1948, Jerusalem 1979 (Hebrew), Doc. 45, 14 December 47, p. 60.



16. Masalha, Expulsion of the Palestinians.



17. Bar-Zohar, Ben-Gurion, p. 702.



18. On 12 July, 1937, there is a long entry in Ben-Gurion’s Diary in which he expresses the wish that the Jewish leadership would have the will and the power to transfer the Arabs from Palestine.



19. The whole speech was published in his book, David Ben-Gurion, In the Battle, pp. 255–72.



20. Central Zionist Archives, 45/1 Protocol, 2 November 1947.



21. Flapan, The Birth of Israel, p. 87.



22. Morris, The Birth of the Palestinian Refugee Problem Revisited.



23. That this was disconnected was reported to Ben-Gurion. See Ben-Gurion Archives, Correspondence Section, 1.12.47–15.12.47, Doc. 7, Eizenberg to Kaplan, 2 December 1947.



24. Ben-Gurion’s Diary reports one such meeting on 2 December 1947 when the Orientalists suggested attacking water supplies and transport centres of the Palestinians.



25. See Ben-Gurion’s Diary, 11 December 1947; for the assessment that most peasants did not wish to be involved in a war.



26. Hagana Archives, 205.9.



27. This meeting was reported in Ben-Gurion’s Diary a day later, on 11 December 1947; it may have taken place in a more limited forum.



28. IDF Archives, 49/5492/9, 19 January 1948.



29. See the website www.palestineremembered.com– an interactive site that invites oral history testimonies.



30. Ben-Gurion’s Diary, 11 December 1947, and the letter to Moshe Sharett, are from G. Yogev, Documents, December 1947–May 1948, Jerusalem: Israel State Archives 1980, p. 60.



31. Reported in The New York Times, 22 December 1947. The Hagana report was sent to Yigael Yadin, on December 14; see the Hagana Archives, 15/80/731.



32. IDF Archives, 51/957, File 16.



33. Central Zionist Archives, Report S25/3569, Danin to Sasson, 23 December 1947.



34. The New York Times, 20 December 1947, and speech by Ben-Gurion in the Zionist Executive, 6 April 1948.



35. Ben-Gurion summarized the wednesday meeting in his Diary, 18 December 1947.



36. Yaacov Markiviski, ‘The Campaign on Haifa in the Independence War’ in Yossi Ben-Artzi (ed.), The Development of Haifa, 1918–1948.



37. Filastin, 31 December 1947.



38. Milstein, The History of the Independence War, vol. 2, p. 78.



39. Benny Morris, The Birth of the Palestinian Refugee Problem, p. 156 and Uri Milstein, The History of the Independence War, vol. 2, p. 156.



40. National committees were bodies of local notables that were established in various localities throughout Palestine in 1937, to act as a form of emergency leadership for the Palestinian community in each city.



41. Morris, The Birth of the Palestinian Refugee Problem, p. 50 and Milstein, The History of the Independence War, vol. 3, pp. 74–5.



42. Morris, The Birth of the Palestinian Refugee Problem, p. 55, note 11.



43. Political and Diplomatic Documents, Document 274, p. 460.



44. Ibid., Document 245, p. 410.



45. Rivlin and Oren, The War of Independence, editorial remark, p. 9.



46. The text of the Protocol for the Long Seminar is in Ha-Kibbutz Ha-Meuchad Archives, Aharon Zisling’s private collection.



47. Ben-Gurion’s Diary, 31 December 1947.



48. Weitz, My Diary, vol. 2, p. 181.



49. Morris, The Birth of the Palestinian Refugee Problem, p. 62.



50. Ben-Gurion Archives, The Galili papers, Protocol of the meeting.



51. Danin testimony for Bar-Zohar, p. 680, note 60.



52. Ben-Gurion Archives, Correspondence Section, 16.1.48–22.1.48, Document 42, 26 January 1948.



53. Ben-Gurion’s Diary, 7 January 1948.



54. Ben-Gurion’s Diary, 25 January 1948.



55. Rivlin and Oren, The War of Independence, p. 229, 10 February 1948.



56. Ben-Gurion Archives, Correspondence Section, 1.1.48–31.1.48, Doc. 101, 26 January 1948.



57. These were Yohanan Ratner, Yaacov Dori, Israeli Galili, Yigael Yadin, Zvi Leschiner (Ayalon) and Yitzhak Sadeh.



58. Ben-Gurion’s Diary, 9 January 1948.



59. This appeared in their publication Mivrak.



60. Ben-Gurion’s Diary, 31 January 1948.



61. Rivlin and Oren, The War of Independence, pp. 210–11.



62. Ben-Gurion’s Diary, 1 January 1948.



63. See note 52.



64. Bar-Zohar, Ben-Gurion, p. 681.



65. Ben-Gurion’s Diary, 30 January 1948.



66. Ibid., 14 January 1948, 2 February 1948, and 1 June 1948.



67. Information on the meetings in February is drawn from Ben-Gurion’s Diary.



68. Ben-Gurion’s Diary, 9 and 10 February 1948 and Haganah Book, pp. 1416–18.



69. Hashomer Ha-Tza‘ir Archives, Files 66.10, meeting with Galili 5 February 1948 (reporting a day after the Matkal meeting on 4 February Wed.).



70. Zvi Sinai and Gershon Rivlin (eds), The Alexandroni Brigade in the War of Independence, p. 220 (Hebrew).



71. Morris, The Birth of the Palestinian Refugee Problem, pp. 53–4.



72. Weitz, My Diary, vol. 3, p. 223, 11 January 1948.



73. The figures listed in the official report were more modest, detailing the blowing up of forty houses, the killing of eleven villagers, and the wounding of another eighty.



74. Israel Even Nur (ed.), The Yiftach-Palmach Story.



75. Ben-Gurion’s Diary, 19 February 1948.



76. Ibid.



77. Khalidi (ed.), All That Remains, pp. 181–2.



78. Weitz, My Diary, vol. 3, p. 223, 11 January 1947.



79. Ibid, 239–40.



80. Morris, The Birth of the Palestinian Refugee Problem, pp. 84–86.



81. Pail, From the Hagana to the IDF, p. 307. See discussion of State D, next chapter.



82. The English translation is in Walid Khalidi, ‘Plan Dalet: Master Plan for the Conquest of Palestine’, Journal of Palestine Studies, 18/69 (Autumn 1988), pp. 4–20.



83. See chapter five.



84. The Plan distributed to the soldiers and the first direct commands are in IDF Archives, 1950/2315 File 47, 11 May 1948.



85. Yadin to Sasson IDF Archives, 16/69/261 The Nachshon Operations Files.





## CHAPTER 5




1. Rivlin and Oren, The War of Independence, vol. 1, p. 332.



2. Speech to the Executive Committee of the Mapai party, 6 April 1948.



3. Quoted directly from the orders to the Carmeli Brigade, Zvi Sinai (ed.), The Carmeli Brigade in the War of Independence, p. 29.



4. Binyamin Etzioni (ed.), The Golani Brigade in the Fighting, p. 10.



5. Zerubavel Gilad, The Palmach Book, vol. 2, pp. 924–5. Daniel McGowan and Matthew C. Hogan, The Saga of the Deir Yassin Massacre, Revisionism and Reality.



6. The descriptions and testimonies about what happened in Deir Yassin are taken from Daniel McGowan and Matthew C. Hogan, The Saga of the Deir Yassin Massacre, Revisionism and Reality.



7. Ibid.



8. Contemporary accounts put the number of victims of the Deir Yassin massacre at 254, a figure endorsed at the time by the Jewish Agency, a Red Cross official, The New York Times, and Dr Hussein al-Khalidi, spokesperson for the Jerusalem-based Arab Higher Committee. It is likely this figure was deliberately inflated in order to sow fear among the Palestinians and thereby panic them into a mass exodus. Certainly, loudspeakers were later used in villages about to be cleansed to warn the people of the terrible consequences if they did not leave voluntarily, to generate panic and encourage them to flee for their lives before the ground troops moved in. Menachem Begin, the leader of the Irgun, described the effect the spreading of such rumours had on the Palestinians in The Revolt, ‘Arabs throughout the country, induced to believe wild tales of “Irgun butchery” were seized with limitless panic and started to flee for their lives. This mass flight soon developed into a maddened, uncontrolled stampede. Of the almost 800,000 who lived on the present territory of the State of Israel, only some 165,000 are still there. The political and economic significance of this development can hardly be overestimated.’ Begin, The Revolt, p. 164. Albert Einstein, along with 27 prominent Jews in New York, condemned the massacre of Deir Yassin in a letter published 4 December 1948 in The New York Times, noting ‘terrorist bands [i.e. Begin’s Irgun] attacked this peaceful village, which was not a military objective in the fighting, killed most of its inhabitants – 240 men, women, and children – and kept a few of them alive to parade as captives through the streets of Jerusalem. Most of the Jewish community was horrified at the deed, and the Jewish Agency sent a telegram of apology to King Abdullah of Transjordan (sic). But the terrorists, far from being ashamed of their act, were proud of this massacre, publicized it widely, and invited all the foreign correspondents present in the country to view the heaped corpses and the general havoc at Deir Yassin.’



9. Uri Ben-Ari, Follow Me.



10. Of particular interest is the way Geula Cohen, today an extreme rightwing activist, and a leading member of the Stern Gang, saved Abu-Ghawsh, because a member of the villages helped her escape the British prison in 1946. See her story in Geula Cohen, Woman of Violence; Memories of a Young Terrorist, 1945–1948.



11. Filastin, 14 April 1948.



12. Palumbo, The Palestinian Catastrophe, pp. 107–8.



13. Ibid., p. 107.



14. See a summary in Flapan, The Birth of Israel, pp. 89–92.



15. This telegraph was intercepted by the Israeli intelligence and is quoted in Ben-Gurion’s Diary, 12 January 1948.



16. See Rees Williams, the Under Secretary of States statement to Parliament, Hansard, House of Commons Debates, vol. 461, p. 2050, 24 February 1950.



17. Arnan Azariahu, who was Israel Galili’s assistant, recalled that when the new Matkal was moved to Ramat Gan, Yigael Yadin demanded that the Qiryati people not be put in charge of protecting the site. Maqor Rishon, interview, 21 May 2006.



18. Walid Khalidi, ‘Selected Documents on the 1948 War’, Journal of Palestine Studies, 107, Vol. 27/3 (Spring 1998), pp. 60–105, uses the British as well as the Arab committee’s correspondence.



19. Hagana Archives, 69/72, 22 April 1948.



20. Central Zionist Archives, 45/2 Protocol.



21. Zadok Eshel (ed.), The Carmeli Brigade in the War of Independence, p. 147



22. Walid Khalidi, ‘Selected Documents on the 1948 War’.



23. Montgomery of Alamein, Memoirs, pp. 4534.



24. Walid Khalidi, ‘The Fall of Haifa’, Middle East Forum, XXXV, 10 (December 1959), letter by Khayat, Saad, Mu’ammar and Koussa from 21 April 1948.



25. The information on the Palestinian side is taken from Mustafa Abasi, Safad During the British Mandate Period: A Social and Political Study, Jerusalem: Institute for Palestine Studies, 2005 (Arabic); a version of it appeared as ‘The Battle for Safad in the War of 1948: A Revised Study, International Journal for Middle East Studies, 36 (2004), pp. 21–47.



26. Ibid.



27. Ibid.



28. Ben-Gurion’s Diary, 7 June 1948.



29. Salim Tamari, Jerusalem 1948.



30. The reconstruction of the orders was done by Itzhak Levy, the head of the Hagana intelligence in Jerusalem in 1948, in his book Jerusalem in the War of Independence, p. 207 (these interviews were later incorporated into the IDF archives).



31. Fourteen of these telegrams are quoted by Ben-Gurion in his diary, see Rivlin and Oren, The War of Independence, pp. 12, 14, 27, 63, 64, 112, 113, 134, 141, 156, 169, 170, 283.



32. Mentioned in Ben-Gurion’s Diary, 15 January 1948.



33. Levy, Jerusalem, p. 219.



34. Red Cross Archives, Geneva, Files G59/1/GC, G3/82 sent by the international Committee of the Red Cross (ICRC) delegate de Meuron on 6–19 May 1948 describe a sudden typhoid epidemic.



35. All the information is based on the Red Cross sources and on Salman Abu Sitta, ‘Israel Biological and Chemical Weapons: Past and Present’, Between the Lines, 15–19 March 2003. Abu Sitta also quotes Sara Leibovitz-Dar’s article in Hadahsot, 13 August 1993, where she traces, from a clue from the historian Uri Milstein, ‘those who were responsible for the Acre operation, but who refused to answer her questions. She concluded her article by saying: ‘What was done then with deep conviction and zealotry is now concealed with shame’.



36. Ben-Gurion’s Diary, 27 May 1948.



37. Ibid., 31 January 1948 and his notes on the history of HEMED.



38. Levy, Jerusalem, p. 113, although he does accuse the Legion of joining earlier in attacks on those who had already surrendered. See pp. 109–12.



39. Interview with Sela (see chapter 2, note 31).



40. Evidence given by Hanna Abuied, on the website www.palestineremembered.com.



41. Morris, The Birth of the Palestinian Refugee Problem, p. 118.



42. Morris in the Hebrew version refers to the meeting on p. 95, Ben-Gurion mentions it in his Diary.



43. Most of these operations are mentioned in Morris, ibid., pp. 137–67.



44. The most detailed information on numbers, methods and maps are in Salman Abu Sitta’s Atlas of the Nakbah.



45. Interview with Sela, (see chapter 2, note 31).



46. The information taken from Khalidi (ed.), All That Remains, pp. 60–1 and, the Hagana’s Village Files, and Ben-Zion Dinur et al., The History of the Hagana, p. 1420.



47. Ha-Kibbutz Ha-Meuchad Archives, Aharon Zisling Archives, Ben-Gurion letters.



48. Almost every expulsion and destruction of the villages was described in The New York Times, which is our main source, together with Khalidi (ed.), All That Remains, Morris, The Birth of the Palestinian Refugee Problem, and Ben-Zion Dinur et al., The History of the Hagana.



49. Morris, ibid., pp. 243–4.



50. Palmach Archives, Givat Haviva, G/146, 19 April 1948.



51. Nafez Nazzal, The Palestinian Exodus from the Galilee 1948, Beirut: the Institute for Palestinian Studies, 1978, pp. 30–3 and Morris, The Birth of the Palestinian Refugee Problem Revisited, p. 130.



52. Khalidi uses this source very extensively in All That Remains.



53. This provided the main sources for Morris, The Birth of the Palestinian Refugee Problem Revisited.



54. Weitz, My Diary, vol. 3, 21 April 1948.



55. See the orders in IDF Archives, 51/967 particularly in Files 16, 24 and 42, and 51/128/50



56. Ben-Gurion Archives, Correspondence Section, 23.02–30.1 doc. 113.



57. Nazzal, The Palestinian Exodus, p. 29.



58. Netiva Ben-Yehuda, Between the Knots.



59. For a review on the film, see Al-Ahram Weekly, 725, 13–19 January 2005.



60. See the synthesis of the available sources in Khalidi (ed.), All That Remains, p. 437.



61. Hans Lebrecht, The Palestinians, History and Present, pp. 176–7.



62. This is an openly available publication, The Palmach Book, vol. 2, p. 304.



63. Ben-Yehuda, Between the Knots, pp. 245–6.



64. The Palmach Book.



65. Interview with Sela (see chapter 2, note 31).



66. Ibid.



67. Ibid.



68. Ibid.



69. Laila Parsons, ‘The Druze and the Birth of Israel’ in Eugene Rogan and Avi Shlaim (eds), The War for Palestine: Rewriting the History of 1948.



70. Ben-Gurion Archives, Correspondence, 23.02–1.03.48, doc. 70.



71. See the discussion in the Arab League in Pappe, The Making of the Arab–Israeli Conflict, pp. 102–34.



72. Walid Khalidi, ‘The Arab Perspective’ in W. Roger Louis and Robert S. Stookey (eds), The End of the Palestine Mandate.



73. Pappe, The Making of the Arab–Israeli Conflict.



74. Qasimya Khairiya, Fawzi al-Qawuqji’s Memoirs, 1936–1948



75. See Shlaim, Collusion.



76. Ben-Gurion’s Diary, 2 May 1948.



77. As much was also conveyed by the Hagana senior officers in a meeting on 8 May 1948 and to Golda Meir by King Abdullah, on May 10. Meir did report to the Zionist leadership that Abdullah would not sign a treaty with the Jews and would have to go to war. But Moshe Dayan affirmed in 1975 what the British suspected, that in fact he promised that the Iraqi and Jordanian troops would invade the Jewish state. See Dayan in Yeidot Acharonot, 28 February 1975 and see Rivlin and Oren, The War of Independence, pp. 409–10 about the 8 May meetings.



78. PRO, FO 800,477, FS 46/7 13 May 1948.



79. Nimr Hawari wrote a war memoir called The Secret of the Nakba, which he published in Nazareth in Arabic in 1955.



80. Quoted in Flapan, The Birth of Israel, p. 157.



81. Recently there was an interesting debate between Israeli historians on Ben-Gurion’s position. See Ha’aretz, 12 and 14 May 2006 ‘The Big Wednesday’.



82. Wahid al-Daly, The Secrets of the Arab League and Abd al-Rahman Azzam.



83. In front of the Joint Parliamentary Middle East Councils, Commission of Enquiry – Palestinian Refugees, London: Labour Middle East Council and others, 2001.





## CHAPTER 6




1. Levy, Jerusalem, criticized the decision to try and defend these enclaves as a strategic mistake which did not serve the overall strategy; Levy, Jerusalem, p. 114.



2. Yehuda Sluzky, Summary of the Hagana Book, pp. 486–7.



3. For all meetings I quote from Ben-Gurion’s Diary.



4. Interview with Glubb, and see Glubb, A Soldier with the Arabs, p. 82.



5. Ben-Gurion’s Diary, 2 June 1948.



6. Amitzur Ilan, The Origins of the Arab–Israeli Arms Race: Arms, Embargo, Military Power and Decision in the 1948 Palestine War.



7. IDF Archives, 51/665, File 1, May 1948.



8. Pail, ‘External’.



9. In fact some of the books we have mentioned, notably Khalidi (ed.), All That Remains, Flapan, The Birth of Israel, Palumbo, The Catastrophe and Morris, Revisited prove this point very convincingly.



10. The orders can be found in the IDF archives, 51/957, File 16, 7 April 1948, and see 49/4858, File 495 to 15 October 1948 [hence IDF Archives, orders].



11. See Maqor Rishon. The reason quoted was direct hits on the Red House and Ben-Gurion’s flat by Egyptian airplanes.



12. IDF Archives, 1951/957, File 24, 28 January 1948 to 7 July 1948.



13. Ibid.



14. See Ilan Pappe, ‘The Tantura Case in Israel: The Katz Research and Trial’, Journal of Palestine Studies, 30(3), Spring 2001, pp. 19–39.



15. Based on Pappe, ibid., p. 3 and also Pappe, ‘Historical Truth, Modern Historiography, and Ethical Obligations: The Challenge of the Tantura Case,’ Holy Land Studies, vol. 3/2 November 2004.



16. Nimr al-Khatib, Palestine’s Nakbah, p. 116.



17. Sinai and Rivlin, The Alexandroni Brigade.



18. IDF Archives, 49/6127, File 117, 13 April to 27 September 1948.



19. Ibid.



20. Hagana Archives, 8/27/domestic, 1 June 1948.



21. See note 8.



22. Report to Yadin, 11 May 1948 in Hagana Archives, 25/97.



23. Eshel (ed.), The Carmeli Brigade in the War of Independence, p. 172.



24. Posted on www.palestineremembered.com, 1 July 2000.



25. Ben-Gurion’s Diary, 24 May 1948.





## CHAPTER 7




1. Morris, The Birth of the Palestinian Refugee Problem, p. 128.



2. Four such villages – Beit Tima, Huj, Biriyya, and Simsim – are reported in Ben-Gurion’s Diary, 1 June 1948; the Israeli State Archives report setting fire to villages, in 2564/9 from August 1948.



3. As reported in his diary.



4. Ben-Gurion’s Diary, 2 June 1948.



5. Ibid.



6. Naji Makhul, Acre and its Villages since Ancient Times, p. 28.



7. Interview by Teddy Katz with Tuvia Lishanski, see Pappe, Tantura.



8. The recollections of eyewitnesses were presented in Salman Natur, Anta al-Qatil, ya-Shaykh, 1976 (no publishing house); Michael Palumbo, who scrutinized the UN archives, reports that the UN was aware of Israel’s method of summary execution, The Palestinian Catastrophe, pp. 163–74.



9. IDF Archives, 49/5205/58n, 1 June 1948



10. Israeli State Archives, 2750/11 a report of the intelligence officer to Ezra Danin, 29 July 1948.



11. IDF Archives, 49/6127, File 117, 3 June 1948.



12. Israeli State Archives, 2566/15, various reports by Shimoni.



13. Orders, for instance, to the Carmeli Brigade in the Hagana Archives, 100/29/B.



14. See oral history evidence on the website www.palestineremembered.com.



15. Morris, The Birth of the Palestinian Refugee Problem, pp. 198–9.



16. Ben-Gurion’s Diary, 16 July 1948.



17. IDF Archives, 49/6127, File 516.



18. Report by the Intelligence Officer of the Northern Front to the HQ, 1 August 1948 in IDF Archives, 1851/957, File 16.



19. The New York Times, 26 and 27 July 1948.



20. Khalidi (ed.), All That Remains p. 148.



21. Lydda in The Encyclopedia of Palestine.



22. Dan Kurzman, Soldier of Peace, pp. 140–1.



23. Ben-Gurion’s Diary, 11, 16 and 17 July 1948 (this was a real obsession).



24. Ibid., 11 July 1948.



25. Ben-Gurion’s Diary, 18 July 1948.



26. Ibid.



27. Interview with Sela (see chapter 2, note 31).



28. Nazzal, The Palestine Exodus, pp. 83–5.



29. IDF Archives, 49/6127, File 516.



30. A detailed description of the expulsion of the Bedouin can be found in Nur Masalha, A Land Without a People: Israel, Transfer and the Palestinians.



31. IDF Archives, File 572/4, a report from 7 August 1948.



32. Ibid. 51/937, Box 5, File 42, 21 August 1948.



33. Ibid.



34. IDF Archives, 549/715, File 9.



35. Ibid. 51/957, File 42, Operation Alef Ayn, 19 June 1948.





## CHAPTER 8




1. Morris, The Birth of the Palestinian Refugee Problem, pp. 305–6.



2. Detailed information on the current location of refugees and their original villages may be found in Salman Abu Sitta’s Atlas of Palestine 1948.



3. Nazzal, The Palestinian Exodus, pp. 95–6 and Morris, The Birth of the Palestinian Refugee Problem, pp. 230–1 and Khalidi, (ed.), All That Remains, p. 497.



4. The oral history evidence was posted on www.palestineremembered.com by Mohammad Abdallah Edghaim on 25 April, 2001, and the archival evidence can be found in the Hashomer Ha-Tza‘ir Archives, Aharon Cohen, private collection, a memo from 11 November, 1948.



5. Appears in the testimony of Edghaim, who interviewed Salim and Shehadeh Shraydeh.



6. Morris, The Birth of the Palestinian Refugee Problem, pp. 194–5.



7. Iqrit has an official website with a succinct report about the events: www.iqrit.org



8. Daud Bader (ed.), Al-Ghabsiyya; Always in our Heart, Center of the Defence of the Displaced Persons’ Right, May 2002 (Nazareth, in Arabic).



9. IDF Archives, 51/957, File 1683, Battalion 103, company C.



10. Ibid. 50/2433, File 7.



11. Ibid. 51/957, File 28/4.



12. Ibid. 51/1957, File 20/4, 11 November 1948.



13. Morris, The Birth of the Palestinian Refugee Problem, p. 182.



14. IDF Archives, 51/957, File 42, Hiram Operative Commands and 49/715, File 9.



15. United Nation Archives, 13/3.3.1 Box 11, Atrocities September–November.



16. IDF Archives, The Committee of Five Meetings, 11 November 1948.



17. Ibid.



18. Ha-Olam ha-Ze, 1 March 1978 and testimony of Dov Yirmiya, the Israeli commander on the spot, published in Journal of Palestine Studies, vol. 7/4 (Summer 1978), no. 28, pp. 143–5. Yirmiya does not mention numbers, but the Lebanese website of the association of these villages does; see Issah Nakhleh, The Encyclopedia of the Palestine Problem, Chapter 15.



19. IDF Archives, 50/121, File 226, 14 December 1948.



20. Michael Palumbo, Catastrophe, pp. 173–4.



21. Hagana Archives, 69/95, Doc. 2230, 7 October 1948.



22. IDF Archives, 51/957, File 42, 24 March 1948 to 12 March 1949.



23. The New York Times, 19 October 1948.



24. ‘Between Hope and Fear: Bedouin of the Negev’, Refugees International’s report 10 February, 2003 and Nakhleh, ibid., Chapter 11, parts 2–7.



25. Habib Jarada was interviewed in Gaza by Yasser al-Banna and was published in Islam On Line on15 May 2002.



26. All mentioned by Morris, The Birth of the Palestinian Refugee Problem, pp. 222–3.



27. A range of strategies that could only be described as psychological warfare was used by the Jewish forces to terrorize and demoralize the Arab population in a deliberate attempt to provoke a mass exodus. Radio broadcasts in Arabic warned of traitors in the Arabs’ midst, describing the Palestinians as having been deserted by their leaders, and accusing Arab militias of committing crimes against Arab civilians. They also spread fears of disease. Another, less subtle, tactic involved the use of loudspeaker trucks. These would be used in the villages and towns to urge the Palestinians to flee before they were all killed, to warn that the Jews were using poison gas and atomic weapons, or to play recorded ‘horror sounds’ – shrieking and moaning, the wail of sirens, and the clang of fire-alarm bells. See Erskine Childers, ‘The Wordless Wish: From Citizens to Refugees’, in Ibrahim Abu-Lughod (ed.), The Transformation of Palestine, pp. 186–8, and Palumbo, The Palestinian Catastrophe: The 1948 Expulsion of a People from Their Homeland, pp. 61–2, 64, 97–8).





## CHAPTER 9




1. IDF Archives, 50/2433, File 7, Minorities Unit, Report no. 10, 25 February 1949.



2. The order was already given in one form in January 1948. IDF Archives, 50/2315, File 35, 11 January 1948.



3. IDF Archives, 50/2433, File 7, Operation Comb, undated.



4. IDF Archives, 50/121, File 226, Orders to the Military Governors, 16 November 1948.



5. Ben-Gurion’s Diary, 17 November, vol. 3, p. 829.



6. IDF Archives, 51/957, File 42, report to HQ, 29 June 1948.



7. IDF Archives, 50/2315 File 35, 11 January 1948; emphasis added.



8. See Aharon Klien, ‘The Arab POWs in the War of Independence’ in Alon Kadish (ed.), Israel’s War of Independence 1948–9, pp. 573–4.



9. IDF Archives, 54/410, File 107, 4 April 1948.



10. I wish to thank Salman Abu Sitta for providing me with the Red Cross Documents: G59/I/GG 6 February 1949.



11. Al-Khatib, Palestine’s Nakbah, p. 116.



12. Ibid.



13. See note 10.



14. See note 4.



15. It appears also in Yossef Ulizki, From Events to A War, p. 53.



16. Palumbo, The Palestinian Catastrophe, p. 108.



17. See note 4.



18. Dan Yahav, Purity of Arms: Ethos, Myth and Reality, 1936–1956, p. 226.



19. See note 15.



20. See note 4.



21. Ibid.



22. Interview with Abu Laben, in Dan Yahav, Purity of Arms: Ethos, Myth and Reality, 1936–1954, Tel-Aviv: Tamuz 2002, pp. 223–30



23. Ben-Gurion’s Diary, 25 June 1948.



24. The protocol of the meeting was published in full by Tom Segev in his book, 1949 –The First Israelis, and can be found in the State Archives.



25. For the full transcript of the meeting, see Tom Segev, 1949–The First Israelis, Jerusalem Domino, 1984, pp. 69–73.



26. Ibid.



27. Ibid.



28. Ibid.



29. Ibid.



30. See Ben-Gurion’s Diary, 5 July 1948.



31. IDF Archives, 50/121, File 226, report by Menahem Ben-Yossef, Platoon commander, Battalion 102, 26 December 1948.



32. Ben-Gurion’s Diary, 5 July 1948.



33. Ibid., 15 July 1948.



34. Pappe, ‘Tantura’.



35. Ben-Gurion, As Israel Fights, pp. 68–9.



36. Ben-Gurion’s Diary, 18 August 1948.



37. Ibid.



38. David Kretzmer, The Legal Status of Arabs in Israel.



39. Tamir Goren, From Independence to Integration: The Israeli Authority and the Arabs of Haifa, 1948–1950, p. 337, and Ben-Gurion’s Diary, 30 June 1948.



40. Ben-Gurion’s Diary, 16 June 1948.



41. All the information in this section is based on an article by Nael Nakhle in Al-Awda, 14 September 2005 (published in Arabic in London).



42. Benvenisti, Sacred Landscape, p. 298.



43. Weitz, My Diary, vol. 3, p. 294, 30 May 1948.



44. Hussein Abu Hussein and Fiona Makay, Access Denied: Palestinian Access to Land in Israel.



45. Ha’aretz, 4 February 2005.





## CHAPTER 10




1. The website address of the JNF is www.kkl.org.il; a limited English version can be found at www.jnf.org.il from which most of the information in this chapter is taken.



2. Khalidi (ed.), All That Remains, p. 169.



3. In Israeli Hebrew, ‘kfar’ normally means ‘Palestinian village’, i.e., there are no ‘Jewish’ villages as Hebrew uses instead yishuvim (settlements), kibbutzim, moshavim, etc.



4. Khalidi (ed.), All That Remains, p. 169.





## CHAPTER 11




1. For the years 1964–1968, which I have called the ‘bogus PLO’, see Ilan Pappe, A History of Modern Palestine: One Land, Two Peoples.



2. Ramzy Baroud (ed.), Searching Jenin: Eyewitness Accounts of the Israeli Invasion 2002.



3. Ibid., p. 53–5.



4. Literally called ‘The Law for Safeguarding the Rejection of the Right of Return, 2001’.





## CHAPTER 12




1. The Arab members come from three parties: the Communist Party (Hadash), the National Party of Azmi Bishara (Balad) and the United Arab List drawn up by the more pragmatic branch of the Islamic movement.



2. Entry for 12 June 1895, where Herzl discusses his proposal for a shift from building a Jewish society in Palestine to forming a state for Jews, as translated by Michael Prior from the original German; see Michael Prior, ‘Zionism and the Challenge of Historical truth and Morality,’ in Prior (ed.), Speaking the Truth about Zionism and Israel, p. 27.



3. From a speech in front of the Mapai Centre, 3 December 1947, reproduced in full in Ben-Gurion, As Israel Fights, p. 255.



4. Quoted in Yediot Achrinot, 17 December 2003.



5. ‘Disengagement’ is, of course, Zionist newspeak, and was invented to circumvent the use of such terms as ‘end of occupation’ and to sidestep the obligations incumbent upon Israel, according to international law, as the occupying power in the West Bank and the Gaza Strip.



6. Ruth Gabison, Ha’aretz, 1 December, where she literally says: ‘Le-Israel yesh zkhut le-fakeah al ha-gidul ha-tivi shel ha-‘Aravim.’



7. The term Mizrahim for Arab Jews in Israel came into use in the early 1990s. As Ella Shohat explains, while retaining its implicit opposite, ‘Ashkenazim’, it ‘condenses a number of connotations: it celebrates the past in the Eastern world; it affirms the pan-oriental communities [that] developed in Israel itself; and it invokes a future of revived cohabitation with the Arab-Muslim East’; Ella Shohat, ‘Rupture and Return: A Mizrahi Perspective on the Zionist Discourse’, MIT Electronic Journal of Middle East Studies 1[2001] (my italics).



8. The ‘black’ Jews Israel brought over from Ethiopia in the 1980s were immediately relegated to the poor areas of the periphery and are almost invisible in Israeli society today; discrimination against them is high, as is the suicide rate among them.





## EPILOGUE




1. Ha'aretz, 9 May 2006.



